/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlCobroPorBanco.java
 *
 * Created on 24/05/2010, 20:21:53
 */

package ar.gov.cjpmv.prestamos.gui.creditos.cobros.porbanco;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author dernst
 */
public class PnlCobroPorBanco extends javax.swing.JPanel {

    /** Creates new form PnlCobroPorBanco */
    public PnlCobroPorBanco() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDetalleCobro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtTotalAPagar = new javax.swing.JTextField();
        txtSaldoAcreedor = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        xlblNumeroCredito4 = new org.jdesktop.swingx.JXLabel();
        xlblNumeroCredito5 = new org.jdesktop.swingx.JXLabel();
        xlblNumeroCredito6 = new org.jdesktop.swingx.JXLabel();
        ckbxImprimirRecibo = new javax.swing.JCheckBox();
        xtsTituloSub2 = new org.jdesktop.swingx.JXTitledSeparator();
        btnAgregarCuotas = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtNumeroBoleta = new javax.swing.JTextField();
        txtEntidadBancaria = new javax.swing.JTextField();
        xlblNumeroCredito = new org.jdesktop.swingx.JXLabel();
        xlblNumeroCredito1 = new org.jdesktop.swingx.JXLabel();
        xlblNumeroCredito2 = new org.jdesktop.swingx.JXLabel();
        xlblNumeroCredito3 = new org.jdesktop.swingx.JXLabel();
        CbxCuentaBancaria = new javax.swing.JComboBox();
        dtcFechaCobro = new com.toedter.calendar.JDateChooser();
        xtsTituloSub1 = new org.jdesktop.swingx.JXTitledSeparator();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlCobroPorBanco.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel16.setBackground(resourceMap.getColor("jPanel16.background")); // NOI18N
        jPanel16.setName("jPanel16"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        tblDetalleCobro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null, "", null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {"", "", null, null, null, null, null},
                {"", "", null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº de Crédito", "Solicitante / Garante", "Nº de Legajo", "Titular", "Nº de Cuota", "Periodo", "Valor de la Cuota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalleCobro.setName("tblDetalleCobro"); // NOI18N
        jScrollPane6.setViewportView(tblDetalleCobro);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        txtTotalAPagar.setForeground(resourceMap.getColor("txtTotalAPagar.foreground")); // NOI18N
        txtTotalAPagar.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtTotalAPagar.border.lineColor"), 1, true)); // NOI18N
        txtTotalAPagar.setName("txtTotalAPagar"); // NOI18N

        txtSaldoAcreedor.setForeground(resourceMap.getColor("txtSaldoAcreedor.foreground")); // NOI18N
        txtSaldoAcreedor.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtSaldoAcreedor.border.lineColor"), 1, true)); // NOI18N
        txtSaldoAcreedor.setName("txtSaldoAcreedor"); // NOI18N

        txtTotal.setForeground(resourceMap.getColor("txtTotal.foreground")); // NOI18N
        txtTotal.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtTotal.border.lineColor"), 1, true)); // NOI18N
        txtTotal.setName("txtTotal"); // NOI18N

        xlblNumeroCredito4.setForeground(resourceMap.getColor("xlblNumeroCredito4.foreground")); // NOI18N
        xlblNumeroCredito4.setText(resourceMap.getString("xlblNumeroCredito4.text")); // NOI18N
        xlblNumeroCredito4.setName("xlblNumeroCredito4"); // NOI18N

        xlblNumeroCredito5.setForeground(resourceMap.getColor("xlblNumeroCredito5.foreground")); // NOI18N
        xlblNumeroCredito5.setText(resourceMap.getString("xlblNumeroCredito5.text")); // NOI18N
        xlblNumeroCredito5.setName("xlblNumeroCredito5"); // NOI18N

        xlblNumeroCredito6.setForeground(resourceMap.getColor("xlblNumeroCredito6.foreground")); // NOI18N
        xlblNumeroCredito6.setText(resourceMap.getString("xlblNumeroCredito6.text")); // NOI18N
        xlblNumeroCredito6.setName("xlblNumeroCredito6"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xlblNumeroCredito4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(xlblNumeroCredito6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlblNumeroCredito5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldoAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlblNumeroCredito5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlblNumeroCredito6, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)))
            .addComponent(xlblNumeroCredito4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ckbxImprimirRecibo.setBackground(resourceMap.getColor("ckbxImprimirRecibo.background")); // NOI18N
        ckbxImprimirRecibo.setForeground(resourceMap.getColor("ckbxImprimirRecibo.foreground")); // NOI18N
        ckbxImprimirRecibo.setText(resourceMap.getString("ckbxImprimirRecibo.text")); // NOI18N
        ckbxImprimirRecibo.setName("ckbxImprimirRecibo"); // NOI18N
        ckbxImprimirRecibo.setOpaque(false);

        xtsTituloSub2.setForeground(resourceMap.getColor("xtsTituloSub2.foreground")); // NOI18N
        xtsTituloSub2.setFont(resourceMap.getFont("xtsTituloSub2.font")); // NOI18N
        xtsTituloSub2.setName("xtsTituloSub2"); // NOI18N
        xtsTituloSub2.setTitle(resourceMap.getString("xtsTituloSub2.title")); // NOI18N

        btnAgregarCuotas.setForeground(resourceMap.getColor("btnAgregarCuotas.foreground")); // NOI18N
        btnAgregarCuotas.setIcon(resourceMap.getIcon("btnAgregarCuotas.icon")); // NOI18N
        btnAgregarCuotas.setText(resourceMap.getString("btnAgregarCuotas.text")); // NOI18N
        btnAgregarCuotas.setName("btnAgregarCuotas"); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                        .addComponent(ckbxImprimirRecibo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(xtsTituloSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                        .addComponent(btnAgregarCuotas)))
                .addGap(21, 21, 21))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtsTituloSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbxImprimirRecibo)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel19.setBackground(resourceMap.getColor("jPanel19.background")); // NOI18N
        jPanel19.setName("jPanel19"); // NOI18N

        txtNumeroBoleta.setForeground(resourceMap.getColor("txtNumeroBoleta.foreground")); // NOI18N
        txtNumeroBoleta.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtNumeroBoleta.border.lineColor"), 1, true)); // NOI18N
        txtNumeroBoleta.setName("txtNumeroBoleta"); // NOI18N

        txtEntidadBancaria.setBackground(resourceMap.getColor("txtEntidadBancaria.background")); // NOI18N
        txtEntidadBancaria.setForeground(resourceMap.getColor("txtEntidadBancaria.foreground")); // NOI18N
        txtEntidadBancaria.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtEntidadBancaria.border.lineColor"), 1, true)); // NOI18N
        txtEntidadBancaria.setName("txtEntidadBancaria"); // NOI18N

        xlblNumeroCredito.setForeground(resourceMap.getColor("xlblNumeroCredito.foreground")); // NOI18N
        xlblNumeroCredito.setText(resourceMap.getString("xlblNumeroCredito.text")); // NOI18N
        xlblNumeroCredito.setName("xlblNumeroCredito"); // NOI18N

        xlblNumeroCredito1.setForeground(resourceMap.getColor("xlblNumeroCredito1.foreground")); // NOI18N
        xlblNumeroCredito1.setText(resourceMap.getString("xlblNumeroCredito1.text")); // NOI18N
        xlblNumeroCredito1.setName("xlblNumeroCredito1"); // NOI18N

        xlblNumeroCredito2.setForeground(resourceMap.getColor("xlblNumeroCredito2.foreground")); // NOI18N
        xlblNumeroCredito2.setText(resourceMap.getString("xlblNumeroCredito2.text")); // NOI18N
        xlblNumeroCredito2.setName("xlblNumeroCredito2"); // NOI18N

        xlblNumeroCredito3.setForeground(resourceMap.getColor("xlblNumeroCredito3.foreground")); // NOI18N
        xlblNumeroCredito3.setText(resourceMap.getString("xlblNumeroCredito3.text")); // NOI18N
        xlblNumeroCredito3.setName("xlblNumeroCredito3"); // NOI18N

        CbxCuentaBancaria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxCuentaBancaria.setName("CbxCuentaBancaria"); // NOI18N

        dtcFechaCobro.setForeground(resourceMap.getColor("dtcFechaCobro.foreground")); // NOI18N
        dtcFechaCobro.setName("dtcFechaCobro"); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xlblNumeroCredito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlblNumeroCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcFechaCobro, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txtNumeroBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xlblNumeroCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlblNumeroCredito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEntidadBancaria, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(CbxCuentaBancaria, 0, 217, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xlblNumeroCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEntidadBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xlblNumeroCredito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtcFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xlblNumeroCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xlblNumeroCredito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        xtsTituloSub1.setForeground(resourceMap.getColor("xtsTituloSub1.foreground")); // NOI18N
        xtsTituloSub1.setFont(resourceMap.getFont("xtsTituloSub1.font")); // NOI18N
        xtsTituloSub1.setName("xtsTituloSub1"); // NOI18N
        xtsTituloSub1.setTitle(resourceMap.getString("xtsTituloSub1.title")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xtsTituloSub1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xtsTituloSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbxCuentaBancaria;
    private javax.swing.JButton btnAgregarCuotas;
    private javax.swing.JCheckBox ckbxImprimirRecibo;
    private com.toedter.calendar.JDateChooser dtcFechaCobro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblDetalleCobro;
    private javax.swing.JTextField txtEntidadBancaria;
    private javax.swing.JTextField txtNumeroBoleta;
    private javax.swing.JTextField txtSaldoAcreedor;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAPagar;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito1;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito2;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito3;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito4;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito5;
    private org.jdesktop.swingx.JXLabel xlblNumeroCredito6;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloSub1;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloSub2;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarCuotas(){
    	return this.btnAgregarCuotas;
    }
    
    public JTable getTblDetalleCobro(){
    	return this.tblDetalleCobro;
    }
    
    
    public JTextField  getTxtEntidadBancaria(){
    	return this.txtEntidadBancaria;
    }
    
    public JTextField getTxtNumeroBoleta(){
    	return this.txtNumeroBoleta;
    }
    
    
    public JDateChooser getDtcFechaCobro(){
    	return this.dtcFechaCobro;
    }
    
    
    public JComboBox getCbxCuentaBancaria(){
    	return this.CbxCuentaBancaria;
    }
    
    
    public JCheckBox getCkbxImprimirRecibo(){
    	return this.ckbxImprimirRecibo;
    }
    
    public JTextField getTxtSaldoAcreedor(){
    	return this.txtSaldoAcreedor;
    }
    
    public JTextField getTxtTotal(){
    	return this.txtTotal;
    }
    
    public JTextField getTxtTotalAPagar(){
    	return this.txtTotalAPagar;
    }

    
    
    
}
