/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlDchaBusquedaView.java
 *
 * Created on 30/12/2009, 00:15:07
 */

package ar.gov.cjpmv.prestamos.gui.comunes;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;



/**
 *
 * @author daiana
 */
public class PnlDchaBusquedaView extends javax.swing.JPanel {

    /** Creates new form PnlDchaBusquedaView */
    public PnlDchaBusquedaView() {
   //     initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPnlDcha = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        sllpBusquedaDcha = new javax.swing.JScrollPane();
        if (this.pnlBusquedaDcha == null){
        	pnlBusquedaDcha = new javax.swing.JPanel();
        }
        xtsTituloParametroBusqueda = new org.jdesktop.swingx.JXTitledSeparator();
        

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDchaBusquedaView.class);
        setBackground(resourceMap.getColor("FondoCeleste")); // NOI18N
        setMinimumSize(new java.awt.Dimension(594, 500));
        setName("Form"); // NOI18N

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setIcon(resourceMap.getIcon("lblTituloPnlDcha.icon")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        btnImprimir.setFont(resourceMap.getFont("TextoCampo")); // NOI18N
        btnImprimir.setIcon(resourceMap.getIcon("btnImprimir.icon")); // NOI18N
        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.setName("btnImprimir"); // NOI18N

        sllpBusquedaDcha.setBackground(resourceMap.getColor("FondoCeleste")); // NOI18N
        sllpBusquedaDcha.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        sllpBusquedaDcha.setForeground(resourceMap.getColor("FondoCeleste")); // NOI18N
        sllpBusquedaDcha.setName("sllpBusquedaDcha"); // NOI18N

        pnlBusquedaDcha.setBackground(resourceMap.getColor("pnlBusquedaDcha.background")); // NOI18N
        pnlBusquedaDcha.setName("pnlBusquedaDcha"); // NOI18N
        pnlBusquedaDcha.setPreferredSize(new java.awt.Dimension(600, 449));

        xtsTituloParametroBusqueda.setForeground(resourceMap.getColor("xtsTituloParametroBusqueda.foreground")); // NOI18N
        xtsTituloParametroBusqueda.setFont(resourceMap.getFont("TtuloBarrita")); // NOI18N
        xtsTituloParametroBusqueda.setName("xtsTituloParametroBusqueda"); // NOI18N
        xtsTituloParametroBusqueda.setTitle(resourceMap.getString("xtsTituloParametroBusqueda.title")); // NOI18N

        sllpBusquedaDcha.setViewportView(pnlBusquedaDcha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloPnlDcha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sllpBusquedaDcha, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sllpBusquedaDcha, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBusquedaDcha;
    private javax.swing.JScrollPane sllpBusquedaDcha;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloParametroBusqueda;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Es el panel interno que realmente hace la búsqueda
     */
    public javax.swing.JPanel getPnlBusquedaDcha() {
		return pnlBusquedaDcha;
	}
    public void setPnlBusquedaDcha(javax.swing.JPanel pnlBusquedaDcha) {
		this.pnlBusquedaDcha = pnlBusquedaDcha;
		this.initComponents();
		this.btnImprimir.setVisible(false);
	}
    
    /**
     * En este label se setea el título que tiene la flecha 
     * @return
     */
    public javax.swing.JLabel getLblTituloPnlDcha() {
		return lblTituloPnlDcha;
	}
    
    public javax.swing.JButton getBtnImprimir() {
		return btnImprimir;
	}
    
    
}
