/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlResultadoBusquedaView.java
 *
 * Created on 28/12/2009, 23:10:58
 */

package ar.gov.cjpmv.prestamos.gui.comunes;

import java.awt.Component;

import ar.gov.cjpmv.prestamos.gui.utiles.JTableOrdenable;

/**
 *
 * @author pulpol
 */
public class PnlResultadoBusquedaView extends javax.swing.JPanel {

    /** Creates new form PnlResultadoBusquedaView */
    public PnlResultadoBusquedaView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scllpResultadoBusqueda = new javax.swing.JScrollPane();
        tblResultadoBusqueda = new JTableOrdenable();
        lblResultado = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblImprimir = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlResultadoBusquedaView.class);
        setBackground(resourceMap.getColor("ColorGris")); // NOI18N
        setName("Form"); // NOI18N

        scllpResultadoBusqueda.setName("scllpResultadoBusqueda"); // NOI18N

        tblResultadoBusqueda.setFont(resourceMap.getFont("ContenidoTabla")); // NOI18N
        tblResultadoBusqueda.setForeground(resourceMap.getColor("ColorContenidoTabla")); // NOI18N
        tblResultadoBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultadoBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblResultadoBusqueda.setName("tblResultadoBusqueda"); // NOI18N
        scllpResultadoBusqueda.setViewportView(tblResultadoBusqueda);
        tblResultadoBusqueda.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblResultadoBusqueda.columnModel.title0")); // NOI18N
        tblResultadoBusqueda.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblResultadoBusqueda.columnModel.title1")); // NOI18N
        tblResultadoBusqueda.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblResultadoBusqueda.columnModel.title2")); // NOI18N
        tblResultadoBusqueda.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblResultadoBusqueda.columnModel.title3")); // NOI18N

        lblResultado.setForeground(resourceMap.getColor("lblResultado.foreground")); // NOI18N
        lblResultado.setText(resourceMap.getString("lblResultado.text")); // NOI18N
        lblResultado.setName("lblResultado"); // NOI18N

        pnlBotonera.setBackground(resourceMap.getColor("ColorGris")); // NOI18N
        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblImprimir.setForeground(resourceMap.getColor("lblImprimir.foreground")); // NOI18N
        lblImprimir.setIcon(resourceMap.getIcon("lblImprimir.icon")); // NOI18N
        lblImprimir.setText(resourceMap.getString("lblImprimir.text")); // NOI18N
        lblImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImprimir.setName("lblImprimir"); // NOI18N
        pnlBotonera.add(lblImprimir);

        lblEditar.setForeground(resourceMap.getColor("lblEditar.foreground")); // NOI18N
        lblEditar.setIcon(resourceMap.getIcon("lblEditar.icon")); // NOI18N
        lblEditar.setText(resourceMap.getString("lblEditar.text")); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.setName("lblEditar"); // NOI18N
        pnlBotonera.add(lblEditar);

        lblEliminar.setForeground(resourceMap.getColor("lblEliminar.foreground")); // NOI18N
        lblEliminar.setIcon(resourceMap.getIcon("lblEliminar.icon")); // NOI18N
        lblEliminar.setText(resourceMap.getString("lblEliminar.text")); // NOI18N
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setName("lblEliminar"); // NOI18N
        pnlBotonera.add(lblEliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scllpResultadoBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResultado)
                    .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scllpResultadoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblImprimir;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JScrollPane scllpResultadoBusqueda;
    private javax.swing.JTable tblResultadoBusqueda;
    // End of variables declaration//GEN-END:variables
	
    
    public javax.swing.JLabel getLblEditar() {
		return lblEditar;
	}

	public javax.swing.JLabel getLblEliminar() {
		return lblEliminar;
	}

	public javax.swing.JLabel getLblImprimir() {
		return lblImprimir;
	}

	public javax.swing.JTable getTblResultadoBusqueda() {
		return tblResultadoBusqueda;
	}

	public javax.swing.JLabel getLblResultado() {
		return lblResultado;
	}

	@Override
	public void setEnabled(boolean enabled) {
		super.setEnabled(enabled);
		//La botonera
		for (Component cadaComponent : this.pnlBotonera.getComponents()){
			cadaComponent.setEnabled(enabled);
		}
		this.tblResultadoBusqueda.setEnabled(enabled);
		
	}


	public javax.swing.JPanel getPnlBotonera() {
		return pnlBotonera;
	}

	public void setTitulo(String pTitulo) {
		this.getLblResultado().setText(pTitulo);
	}
	

	
}
