/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlCobroPorHaberesCaja.java
 *
 * Created on 20/08/2010, 21:48:21
 */

package ar.gov.cjpmv.prestamos.gui.creditos.cobros.porHaberesCaja;

import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JRadioButton;
import javax.swing.JTable;

import ar.gov.cjpmv.prestamos.gui.utiles.JTableOrdenable;

import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;

/**
 *
 * @author dernst
 */
public class PnlCobroPorHaberesCaja extends javax.swing.JPanel {

    /** Creates new form PnlCobroPorHaberesCaja */
    public PnlCobroPorHaberesCaja() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCobroCaja = new ar.gov.cjpmv.prestamos.gui.utiles.JTableOrdenable();
        lblTituloSeleccionFecha1 = new javax.swing.JLabel();
        rbtnLegajo = new javax.swing.JRadioButton();
        rbtnApellidoNombre = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        ycAnio = new com.toedter.calendar.JYearChooser();
        lblAnio = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        btnGenerarCobro = new javax.swing.JButton();
        mchMes = new com.toedter.calendar.JMonthChooser();
        lblTituloSeleccionFecha = new javax.swing.JLabel();
        xtsTituloParametroBusqueda = new org.jdesktop.swingx.JXTitledSeparator();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlCobroPorHaberesCaja.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblCobroCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCobroCaja.setName("tblCobroCaja"); // NOI18N
        jScrollPane1.setViewportView(tblCobroCaja);

        lblTituloSeleccionFecha1.setFont(resourceMap.getFont("lblTituloSeleccionFecha1.font")); // NOI18N
        lblTituloSeleccionFecha1.setForeground(resourceMap.getColor("lblTituloSeleccionFecha1.foreground")); // NOI18N
        lblTituloSeleccionFecha1.setText(resourceMap.getString("lblTituloSeleccionFecha1.text")); // NOI18N
        lblTituloSeleccionFecha1.setName("lblTituloSeleccionFecha1"); // NOI18N

        rbtnLegajo.setBackground(resourceMap.getColor("rbtnLegajo.background")); // NOI18N
        buttonGroup1.add(rbtnLegajo);
        rbtnLegajo.setText(resourceMap.getString("rbtnLegajo.text")); // NOI18N
        rbtnLegajo.setName("rbtnLegajo"); // NOI18N

        rbtnApellidoNombre.setBackground(resourceMap.getColor("rbtnApellidoNombre.background")); // NOI18N
        buttonGroup1.add(rbtnApellidoNombre);
        rbtnApellidoNombre.setText(resourceMap.getString("rbtnApellidoNombre.text")); // NOI18N
        rbtnApellidoNombre.setName("rbtnApellidoNombre"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtnLegajo)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnApellidoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTituloSeleccionFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnLegajo)
                    .addComponent(rbtnApellidoNombre)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTituloSeleccionFecha1)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        ycAnio.setName("ycAnio"); // NOI18N

        lblAnio.setText(resourceMap.getString("lblAnio.text")); // NOI18N
        lblAnio.setName("lblAnio"); // NOI18N

        lblMes.setText(resourceMap.getString("lblMes.text")); // NOI18N
        lblMes.setName("lblMes"); // NOI18N

        btnGenerarCobro.setFont(resourceMap.getFont("btnGenerarCobro.font")); // NOI18N
        btnGenerarCobro.setForeground(resourceMap.getColor("btnGenerarCobro.foreground")); // NOI18N
        btnGenerarCobro.setText(resourceMap.getString("btnGenerarCobro.text")); // NOI18N
        btnGenerarCobro.setActionCommand(resourceMap.getString("btnGenerarCobro.actionCommand")); // NOI18N
        btnGenerarCobro.setName("btnGenerarCobro"); // NOI18N

        mchMes.setName("mchMes"); // NOI18N
        mchMes.setYearChooser(null);

        lblTituloSeleccionFecha.setFont(resourceMap.getFont("lblTituloSeleccionFecha.font")); // NOI18N
        lblTituloSeleccionFecha.setForeground(resourceMap.getColor("lblTituloSeleccionFecha.foreground")); // NOI18N
        lblTituloSeleccionFecha.setText(resourceMap.getString("lblTituloSeleccionFecha.text")); // NOI18N
        lblTituloSeleccionFecha.setName("lblTituloSeleccionFecha"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloSeleccionFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mchMes, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ycAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerarCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloSeleccionFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ycAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnGenerarCobro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(mchMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        xtsTituloParametroBusqueda.setForeground(resourceMap.getColor("xtsTituloParametroBusqueda.foreground")); // NOI18N
        xtsTituloParametroBusqueda.setFont(resourceMap.getFont("xtsTituloParametroBusqueda.font")); // NOI18N
        xtsTituloParametroBusqueda.setName("xtsTituloParametroBusqueda"); // NOI18N
        xtsTituloParametroBusqueda.setTitle(resourceMap.getString("xtsTituloParametroBusqueda.title")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarCobro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblTituloSeleccionFecha;
    private javax.swing.JLabel lblTituloSeleccionFecha1;
    private com.toedter.calendar.JMonthChooser mchMes;
    private javax.swing.JRadioButton rbtnApellidoNombre;
    private javax.swing.JRadioButton rbtnLegajo;
    private ar.gov.cjpmv.prestamos.gui.utiles.JTableOrdenable tblCobroCaja;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloParametroBusqueda;
    private com.toedter.calendar.JYearChooser ycAnio;
    // End of variables declaration//GEN-END:variables

    
    public JMonthChooser getMchMes(){
    	return this.mchMes;
    }
    
    public JYearChooser getYchAnio(){
    	return this.ycAnio;
    }
    
    public JButton getBtnCobrar(){
    	return this.btnGenerarCobro;
    }
    
    public JTable getTblCobroCaja(){
    	return this.tblCobroCaja;
    }
    
    public JRadioButton getRbtnOrdenarPorLegajo(){
    	return this.rbtnLegajo;
    }
    
    public JRadioButton getRbtnOrdenarPorApellidoNombre(){
    	return this.rbtnApellidoNombre;
    }
 
    
}
