/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetalleCuotas.java
 *
 * Created on 09/02/2010, 22:21:42
 */

package ar.gov.cjpmv.prestamos.gui.creditos;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;

/**
 *
 * @author daiana
 */
public class DetalleCuotas extends javax.swing.JDialog {

    /** Creates new form DetalleCuotas */
  /*  public DetalleCuotas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    */
    
    public DetalleCuotas(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sllpCuotas = new javax.swing.JScrollPane();
        tblCuotas = new javax.swing.JTable();
        xtsCuotas = new org.jdesktop.swingx.JXTitledSeparator();
        xtsReferencias = new org.jdesktop.swingx.JXTitledSeparator();
        lblCanceladas = new javax.swing.JLabel();
        lblAdeudadasVencidas = new javax.swing.JLabel();
        lblAdeudadasNoVencidas = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        sllpCuotas.setName("sllpCuotas"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(DetalleCuotas.class);
        tblCuotas.setFont(resourceMap.getFont("Campo")); // NOI18N
        tblCuotas.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        tblCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "Nº de Cuota", "Vencimiento", "Capital", "Interes", "Otros Conceptos", "Valor Total"
            }
        ));
        tblCuotas.setName("tblCuotas"); // NOI18N
        sllpCuotas.setViewportView(tblCuotas);
        tblCuotas.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title0")); // NOI18N
        tblCuotas.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title1")); // NOI18N
        tblCuotas.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title2")); // NOI18N
        tblCuotas.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title3")); // NOI18N
        tblCuotas.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title4")); // NOI18N
        tblCuotas.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title5")); // NOI18N
        tblCuotas.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("tblCuotas.columnModel.title6")); // NOI18N

        xtsCuotas.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsCuotas.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsCuotas.setName("xtsCuotas"); // NOI18N
        xtsCuotas.setTitle(resourceMap.getString("xtsCuotas.title")); // NOI18N

        xtsReferencias.setForeground(resourceMap.getColor("xtsReferencias.foreground")); // NOI18N
        xtsReferencias.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsReferencias.setName("xtsReferencias"); // NOI18N
        xtsReferencias.setTitle(resourceMap.getString("xtsReferencias.title")); // NOI18N

        lblCanceladas.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblCanceladas.setForeground(resourceMap.getColor("lblCanceladas.foreground")); // NOI18N
        lblCanceladas.setText(resourceMap.getString("lblCanceladas.text")); // NOI18N
        lblCanceladas.setName("lblCanceladas"); // NOI18N

        lblAdeudadasVencidas.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblAdeudadasVencidas.setForeground(resourceMap.getColor("lblAdeudadasVencidas.foreground")); // NOI18N
        lblAdeudadasVencidas.setText(resourceMap.getString("lblAdeudadasVencidas.text")); // NOI18N
        lblAdeudadasVencidas.setName("lblAdeudadasVencidas"); // NOI18N

        lblAdeudadasNoVencidas.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblAdeudadasNoVencidas.setForeground(resourceMap.getColor("lblAdeudadasNoVencidas.foreground")); // NOI18N
        lblAdeudadasNoVencidas.setText(resourceMap.getString("lblAdeudadasNoVencidas.text")); // NOI18N
        lblAdeudadasNoVencidas.setName("lblAdeudadasNoVencidas"); // NOI18N

        btnImprimir.setFont(resourceMap.getFont("btnImprimir.font")); // NOI18N
        btnImprimir.setIcon(resourceMap.getIcon("btnImprimir.icon")); // NOI18N
        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setMaximumSize(new java.awt.Dimension(121, 23));
        btnImprimir.setName("btnImprimir"); // NOI18N
        btnImprimir.setPreferredSize(new java.awt.Dimension(101, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sllpCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(xtsReferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCanceladas)
                        .addGap(18, 18, 18)
                        .addComponent(lblAdeudadasNoVencidas)
                        .addGap(18, 18, 18)
                        .addComponent(lblAdeudadasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xtsCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sllpCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtsReferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCanceladas)
                        .addComponent(lblAdeudadasNoVencidas)
                        .addComponent(lblAdeudadasVencidas)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetalleCuotas dialog = new DetalleCuotas(new JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdeudadasNoVencidas;
    private javax.swing.JLabel lblAdeudadasVencidas;
    private javax.swing.JLabel lblCanceladas;
    private javax.swing.JScrollPane sllpCuotas;
    private javax.swing.JTable tblCuotas;
    private org.jdesktop.swingx.JXTitledSeparator xtsCuotas;
    private org.jdesktop.swingx.JXTitledSeparator xtsReferencias;
    // End of variables declaration//GEN-END:variables
    
    
    public JTable getTblCuotas(){
    	return this.tblCuotas;
    }
    
    public JButton getBtnImprimir(){
    	return this.btnImprimir;
    }

}
