/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EstadoCuenta.java
 *
 * Created on 09/02/2010, 21:35:34
 */

package ar.gov.cjpmv.prestamos.gui.creditos;

import javax.swing.JDialog;
import javax.swing.JPanel;

import org.jdesktop.swingx.JXHyperlink;
import org.jdesktop.swingx.JXTitledSeparator;

/**
 *
 * @author daiana
 */
public class EstadoCuenta extends javax.swing.JDialog {

    /** Creates new form EstadoCuenta */
    public EstadoCuenta(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoBlanco = new javax.swing.JPanel();
        pnlCreditosEnCurso = new javax.swing.JPanel();
        sllpCreditosEnCurso = new javax.swing.JScrollPane();
        tblCreditosEnCurso = new javax.swing.JTable();
        xtsCreditos = new org.jdesktop.swingx.JXTitledSeparator();
        xhDetalleCuotasCreditos = new org.jdesktop.swingx.JXHyperlink();
        xtsTotalAdeudado = new org.jdesktop.swingx.JXTitledSeparator();
        lblMontoAdeudadoCredito = new javax.swing.JLabel();
        lblMontoAdeudadoCredito1 = new javax.swing.JLabel();
        xtsSobranteCuentaCorriente = new org.jdesktop.swingx.JXTitledSeparator();
        xhCancelarCredito = new org.jdesktop.swingx.JXHyperlink();
        xtsCreditosEnCurso = new org.jdesktop.swingx.JXTitledSeparator();
        xtsGarantiasEnCurso = new org.jdesktop.swingx.JXTitledSeparator();
        pnlGarantiasEnCurso = new javax.swing.JPanel();
        sllpGarantiasEnCurso = new javax.swing.JScrollPane();
        tblGarantiasEnCurso = new javax.swing.JTable();
        xtsCreditoGarantia = new org.jdesktop.swingx.JXTitledSeparator();
        xhDetalleCuotasGarantias = new org.jdesktop.swingx.JXHyperlink();
        xtsTotalAdeudadoGarantia = new org.jdesktop.swingx.JXTitledSeparator();
        xtsRespondiendoComoGarante = new org.jdesktop.swingx.JXTitledSeparator();
        lblRespondiendoComoGarante = new javax.swing.JLabel();
        lblTotalAdeudadoGarantias = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(EstadoCuenta.class);
        pnlFondoBlanco.setBackground(resourceMap.getColor("pnlFondoBlanco.background")); // NOI18N
        pnlFondoBlanco.setName("pnlFondoBlanco"); // NOI18N

        pnlCreditosEnCurso.setBackground(resourceMap.getColor("pnlCreditosEnCurso.background")); // NOI18N
        pnlCreditosEnCurso.setName("pnlCreditosEnCurso"); // NOI18N

        sllpCreditosEnCurso.setName("sllpCreditosEnCurso"); // NOI18N

        tblCreditosEnCurso.setFont(resourceMap.getFont("Campo")); // NOI18N
        tblCreditosEnCurso.setForeground(resourceMap.getColor("tblCreditosEnCurso.foreground")); // NOI18N
        tblCreditosEnCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Fecha Inicio", "Monto Total", "Cantidad de Cuotas", "Cuotas Adeudadas", "Saldo Adeudado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCreditosEnCurso.setGridColor(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        tblCreditosEnCurso.setName("tblCreditosEnCurso"); // NOI18N
        sllpCreditosEnCurso.setViewportView(tblCreditosEnCurso);

        xtsCreditos.setForeground(resourceMap.getColor("xtsCreditos.foreground")); // NOI18N
        xtsCreditos.setFont(resourceMap.getFont("Campo")); // NOI18N
        xtsCreditos.setName("xtsCreditos"); // NOI18N
        xtsCreditos.setTitle(resourceMap.getString("xtsCreditos.title")); // NOI18N

        xhDetalleCuotasCreditos.setIcon(resourceMap.getIcon("xhDetalleCuotasCreditos.icon")); // NOI18N
        xhDetalleCuotasCreditos.setText(resourceMap.getString("xhDetalleCuotasCreditos.text")); // NOI18N
        xhDetalleCuotasCreditos.setClickedColor(resourceMap.getColor("xhDetalleCuotasCreditos.clickedColor")); // NOI18N
        xhDetalleCuotasCreditos.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xhDetalleCuotasCreditos.setName("xhDetalleCuotasCreditos"); // NOI18N
        xhDetalleCuotasCreditos.setUnclickedColor(resourceMap.getColor("xhDetalleCuotasCreditos.unclickedColor")); // NOI18N
        xhDetalleCuotasCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xhDetalleCuotasCreditosActionPerformed(evt);
            }
        });

        xtsTotalAdeudado.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsTotalAdeudado.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsTotalAdeudado.setName("xtsTotalAdeudado"); // NOI18N
        xtsTotalAdeudado.setTitle(resourceMap.getString("xtsTotalAdeudado.title")); // NOI18N

        lblMontoAdeudadoCredito.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblMontoAdeudadoCredito.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        lblMontoAdeudadoCredito.setText(resourceMap.getString("lblMontoAdeudadoCredito.text")); // NOI18N
        lblMontoAdeudadoCredito.setName("lblMontoAdeudadoCredito"); // NOI18N

        lblMontoAdeudadoCredito1.setFont(resourceMap.getFont("lblMontoAdeudadoCredito1.font")); // NOI18N
        lblMontoAdeudadoCredito1.setForeground(resourceMap.getColor("lblMontoAdeudadoCredito1.foreground")); // NOI18N
        lblMontoAdeudadoCredito1.setText(resourceMap.getString("lblMontoAdeudadoCredito1.text")); // NOI18N
        lblMontoAdeudadoCredito1.setName("lblMontoAdeudadoCredito1"); // NOI18N

        xtsSobranteCuentaCorriente.setForeground(resourceMap.getColor("xtsSobranteCuentaCorriente.foreground")); // NOI18N
        xtsSobranteCuentaCorriente.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsSobranteCuentaCorriente.setName("xtsSobranteCuentaCorriente"); // NOI18N
        xtsSobranteCuentaCorriente.setTitle(resourceMap.getString("xtsSobranteCuentaCorriente.title")); // NOI18N

        xhCancelarCredito.setIcon(resourceMap.getIcon("xhCancelarCredito.icon")); // NOI18N
        xhCancelarCredito.setText(resourceMap.getString("xhCancelarCredito.text")); // NOI18N
        xhCancelarCredito.setClickedColor(resourceMap.getColor("xhCancelarCredito.clickedColor")); // NOI18N
        xhCancelarCredito.setFont(resourceMap.getFont("xhCancelarCredito.font")); // NOI18N
        xhCancelarCredito.setName("xhCancelarCredito"); // NOI18N
        xhCancelarCredito.setUnclickedColor(resourceMap.getColor("xhCancelarCredito.unclickedColor")); // NOI18N
        xhCancelarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xhCancelarCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreditosEnCursoLayout = new javax.swing.GroupLayout(pnlCreditosEnCurso);
        pnlCreditosEnCurso.setLayout(pnlCreditosEnCursoLayout);
        pnlCreditosEnCursoLayout.setHorizontalGroup(
            pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditosEnCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreditosEnCursoLayout.createSequentialGroup()
                        .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sllpCreditosEnCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCreditosEnCursoLayout.createSequentialGroup()
                                .addComponent(xtsCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                                .addComponent(xhCancelarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xhDetalleCuotasCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCreditosEnCursoLayout.createSequentialGroup()
                                .addComponent(xtsSobranteCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMontoAdeudadoCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(pnlCreditosEnCursoLayout.createSequentialGroup()
                        .addComponent(xtsTotalAdeudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMontoAdeudadoCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                        .addGap(79, 79, 79))))
        );
        pnlCreditosEnCursoLayout.setVerticalGroup(
            pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditosEnCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xtsCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xhDetalleCuotasCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xhCancelarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sllpCreditosEnCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTotalAdeudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoAdeudadoCredito))
                .addGap(3, 3, 3)
                .addGroup(pnlCreditosEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMontoAdeudadoCredito1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(xtsSobranteCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        xtsCreditosEnCurso.setForeground(resourceMap.getColor("colorTituloBarrita")); // NOI18N
        xtsCreditosEnCurso.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsCreditosEnCurso.setName("xtsCreditosEnCurso"); // NOI18N
        xtsCreditosEnCurso.setTitle(resourceMap.getString("xtsCreditosEnCurso.title")); // NOI18N

        xtsGarantiasEnCurso.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsGarantiasEnCurso.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsGarantiasEnCurso.setName("xtsGarantiasEnCurso"); // NOI18N
        xtsGarantiasEnCurso.setTitle(resourceMap.getString("xtsGarantiasEnCurso.title")); // NOI18N

        pnlGarantiasEnCurso.setBackground(resourceMap.getColor("pnlGarantiasEnCurso.background")); // NOI18N
        pnlGarantiasEnCurso.setName("pnlGarantiasEnCurso"); // NOI18N

        sllpGarantiasEnCurso.setName("sllpGarantiasEnCurso"); // NOI18N

        tblGarantiasEnCurso.setFont(resourceMap.getFont("Campo")); // NOI18N
        tblGarantiasEnCurso.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        tblGarantiasEnCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Solicitante", "Monto Total", "Cantidad de Cuotas", "Cuotas Adeudadas", "Saldo Adeudado"
            }
        ));
        tblGarantiasEnCurso.setName("tblGarantiasEnCurso"); // NOI18N
        sllpGarantiasEnCurso.setViewportView(tblGarantiasEnCurso);

        xtsCreditoGarantia.setForeground(resourceMap.getColor("xtsCreditoGarantia.foreground")); // NOI18N
        xtsCreditoGarantia.setName("xtsCreditoGarantia"); // NOI18N
        xtsCreditoGarantia.setTitle(resourceMap.getString("xtsCreditoGarantia.title")); // NOI18N

        xhDetalleCuotasGarantias.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xhDetalleCuotasGarantias.setIcon(resourceMap.getIcon("xhDetalleCuotasGarantias.icon")); // NOI18N
        xhDetalleCuotasGarantias.setText(resourceMap.getString("xhDetalleCuotasGarantias.text")); // NOI18N
        xhDetalleCuotasGarantias.setClickedColor(resourceMap.getColor("xhDetalleCuotasGarantias.clickedColor")); // NOI18N
        xhDetalleCuotasGarantias.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xhDetalleCuotasGarantias.setName("xhDetalleCuotasGarantias"); // NOI18N
        xhDetalleCuotasGarantias.setUnclickedColor(resourceMap.getColor("xhDetalleCuotasGarantias.unclickedColor")); // NOI18N
        xhDetalleCuotasGarantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xhDetalleCuotasGarantiasActionPerformed(evt);
            }
        });

        xtsTotalAdeudadoGarantia.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsTotalAdeudadoGarantia.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsTotalAdeudadoGarantia.setName("xtsTotalAdeudadoGarantia"); // NOI18N
        xtsTotalAdeudadoGarantia.setTitle(resourceMap.getString("xtsTotalAdeudadoGarantia.title")); // NOI18N

        xtsRespondiendoComoGarante.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsRespondiendoComoGarante.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsRespondiendoComoGarante.setName("xtsRespondiendoComoGarante"); // NOI18N
        xtsRespondiendoComoGarante.setTitle(resourceMap.getString("xtsRespondiendoComoGarante.title")); // NOI18N

        lblRespondiendoComoGarante.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblRespondiendoComoGarante.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        lblRespondiendoComoGarante.setText(resourceMap.getString("lblRespondiendoComoGarante.text")); // NOI18N
        lblRespondiendoComoGarante.setName("lblRespondiendoComoGarante"); // NOI18N

        lblTotalAdeudadoGarantias.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblTotalAdeudadoGarantias.setForeground(resourceMap.getColor("lblTotalAdeudadoGarantias.foreground")); // NOI18N
        lblTotalAdeudadoGarantias.setText(resourceMap.getString("lblTotalAdeudadoGarantias.text")); // NOI18N
        lblTotalAdeudadoGarantias.setName("lblTotalAdeudadoGarantias"); // NOI18N

        javax.swing.GroupLayout pnlGarantiasEnCursoLayout = new javax.swing.GroupLayout(pnlGarantiasEnCurso);
        pnlGarantiasEnCurso.setLayout(pnlGarantiasEnCursoLayout);
        pnlGarantiasEnCursoLayout.setHorizontalGroup(
            pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                .addGroup(pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                                .addComponent(xtsCreditoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                                .addComponent(xhDetalleCuotasGarantias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sllpGarantiasEnCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                            .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                                .addComponent(xtsRespondiendoComoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRespondiendoComoGarante, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))))
                    .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(xtsTotalAdeudadoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAdeudadoGarantias, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlGarantiasEnCursoLayout.setVerticalGroup(
            pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGarantiasEnCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xtsCreditoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xhDetalleCuotasGarantias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sllpGarantiasEnCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTotalAdeudadoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalAdeudadoGarantias))
                .addGap(3, 3, 3)
                .addGroup(pnlGarantiasEnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsRespondiendoComoGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespondiendoComoGarante))
                .addContainerGap())
        );

        btnImprimir.setIcon(resourceMap.getIcon("btnImprimir.icon")); // NOI18N
        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setMaximumSize(new java.awt.Dimension(121, 23));
        btnImprimir.setName("btnImprimir"); // NOI18N
        btnImprimir.setPreferredSize(new java.awt.Dimension(101, 23));

        javax.swing.GroupLayout pnlFondoBlancoLayout = new javax.swing.GroupLayout(pnlFondoBlanco);
        pnlFondoBlanco.setLayout(pnlFondoBlancoLayout);
        pnlFondoBlancoLayout.setHorizontalGroup(
            pnlFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGarantiasEnCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCreditosEnCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xtsCreditosEnCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtsGarantiasEnCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFondoBlancoLayout.setVerticalGroup(
            pnlFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsCreditosEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCreditosEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(xtsGarantiasEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGarantiasEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xhDetalleCuotasCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xhDetalleCuotasCreditosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_xhDetalleCuotasCreditosActionPerformed

    private void xhDetalleCuotasGarantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xhDetalleCuotasGarantiasActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_xhDetalleCuotasGarantiasActionPerformed

    private void xhCancelarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xhCancelarCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xhCancelarCreditoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstadoCuenta dialog = new EstadoCuenta(new JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel lblMontoAdeudadoCredito;
    private javax.swing.JLabel lblMontoAdeudadoCredito1;
    private javax.swing.JLabel lblRespondiendoComoGarante;
    private javax.swing.JLabel lblTotalAdeudadoGarantias;
    private javax.swing.JPanel pnlCreditosEnCurso;
    private javax.swing.JPanel pnlFondoBlanco;
    private javax.swing.JPanel pnlGarantiasEnCurso;
    private javax.swing.JScrollPane sllpCreditosEnCurso;
    private javax.swing.JScrollPane sllpGarantiasEnCurso;
    private javax.swing.JTable tblCreditosEnCurso;
    private javax.swing.JTable tblGarantiasEnCurso;
    private org.jdesktop.swingx.JXHyperlink xhCancelarCredito;
    private org.jdesktop.swingx.JXHyperlink xhDetalleCuotasCreditos;
    private org.jdesktop.swingx.JXHyperlink xhDetalleCuotasGarantias;
    private org.jdesktop.swingx.JXTitledSeparator xtsCreditoGarantia;
    private org.jdesktop.swingx.JXTitledSeparator xtsCreditos;
    private org.jdesktop.swingx.JXTitledSeparator xtsCreditosEnCurso;
    private org.jdesktop.swingx.JXTitledSeparator xtsGarantiasEnCurso;
    private org.jdesktop.swingx.JXTitledSeparator xtsRespondiendoComoGarante;
    private org.jdesktop.swingx.JXTitledSeparator xtsSobranteCuentaCorriente;
    private org.jdesktop.swingx.JXTitledSeparator xtsTotalAdeudado;
    private org.jdesktop.swingx.JXTitledSeparator xtsTotalAdeudadoGarantia;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtnImprimir() {
		return btnImprimir;
	}

	public void setBtnImprimir(javax.swing.JButton btnImprimir) {
		this.btnImprimir = btnImprimir;
	}

	public javax.swing.JLabel getLblMontoAdeudadoCredito() {
		return lblMontoAdeudadoCredito;
	}

	public void setLblMontoAdeudadoCredito(
			javax.swing.JLabel lblMontoAdeudadoCredito) {
		this.lblMontoAdeudadoCredito = lblMontoAdeudadoCredito;
	}

	public javax.swing.JLabel getLblMontoAdeudadoCredito1() {
		return lblMontoAdeudadoCredito1;
	}

	public void setLblMontoAdeudadoCredito1(
			javax.swing.JLabel lblMontoAdeudadoCredito1) {
		this.lblMontoAdeudadoCredito1 = lblMontoAdeudadoCredito1;
	}

	public javax.swing.JLabel getLblRespondiendoComoGarante() {
		return lblRespondiendoComoGarante;
	}

	public void setLblRespondiendoComoGarante(
			javax.swing.JLabel lblRespondiendoComoGarante) {
		this.lblRespondiendoComoGarante = lblRespondiendoComoGarante;
	}

	public javax.swing.JLabel getLblTotalAdeudadoGarantias() {
		return lblTotalAdeudadoGarantias;
	}

	public void setLblTotalAdeudadoGarantias(
			javax.swing.JLabel lblTotalAdeudadoGarantias) {
		this.lblTotalAdeudadoGarantias = lblTotalAdeudadoGarantias;
	}

	public javax.swing.JTable getTblCreditosEnCurso() {
		return tblCreditosEnCurso;
	}

	public void setTblCreditosEnCurso(javax.swing.JTable tblCreditosEnCurso) {
		this.tblCreditosEnCurso = tblCreditosEnCurso;
	}

	public javax.swing.JTable getTblGarantiasEnCurso() {
		return tblGarantiasEnCurso;
	}

	public void setTblGarantiasEnCurso(javax.swing.JTable tblGarantiasEnCurso) {
		this.tblGarantiasEnCurso = tblGarantiasEnCurso;
	}
	
	public JPanel getPnlGarantiasEnCurso(){
		return this.pnlGarantiasEnCurso;
	}
	
	public JXTitledSeparator getXtsGarantiasEnCurso(){
		return this.xtsGarantiasEnCurso;
	}
	
	public JXHyperlink getXhDetalleCuotasCreditos(){
		return this.xhDetalleCuotasCreditos;
	}
	
	public JXHyperlink getXhDetalleCuotasGarantias(){
		return xhDetalleCuotasGarantias;
	}
	
	public org.jdesktop.swingx.JXHyperlink getXhCancelarCredito() {
		return xhCancelarCredito;
	}
}
