/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlDatosSolicitanteGarante.java
 *
 * Created on 09/02/2010, 23:24:32
 */

package ar.gov.cjpmv.prestamos.gui.creditos;

import javax.swing.JButton;
import javax.swing.JLabel;

import org.jdesktop.swingx.JXTitledSeparator;

import ar.gov.cjpmv.prestamos.gui.creditos.datos.garantes.controllers.PnlDatosSolicitanteGaranteController;
import ar.gov.cjpmv.prestamos.gui.creditos.datos.solicitante.controllers.PnlDatosSolicitanteController;

/**
 *
 * @author daiana
 */
public class PnlDatosSolicitanteGarante extends javax.swing.JPanel {

    /** Creates new form PnlDatosSolicitanteGarante */
    public PnlDatosSolicitanteGarante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        xlblLegajo = new org.jdesktop.swingx.JXLabel();
        xlblTipoDocumento = new org.jdesktop.swingx.JXLabel();
        xlblApellidoRazon = new org.jdesktop.swingx.JXLabel();
        xlblEstado = new org.jdesktop.swingx.JXLabel();
        xlblNumeroDocumento = new org.jdesktop.swingx.JXLabel();
        xlblCui = new org.jdesktop.swingx.JXLabel();
        lblLegajo = new javax.swing.JLabel();
        lblTipoDocumento = new javax.swing.JLabel();
        lblApellidoRazon = new javax.swing.JLabel();
        lblCui = new javax.swing.JLabel();
        lblNumeroDocumento = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDatosSolicitanteGarante.class);
        setBackground(resourceMap.getColor("FondoGris")); // NOI18N
        setName("Form"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setIcon(resourceMap.getIcon("xtsTitulo.icon")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        xlblLegajo.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblLegajo.setText(resourceMap.getString("xlblLegajo.text")); // NOI18N
        xlblLegajo.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblLegajo.setName("xlblLegajo"); // NOI18N

        xlblTipoDocumento.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblTipoDocumento.setText(resourceMap.getString("xlblTipoDocumento.text")); // NOI18N
        xlblTipoDocumento.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblTipoDocumento.setName("xlblTipoDocumento"); // NOI18N

        xlblApellidoRazon.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblApellidoRazon.setText(resourceMap.getString("xlblApellidoRazon.text")); // NOI18N
        xlblApellidoRazon.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblApellidoRazon.setName("xlblApellidoRazon"); // NOI18N

        xlblEstado.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblEstado.setText(resourceMap.getString("xlblEstado.text")); // NOI18N
        xlblEstado.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblEstado.setName("xlblEstado"); // NOI18N

        xlblNumeroDocumento.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblNumeroDocumento.setText(resourceMap.getString("xlblNumeroDocumento.text")); // NOI18N
        xlblNumeroDocumento.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblNumeroDocumento.setName("xlblNumeroDocumento"); // NOI18N

        xlblCui.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xlblCui.setText(resourceMap.getString("xlblCui.text")); // NOI18N
        xlblCui.setFont(resourceMap.getFont("Campo")); // NOI18N
        xlblCui.setName("xlblCui"); // NOI18N

        lblLegajo.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblLegajo.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblLegajo.setText(resourceMap.getString("lblLegajo.text")); // NOI18N
        lblLegajo.setName("lblLegajo"); // NOI18N

        lblTipoDocumento.setForeground(resourceMap.getColor("lblTipoDocumento.foreground")); // NOI18N
        lblTipoDocumento.setText(resourceMap.getString("lblTipoDocumento.text")); // NOI18N
        lblTipoDocumento.setName("lblTipoDocumento"); // NOI18N

        lblApellidoRazon.setForeground(resourceMap.getColor("lblApellidoRazon.foreground")); // NOI18N
        lblApellidoRazon.setText(resourceMap.getString("lblApellidoRazon.text")); // NOI18N
        lblApellidoRazon.setName("lblApellidoRazon"); // NOI18N

        lblCui.setForeground(resourceMap.getColor("lblCui.foreground")); // NOI18N
        lblCui.setText(resourceMap.getString("lblCui.text")); // NOI18N
        lblCui.setName("lblCui"); // NOI18N

        lblNumeroDocumento.setForeground(resourceMap.getColor("lblNumeroDocumento.foreground")); // NOI18N
        lblNumeroDocumento.setText(resourceMap.getString("lblNumeroDocumento.text")); // NOI18N
        lblNumeroDocumento.setName("lblNumeroDocumento"); // NOI18N

        lblEstado.setForeground(resourceMap.getColor("lblEstado.foreground")); // NOI18N
        lblEstado.setText(resourceMap.getString("lblEstado.text")); // NOI18N
        lblEstado.setName("lblEstado"); // NOI18N

        btnEliminar.setIcon(resourceMap.getIcon("btnEliminar.icon")); // NOI18N
        btnEliminar.setText(resourceMap.getString("btnEliminar.text")); // NOI18N
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xlblLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xlblApellidoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(xlblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(lblTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(lblApellidoRazon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xlblNumeroDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(xlblCui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(xlblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(lblNumeroDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(lblCui, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(651, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xlblLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(lblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xlblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xlblApellidoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xlblCui, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xlblNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xlblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCui, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblApellidoRazon;
    private javax.swing.JLabel lblCui;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblNumeroDocumento;
    private javax.swing.JLabel lblTipoDocumento;
    private org.jdesktop.swingx.JXLabel xlblApellidoRazon;
    private org.jdesktop.swingx.JXLabel xlblCui;
    private org.jdesktop.swingx.JXLabel xlblEstado;
    private org.jdesktop.swingx.JXLabel xlblLegajo;
    private org.jdesktop.swingx.JXLabel xlblNumeroDocumento;
    private org.jdesktop.swingx.JXLabel xlblTipoDocumento;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables

    private PnlDatosSolicitanteGaranteController controlador;
    
    public JXTitledSeparator getXtsTitulo(){
    	return this.xtsTitulo;
    }
    
    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JLabel getLblApellidoRazon() {
        return lblApellidoRazon;
    }

    public void setLblApellidoRazon(JLabel lblApellidoRazon) {
        this.lblApellidoRazon = lblApellidoRazon;
    }

    public JLabel getLblCui() {
        return lblCui;
    }

    public void setLblCui(JLabel lblCui) {
        this.lblCui = lblCui;
    }

    public JLabel getLblEstado() {
        return lblEstado;
    }

    public void setLblEstado(JLabel lblEstado) {
        this.lblEstado = lblEstado;
    }

    public JLabel getLblLegajo() {
        return lblLegajo;
    }

    public void setLblLegajo(JLabel lblLegajo) {
        this.lblLegajo = lblLegajo;
    }

    public JLabel getLblNumeroDocumento() {
        return lblNumeroDocumento;
    }

    public void setLblNumeroDocumento(JLabel lblNumeroDocumento) {
        this.lblNumeroDocumento = lblNumeroDocumento;
    }

    public JLabel getLblTipoDocumento() {
        return lblTipoDocumento;
    }

    public void setLblTipoDocumento(JLabel lblTipoDocumento) {
        this.lblTipoDocumento = lblTipoDocumento;
    }

	public void setControlador(
			PnlDatosSolicitanteGaranteController pnlDatosSolicitanteGaranteController) {
		this.controlador = pnlDatosSolicitanteGaranteController;		
	}

	public PnlDatosSolicitanteGaranteController getControlador() {
		return controlador;
	}

	    
}
