/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminUsuarios.java
 *
 * Created on 25/01/2010, 11:58:49
 */

package ar.gov.cjpmv.prestamos.gui.usuarios;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.jdesktop.swingx.JXHyperlink;
import org.jdesktop.swingx.JXTitledSeparator;

import ar.gov.cjpmv.prestamos.gui.Principal;
import ar.gov.cjpmv.prestamos.gui.PrincipalView;

/**
 *
 * @author Administrador
 */
public class AdminUsuariosView extends javax.swing.JDialog {

    /** Creates new form AdminUsuarios */
    public AdminUsuariosView(PrincipalView parent, boolean modal) {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlBotoneraUsuarios1 = new ar.gov.cjpmv.prestamos.gui.usuarios.PnlBotoneraUsuarios();
        pnlDchaUsuarios1 = new ar.gov.cjpmv.prestamos.gui.usuarios.PnlDchaUsuarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jSplitPane1.setDividerSize(2);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        pnlBotoneraUsuarios1.setName("pnlBotoneraUsuarios1"); // NOI18N
        jSplitPane1.setLeftComponent(pnlBotoneraUsuarios1);

        pnlDchaUsuarios1.setName("pnlDchaUsuarios1"); // NOI18N
        jSplitPane1.setRightComponent(pnlDchaUsuarios1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminUsuariosView dialog = new AdminUsuariosView(new PrincipalView(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private ar.gov.cjpmv.prestamos.gui.usuarios.PnlBotoneraUsuarios pnlBotoneraUsuarios1;
    private ar.gov.cjpmv.prestamos.gui.usuarios.PnlDchaUsuarios pnlDchaUsuarios1;
    // End of variables declaration//GEN-END:variables
    
  
    public JXHyperlink getXhNuevoUsuario(){
    	return this.pnlBotoneraUsuarios1.getXhNuevoUsuario();
    }
    public JXHyperlink getXhEditarUsuario(){
    	return this.pnlBotoneraUsuarios1.getXhEditarUsuario();
    }
    public JXHyperlink getXhCambiarContrasenia(){
    	return this.pnlBotoneraUsuarios1.getXhCambiarContrasenia();
    }
    
    public JLabel getLblTituloPnlDcha1(){
    	return this.pnlDchaUsuarios1.getLblTituloPnlDcha1();
    }

    public JPanel getPnlBusquedaDcha1(){
    	return this.pnlDchaUsuarios1.getPnlBusquedaDcha1();
    }
    
    public JButton getBtnCancelar(){
    	return this.pnlDchaUsuarios1.getBtnCancelar();
    }
    public JButton getBtnGuardar(){
    	return this.pnlDchaUsuarios1.getBtnGuardar();
    }
    
    
    public void setPanel(JPanel pComponente){
    	this.pnlDchaUsuarios1.setPanel(pComponente);
    }
    
    public PnlBotoneraUsuarios getPnlBotoneraUsuarios(){
    	return this.pnlBotoneraUsuarios1;
    }



    

    

 
    


}
