/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlABMUsuarios.java
 *
 * Created on 25/01/2010, 21:53:57
 */

package ar.gov.cjpmv.prestamos.gui.usuarios;

import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author daiana
 */
public class PnlABMUsuarios extends javax.swing.JPanel {

    /** Creates new form PnlABMUsuarios */
    public PnlABMUsuarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xtsTituloSub1 = new org.jdesktop.swingx.JXTitledSeparator();
        pnlDatosUsuarios1 = new ar.gov.cjpmv.prestamos.gui.usuarios.PnlDatosUsuarios();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlABMUsuarios.class);
        setBackground(resourceMap.getColor("FondoBlanco")); // NOI18N
        setName("Form"); // NOI18N

        xtsTituloSub1.setForeground(resourceMap.getColor("xtsTituloSub1.foreground")); // NOI18N
        xtsTituloSub1.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsTituloSub1.setName("xtsTituloSub1"); // NOI18N
        xtsTituloSub1.setTitle(resourceMap.getString("xtsTituloSub1.title")); // NOI18N

        pnlDatosUsuarios1.setName("pnlDatosUsuarios1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTituloSub1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(pnlDatosUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTituloSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.gov.cjpmv.prestamos.gui.usuarios.PnlDatosUsuarios pnlDatosUsuarios1;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloSub1;
    // End of variables declaration//GEN-END:variables

 
    public JTextField getTxtUsuario(){
    	return this.pnlDatosUsuarios1.getTxtUsuario();
    }
    
    public JPasswordField getTxtPasContrasenia(){
    	return this.pnlDatosUsuarios1.getTxtPasContrasenia();
    }
    
    public JPasswordField getTxtPasRepetirContrasenia(){
    	return this.pnlDatosUsuarios1.getTxtPasRepetirContrasenia();
    }
    
    public JTable getTblModulosPermisos(){
    	return this.pnlDatosUsuarios1.getTblModulosPermisos();
    }
    
    
}
