/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlDchaUsuarios.java
 *
 * Created on 25/01/2010, 12:38:52
 */

package ar.gov.cjpmv.prestamos.gui.usuarios;

import java.awt.BorderLayout;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.jdesktop.swingx.JXTitledSeparator;

/**
 *
 * @author Administrador
 */
public class PnlDchaUsuarios extends javax.swing.JPanel {

    private static final JButton btnImprimir = null;
	/** Creates new form PnlDchaUsuarios */
   
    
    
    public PnlDchaUsuarios() {
    	//TE AMOUUU MUCHO TODO FIXME
      initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        lblTituloPnlDcha1 = new javax.swing.JLabel();
        pnlBusquedaDcha1 = new javax.swing.JPanel();
        pnlBusquedaUsuarios1 = new ar.gov.cjpmv.prestamos.gui.usuarios.PnlBusquedaUsuarios();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDchaUsuarios.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        lblTituloPnlDcha1.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblTituloPnlDcha1.setForeground(resourceMap.getColor("lblTituloPnlDcha1.foreground")); // NOI18N
        lblTituloPnlDcha1.setIcon(resourceMap.getIcon("lblTituloPnlDcha1.icon")); // NOI18N
        lblTituloPnlDcha1.setText(resourceMap.getString("lblTituloPnlDcha1.text")); // NOI18N
        lblTituloPnlDcha1.setName("lblTituloPnlDcha1"); // NOI18N

        pnlBusquedaDcha1.setBackground(resourceMap.getColor("pnlBusquedaDcha1.background")); // NOI18N
        pnlBusquedaDcha1.setName("pnlBusquedaDcha1"); // NOI18N
        pnlBusquedaDcha1.setPreferredSize(new java.awt.Dimension(600, 449));
        pnlBusquedaDcha1.setLayout(new java.awt.BorderLayout());

        pnlBusquedaUsuarios1.setName("pnlBusquedaUsuarios1"); // NOI18N
        pnlBusquedaDcha1.add(pnlBusquedaUsuarios1, java.awt.BorderLayout.CENTER);

        btnGuardar.setIcon(resourceMap.getIcon("btnGuardar.icon")); // NOI18N
        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setMaximumSize(new java.awt.Dimension(121, 23));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPreferredSize(new java.awt.Dimension(101, 23));

        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBusquedaDcha1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addComponent(lblTituloPnlDcha1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBusquedaDcha1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblTituloPnlDcha1;
    private javax.swing.JPanel pnlBusquedaDcha1;
    private ar.gov.cjpmv.prestamos.gui.usuarios.PnlBusquedaUsuarios pnlBusquedaUsuarios1;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getLblTituloPnlDcha1(){
    	return this.lblTituloPnlDcha1;
    }

    public JPanel getPnlBusquedaDcha1(){
    	return this.pnlBusquedaDcha1;
    }
    
    public JButton getBtnCancelar(){
    	return this.btnCancelar;
    }
    public JButton getBtnGuardar(){
    	return this.btnGuardar;
    }
    
    
    
    public void setPanel(JPanel pPanel){    	
    	this.getPnlBusquedaDcha1().removeAll();
    	this.getPnlBusquedaDcha1().add(pPanel,BorderLayout.CENTER);
    	this.getPnlBusquedaDcha1().validate();
    	this.getPnlBusquedaDcha1().repaint();
    }
        

}
