/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlDatosUsuarios.java
 *
 * Created on 25/01/2010, 15:08:47
 */

package ar.gov.cjpmv.prestamos.gui.usuarios;

import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author daiana
 */
public class PnlDatosUsuarios extends javax.swing.JPanel {

    /** Creates new form PnlDatosUsuarios */
    public PnlDatosUsuarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        txtPasRepetirContrasenia = new javax.swing.JPasswordField();
        txtPasRepetirContrasenia1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModulosPermisos = new javax.swing.JTable();
        lblModulosPermisos = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDatosUsuarios.class);
        setBackground(resourceMap.getColor("ColorGris")); // NOI18N
        setName("Form"); // NOI18N

        lblUsuario.setFont(resourceMap.getFont("lblUsuario.font")); // NOI18N
        lblUsuario.setForeground(resourceMap.getColor("lblUsuario.foreground")); // NOI18N
        lblUsuario.setText(resourceMap.getString("lblUsuario.text")); // NOI18N
        lblUsuario.setName("lblUsuario"); // NOI18N

        txtUsuario.setForeground(resourceMap.getColor("txtUsuario.foreground")); // NOI18N
        txtUsuario.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtUsuario.border.lineColor"), 1, true)); // NOI18N
        txtUsuario.setName("txtUsuario"); // NOI18N

        lblNombre1.setForeground(resourceMap.getColor("lblNombre1.foreground")); // NOI18N
        lblNombre1.setText(resourceMap.getString("lblNombre1.text")); // NOI18N
        lblNombre1.setName("lblNombre1"); // NOI18N

        lblNombre2.setForeground(resourceMap.getColor("lblNombre2.foreground")); // NOI18N
        lblNombre2.setText(resourceMap.getString("lblNombre2.text")); // NOI18N
        lblNombre2.setName("lblNombre2"); // NOI18N

        txtPasRepetirContrasenia.setFont(resourceMap.getFont("Campo")); // NOI18N
        txtPasRepetirContrasenia.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        txtPasRepetirContrasenia.setText(resourceMap.getString("txtPasRepetirContrasenia.text")); // NOI18N
        txtPasRepetirContrasenia.setName("txtPasRepetirContrasenia"); // NOI18N

        txtPasRepetirContrasenia1.setForeground(resourceMap.getColor("txtPasRepetirContrasenia1.foreground")); // NOI18N
        txtPasRepetirContrasenia1.setText(resourceMap.getString("txtPasRepetirContrasenia1.text")); // NOI18N
        txtPasRepetirContrasenia1.setName("txtPasRepetirContrasenia1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbModulosPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbModulosPermisos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbModulosPermisos.setName("tbModulosPermisos"); // NOI18N
        jScrollPane1.setViewportView(tbModulosPermisos);

        lblModulosPermisos.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        lblModulosPermisos.setForeground(resourceMap.getColor("lblModulosPermisos.foreground")); // NOI18N
        lblModulosPermisos.setText(resourceMap.getString("lblModulosPermisos.text")); // NOI18N
        lblModulosPermisos.setName("lblModulosPermisos"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblModulosPermisos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblNombre1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblUsuario)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtPasRepetirContrasenia1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(lblNombre2)
                        .addGap(14, 14, 14)
                        .addComponent(txtPasRepetirContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(lblNombre2)
                            .addComponent(txtPasRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtPasRepetirContrasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(lblModulosPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModulosPermisos;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tbModulosPermisos;
    private javax.swing.JPasswordField txtPasRepetirContrasenia;
    private javax.swing.JPasswordField txtPasRepetirContrasenia1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    
    public JTextField getTxtUsuario(){
    	return this.txtUsuario;
    }
    
    public JPasswordField getTxtPasContrasenia(){
    	return this.txtPasRepetirContrasenia;
    }
    
    public JPasswordField getTxtPasRepetirContrasenia(){
    	return this.txtPasRepetirContrasenia1;
    }
    
    public JTable getTblModulosPermisos(){
    	return this.tbModulosPermisos;
    }
    
    
    
}
