/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlFormulariosCredito.java
 *
 * Created on 20/01/2011, 21:35:25
 */

package ar.gov.cjpmv.prestamos.gui.creditos.reportes;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author dernst
 */
public class PnlFormulariosCredito extends javax.swing.JPanel {

    /** Creates new form PnlFormulariosCredito */
    public PnlFormulariosCredito() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xtsTituloParametroBusqueda = new org.jdesktop.swingx.JXTitledSeparator();
        jPanel2 = new javax.swing.JPanel();
        lblTituloSeleccionFecha2 = new javax.swing.JLabel();
        cbxFormulario = new javax.swing.JCheckBox();
        cbxRecibo = new javax.swing.JCheckBox();
        cbxOtorgamiento = new javax.swing.JCheckBox();
        btnImprimir = new javax.swing.JButton();
        cbxFormulario2 = new javax.swing.JCheckBox();
        cbxConcepto = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        lblTituloSeleccionFecha1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblDescripcion4 = new javax.swing.JLabel();
        lblDescripcion5 = new javax.swing.JLabel();
        txtNroCredito = new javax.swing.JTextField();
        txtLegajo = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlFormulariosCredito.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        xtsTituloParametroBusqueda.setForeground(resourceMap.getColor("xtsTituloParametroBusqueda.foreground")); // NOI18N
        xtsTituloParametroBusqueda.setFont(resourceMap.getFont("xtsTituloParametroBusqueda.font")); // NOI18N
        xtsTituloParametroBusqueda.setName("xtsTituloParametroBusqueda"); // NOI18N
        xtsTituloParametroBusqueda.setTitle(resourceMap.getString("xtsTituloParametroBusqueda.title")); // NOI18N

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        lblTituloSeleccionFecha2.setFont(resourceMap.getFont("lblTituloSeleccionFecha2.font")); // NOI18N
        lblTituloSeleccionFecha2.setForeground(resourceMap.getColor("lblTituloSeleccionFecha2.foreground")); // NOI18N
        lblTituloSeleccionFecha2.setText(resourceMap.getString("lblTituloSeleccionFecha2.text")); // NOI18N
        lblTituloSeleccionFecha2.setName("lblTituloSeleccionFecha2"); // NOI18N

        cbxFormulario.setBackground(resourceMap.getColor("cbxFormulario.background")); // NOI18N
        cbxFormulario.setForeground(resourceMap.getColor("cbxFormulario.foreground")); // NOI18N
        cbxFormulario.setText(resourceMap.getString("cbxFormulario.text")); // NOI18N
        cbxFormulario.setName("cbxFormulario"); // NOI18N

        cbxRecibo.setBackground(resourceMap.getColor("cbxRecibo.background")); // NOI18N
        cbxRecibo.setForeground(resourceMap.getColor("cbxRecibo.foreground")); // NOI18N
        cbxRecibo.setText(resourceMap.getString("cbxRecibo.text")); // NOI18N
        cbxRecibo.setName("cbxRecibo"); // NOI18N

        cbxOtorgamiento.setBackground(resourceMap.getColor("cbxOtorgamiento.background")); // NOI18N
        cbxOtorgamiento.setForeground(resourceMap.getColor("cbxOtorgamiento.foreground")); // NOI18N
        cbxOtorgamiento.setText(resourceMap.getString("cbxOtorgamiento.text")); // NOI18N
        cbxOtorgamiento.setName("cbxOtorgamiento"); // NOI18N

        btnImprimir.setFont(resourceMap.getFont("btnImprimir.font")); // NOI18N
        btnImprimir.setForeground(resourceMap.getColor("btnImprimir.foreground")); // NOI18N
        btnImprimir.setIcon(resourceMap.getIcon("btnImprimir.icon")); // NOI18N
        btnImprimir.setText(resourceMap.getString("btnImprimir.text")); // NOI18N
        btnImprimir.setName("btnImprimir"); // NOI18N

        cbxFormulario2.setBackground(resourceMap.getColor("cbxFormulario2.background")); // NOI18N
        cbxFormulario2.setForeground(resourceMap.getColor("cbxFormulario2.foreground")); // NOI18N
        cbxFormulario2.setText(resourceMap.getString("cbxFormulario2.text")); // NOI18N
        cbxFormulario2.setName("cbxFormulario2"); // NOI18N

        cbxConcepto.setBackground(resourceMap.getColor("cbxConcepto.background")); // NOI18N
        cbxConcepto.setForeground(resourceMap.getColor("cbxConcepto.foreground")); // NOI18N
        cbxConcepto.setText(resourceMap.getString("cbxConcepto.text")); // NOI18N
        cbxConcepto.setName("cbxConcepto"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbxFormulario)
                        .addGap(18, 18, 18)
                        .addComponent(cbxFormulario2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxRecibo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxOtorgamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloSeleccionFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblTituloSeleccionFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFormulario)
                    .addComponent(cbxFormulario2)
                    .addComponent(cbxRecibo)
                    .addComponent(cbxOtorgamiento)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxConcepto))
                .addGap(67, 67, 67))
        );

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        lblTituloSeleccionFecha1.setFont(resourceMap.getFont("lblTituloSeleccionFecha1.font")); // NOI18N
        lblTituloSeleccionFecha1.setForeground(resourceMap.getColor("lblTituloSeleccionFecha1.foreground")); // NOI18N
        lblTituloSeleccionFecha1.setText(resourceMap.getString("lblTituloSeleccionFecha1.text")); // NOI18N
        lblTituloSeleccionFecha1.setName("lblTituloSeleccionFecha1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblResultado.setForeground(resourceMap.getColor("tblResultado.foreground")); // NOI18N
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblResultado.setName("tblResultado"); // NOI18N
        jScrollPane1.setViewportView(tblResultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addComponent(lblTituloSeleccionFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloSeleccionFecha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        lblDescripcion4.setForeground(resourceMap.getColor("lblDescripcion4.foreground")); // NOI18N
        lblDescripcion4.setText(resourceMap.getString("lblDescripcion4.text")); // NOI18N
        lblDescripcion4.setName("lblDescripcion4"); // NOI18N

        lblDescripcion5.setForeground(resourceMap.getColor("lblDescripcion5.foreground")); // NOI18N
        lblDescripcion5.setText(resourceMap.getString("lblDescripcion5.text")); // NOI18N
        lblDescripcion5.setName("lblDescripcion5"); // NOI18N

        txtNroCredito.setName("txtNroCredito"); // NOI18N

        txtLegajo.setName("txtLegajo"); // NOI18N

        btnBusqueda.setIcon(resourceMap.getIcon("btnBusqueda.icon")); // NOI18N
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBusqueda.setName("btnBusqueda"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion4)
                            .addComponent(txtNroCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion5)
                            .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JCheckBox cbxConcepto;
    private javax.swing.JCheckBox cbxFormulario;
    private javax.swing.JCheckBox cbxFormulario2;
    private javax.swing.JCheckBox cbxOtorgamiento;
    private javax.swing.JCheckBox cbxRecibo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion4;
    private javax.swing.JLabel lblDescripcion5;
    private javax.swing.JLabel lblTituloSeleccionFecha1;
    private javax.swing.JLabel lblTituloSeleccionFecha2;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNroCredito;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloParametroBusqueda;
    // End of variables declaration//GEN-END:variables
    
    public JTable getTblResultado(){
    	return this.tblResultado;
    }
    
    public JButton getBtBusqueda(){
    	return this.btnBusqueda;
    }
    
    public JButton getBtnImprimir(){
    	return this.btnImprimir;
    }
    
    public JCheckBox getCbxFormulario1(){
    	return this.cbxFormulario;
    }
    
    public JCheckBox getCbxFormulario2(){
    	return this.cbxFormulario2;
    }
    
    public JCheckBox getCbxRecibo(){
    	return this.cbxRecibo;
    }
    
    public JCheckBox getCbxOtorgamiento(){
    	return this.cbxOtorgamiento;
    }
    
    public JCheckBox getCbxConcepto(){
    	return this.cbxConcepto;
    }
        
    public JTextField getTxtLegajo(){
    	return this.txtLegajo;
    }
    
    public JTextField getTxtNroCredito(){
    	return this.txtNroCredito;
    }
    
    
    
    

}
