/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlPreferenciasAdministracion.java
 *
 * Created on 26/12/2009, 22:09:36
 */

package ar.gov.cjpmv.prestamos.gui;

import javax.swing.JLabel;

/**
 *
 * @author pulpol
 */
public class PnlPreferenciasAdministracion extends javax.swing.JPanel {

    /** Creates new form PnlPreferenciasAdministracion */
    public PnlPreferenciasAdministracion() {
        initComponents();
        //FIXME ELIMINAR
        this.ocultarPorEntrega();
    }

    private void ocultarPorEntrega() {
		this.lblAyuda.setEnabled(false);
		this.lblAyuda.setVisible(false);
		this.lblIconoAyuda.setEnabled(false);
		this.lblIconoAyuda.setVisible(false);
		this.lblIconoResguardo.setEnabled(false);
		this.lblIconoResguardo.setVisible(false);
		this.lblResguardo.setEnabled(false);
		this.lblResguardo.setVisible(false);
		this.lblIconoResguardo.setVisible(false);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new java.awt.Label();
        lblConfiguracion = new javax.swing.JLabel();
        lblIconoConfiguracion = new javax.swing.JLabel();
        lblIconoResguardo = new javax.swing.JLabel();
        lblResguardo = new javax.swing.JLabel();
        lblIconoAyuda = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        lblIconoUsuarios = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlPreferenciasAdministracion.class);
        setBackground(resourceMap.getColor("FondoCeleste")); // NOI18N
        setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(629, 179));
        setRequestFocusEnabled(false);

        lblTitulo.setBackground(resourceMap.getColor("FondoAzulOscuro")); // NOI18N
        lblTitulo.setFont(resourceMap.getFont("tituloBarrita")); // NOI18N
        lblTitulo.setForeground(resourceMap.getColor("lblTitulo.foreground")); // NOI18N
        lblTitulo.setName("lblTitulo"); // NOI18N
        lblTitulo.setText(resourceMap.getString("lblTitulo.text")); // NOI18N

        lblConfiguracion.setFont(resourceMap.getFont("tituloBarrita")); // NOI18N
        lblConfiguracion.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        lblConfiguracion.setText(resourceMap.getString("lblConfiguracion.text")); // NOI18N
        lblConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfiguracion.setName("lblConfiguracion"); // NOI18N

        lblIconoConfiguracion.setFont(resourceMap.getFont("lblIconoConfiguracion.font")); // NOI18N
        lblIconoConfiguracion.setForeground(resourceMap.getColor("lblIconoConfiguracion.foreground")); // NOI18N
        lblIconoConfiguracion.setIcon(resourceMap.getIcon("lblIconoConfiguracion.icon")); // NOI18N
        lblIconoConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoConfiguracion.setName("lblIconoConfiguracion"); // NOI18N

        lblIconoResguardo.setFont(resourceMap.getFont("lblIconoResguardo.font")); // NOI18N
        lblIconoResguardo.setForeground(resourceMap.getColor("lblIconoResguardo.foreground")); // NOI18N
        lblIconoResguardo.setIcon(resourceMap.getIcon("lblIconoResguardo.icon")); // NOI18N
        lblIconoResguardo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoResguardo.setName("lblIconoResguardo"); // NOI18N

        lblResguardo.setFont(resourceMap.getFont("tituloBarrita")); // NOI18N
        lblResguardo.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        lblResguardo.setText(resourceMap.getString("lblResguardo.text")); // NOI18N
        lblResguardo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblResguardo.setName("lblResguardo"); // NOI18N

        lblIconoAyuda.setIcon(resourceMap.getIcon("lblIconoAyuda.icon")); // NOI18N
        lblIconoAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoAyuda.setName("lblIconoAyuda"); // NOI18N

        lblAyuda.setFont(resourceMap.getFont("tituloBarrita")); // NOI18N
        lblAyuda.setForeground(resourceMap.getColor("ColorTituloBarrita")); // NOI18N
        lblAyuda.setText(resourceMap.getString("lblAyuda.text")); // NOI18N
        lblAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAyuda.setName("lblAyuda"); // NOI18N

        lblIconoUsuarios.setIcon(resourceMap.getIcon("lblIconoUsuarios.icon")); // NOI18N
        lblIconoUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoUsuarios.setName("lblIconoUsuarios"); // NOI18N

        lblUsuarios.setFont(resourceMap.getFont("lblUsuarios.font")); // NOI18N
        lblUsuarios.setForeground(resourceMap.getColor("lblUsuarios.foreground")); // NOI18N
        lblUsuarios.setText(resourceMap.getString("lblUsuarios.text")); // NOI18N
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.setName("lblUsuarios"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblIconoConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoUsuarios, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblUsuarios))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoResguardo)
                    .addComponent(lblResguardo))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoAyuda)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoConfiguracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoAyuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAyuda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoResguardo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResguardo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuarios)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblIconoAyuda;
    private javax.swing.JLabel lblIconoConfiguracion;
    private javax.swing.JLabel lblIconoResguardo;
    private javax.swing.JLabel lblIconoUsuarios;
    private javax.swing.JLabel lblResguardo;
    private java.awt.Label lblTitulo;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables
    
    
    public JLabel getLblConfiguracion(){
    	return this.lblConfiguracion;
    }
    
    public javax.swing.JLabel getLblIconoConfiguracion() {
		return lblIconoConfiguracion;
	}

	public javax.swing.JLabel getLblAyuda() {
		return lblAyuda;
	}

	public javax.swing.JLabel getLblIconoAyuda() {
		return lblIconoAyuda;
	}

	public javax.swing.JLabel getLblIconoResguardo() {
		return lblIconoResguardo;
	}

	public javax.swing.JLabel getLblResguardo() {
		return lblResguardo;
	}

	public java.awt.Label getLblTitulo() {
		return lblTitulo;
	}

	public javax.swing.JLabel getLblIconoUsuarios() {
		return lblIconoUsuarios;
	}

	public javax.swing.JLabel getLblUsuarios() {
		return lblUsuarios;
	}

    
}
