/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMConfiguracion.java
 *
 * Created on 05/01/2010, 17:40:16
 */

package ar.gov.cjpmv.prestamos.gui.configuracion;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author daiana
 */
public class ABMConfiguracion extends javax.swing.JDialog {

    /** Creates new form ABMConfiguracion */
    public ABMConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ABMConfiguracion(JDialog pPadre, boolean modal) {
		super(pPadre, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlABMConfiguracion = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlDescripcionTipo1 = new ar.gov.cjpmv.prestamos.gui.configuracion.PnlDescripcionTipo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(ABMConfiguracion.class);
        pnlABMConfiguracion.setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        pnlABMConfiguracion.setName("pnlABMConfiguracion"); // NOI18N

        btnGuardar.setFont(resourceMap.getFont("Campo")); // NOI18N
        btnGuardar.setForeground(resourceMap.getColor("btnGuardar.foreground")); // NOI18N
        btnGuardar.setIcon(resourceMap.getIcon("btnGuardar.icon")); // NOI18N
        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setMaximumSize(new java.awt.Dimension(121, 23));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPreferredSize(new java.awt.Dimension(101, 23));

        btnCancelar.setFont(resourceMap.getFont("Campo")); // NOI18N
        btnCancelar.setForeground(resourceMap.getColor("btnCancelar.foreground")); // NOI18N
        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlDescripcionTipo1.setName("pnlDescripcionTipo1"); // NOI18N

        javax.swing.GroupLayout pnlABMConfiguracionLayout = new javax.swing.GroupLayout(pnlABMConfiguracion);
        pnlABMConfiguracion.setLayout(pnlABMConfiguracionLayout);
        pnlABMConfiguracionLayout.setHorizontalGroup(
            pnlABMConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlABMConfiguracionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlDescripcionTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlABMConfiguracionLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(53, 53, 53))
        );
        pnlABMConfiguracionLayout.setVerticalGroup(
            pnlABMConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlABMConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDescripcionTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlABMConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlABMConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlABMConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMConfiguracion dialog = new ABMConfiguracion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel pnlABMConfiguracion;
    private ar.gov.cjpmv.prestamos.gui.configuracion.PnlDescripcionTipo pnlDescripcionTipo1;
    // End of variables declaration//GEN-END:variables
    
    
	public JButton getBtnGuardar() {
		return this.btnGuardar;
	}
	
	public JButton getBtnCancelar(){
		return this.btnCancelar;
	}
	
	public JTextField getTxtDescripcion(){
		return this.pnlDescripcionTipo1.getTxtDescripcion();
	}
	public void setLblDescripcion(String pLabel){
		this.pnlDescripcionTipo1.setLblDescripcion(pLabel);
	}
	


}
