/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlTipoDocumento.java
 *
 * Created on 05/01/2010, 17:42:54
 */

package ar.gov.cjpmv.prestamos.gui.configuracion;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author daiana
 */
public class PnlDescripcionTipo extends javax.swing.JPanel {

    /** Creates new form PnlTipoDocumento */
    public PnlDescripcionTipo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDescripcionTipo.class);
        setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        setName("Form"); // NOI18N

        lblDescripcion.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblDescripcion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblDescripcion.setText(resourceMap.getString("lblDescripcion.text")); // NOI18N
        lblDescripcion.setName("lblDescripcion"); // NOI18N

        txtDescripcion.setFont(resourceMap.getFont("Campo")); // NOI18N
        txtDescripcion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtDescripcion.border.lineColor"), 1, true)); // NOI18N
        txtDescripcion.setName("txtDescripcion"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

    
	public JTextField getTxtDescripcion() {
		return this.txtDescripcion;
	}

	
	public void setLblDescripcion(String pLabel){
		this.lblDescripcion.setText(pLabel);
	}


}
