/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlLocalidad.java
 *
 * Created on 05/01/2010, 17:59:37
 */

package ar.gov.cjpmv.prestamos.gui.configuracion;

import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author daiana
 */
public class PnlLocalidad extends javax.swing.JPanel {

    /** Creates new form PnlLocalidad */
    public PnlLocalidad() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProvincia = new javax.swing.JLabel();
        cbxProvincia = new javax.swing.JComboBox();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbxDepartamento = new javax.swing.JComboBox();
        lblDepartamento = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlLocalidad.class);
        setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        setName("Form"); // NOI18N

        lblProvincia.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblProvincia.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblProvincia.setText(resourceMap.getString("lblProvincia.text")); // NOI18N
        lblProvincia.setName("lblProvincia"); // NOI18N

        cbxProvincia.setFont(resourceMap.getFont("Campo")); // NOI18N
        cbxProvincia.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
      //  cbxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entre Ríos", "Santa Fe", "Buenos Aires" }));
        cbxProvincia.setName("cbxProvincia"); // NOI18N

        lblNombre.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblNombre.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblNombre.setText(resourceMap.getString("lblNombre.text")); // NOI18N
        lblNombre.setName("lblNombre"); // NOI18N

        txtNombre.setFont(resourceMap.getFont("Campo")); // NOI18N
        txtNombre.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtNombre.border.lineColor"), 1, true)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N

        cbxDepartamento.setFont(resourceMap.getFont("Campo")); // NOI18N
        cbxDepartamento.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
       // cbxDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Victoria", "Diamante", "Paraná" }));
        cbxDepartamento.setName("cbxDepartamento"); // NOI18N

        lblDepartamento.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblDepartamento.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblDepartamento.setText(resourceMap.getString("lblDepartamento.text")); // NOI18N
        lblDepartamento.setName("lblDepartamento"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartamento)
                    .addComponent(lblProvincia)
                    .addComponent(lblNombre))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxProvincia, 0, 220, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(cbxDepartamento, 0, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia)
                    .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxDepartamento;
    private javax.swing.JComboBox cbxProvincia;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
	public JTextField getTxtNombre() {
		return this.txtNombre;
	}
	
	public JComboBox getCbxProvincia() {
		return this.cbxProvincia;
	}
	
	public JComboBox getCbxDepartamento(){
		return this.cbxDepartamento;
	}
}
