/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlProvincia.java
 *
 * Created on 05/01/2010, 20:46:46
 */

package ar.gov.cjpmv.prestamos.gui.configuracion;

/**
 *
 * @author daiana
 */
public class PnlProvincia extends javax.swing.JPanel {

    /** Creates new form PnlProvincia */
    public PnlProvincia() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlProvincia.class);
        setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        setName("Form"); // NOI18N

        lblNombre.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblNombre.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblNombre.setText(resourceMap.getString("lblNombre.text")); // NOI18N
        lblNombre.setName("lblNombre"); // NOI18N

        txtNombre.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        txtNombre.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtNombre.border.lineColor"), 1, true)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblNombre)
                .addGap(14, 14, 14)
                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
