/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPersonaView.java
 *
 * Created on 22/12/2009, 13:51:49
 */

package ar.gov.cjpmv.prestamos.gui.personas;

import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
   
/**
 *
 * @author mal
 */
public class AdminPersonaView extends javax.swing.JDialog {

    /** Creates new form AdminPersonaView */
    public AdminPersonaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlBotoneraPersonaView1 = new ar.gov.cjpmv.prestamos.gui.personas.PnlBotoneraPersonaView();
        pnlDchaABMView1 = new ar.gov.cjpmv.prestamos.gui.comunes.PnlDchaABMView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(AdminPersonaView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("Form"); // NOI18N

        jSplitPane1.setDividerSize(2);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        pnlBotoneraPersonaView1.setMinimumSize(new java.awt.Dimension(228, 347));
        pnlBotoneraPersonaView1.setName("pnlBotoneraPersonaView1"); // NOI18N
        jSplitPane1.setLeftComponent(pnlBotoneraPersonaView1);

        pnlDchaABMView1.setName("pnlDchaABMView1"); // NOI18N
        JScrollPane scPane = new JScrollPane(pnlDchaABMView1);
        jSplitPane1.setRightComponent(scPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminPersonaView dialog = new AdminPersonaView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private ar.gov.cjpmv.prestamos.gui.personas.PnlBotoneraPersonaView pnlBotoneraPersonaView1;
    private JPanel pnlDchaABMView1;
    // End of variables declaration//GEN-END:variables

    public JPanel getPnlDchaABMView1() {
		return pnlDchaABMView1;
	}
    

 
    
    public void setPnlDchaABMView1(JPanel pnlDchaABMView1) {
		this.pnlDchaABMView1 = pnlDchaABMView1;
		this.jSplitPane1.remove(this.jSplitPane1.getRightComponent());
		this.jSplitPane1.setRightComponent(this.pnlDchaABMView1);
	}
    
    public PnlBotoneraPersonaView getPnlBotoneraPersonaView1() {
		return pnlBotoneraPersonaView1;
	}

}
