/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusquedaPersonaJuridicaDialog.java
 *
 * Created on 18/01/2010, 21:34:38
 */

package ar.gov.cjpmv.prestamos.gui.personas;

import javax.swing.JDialog;

/**
 *
 * @author pulpol
 */
public class BusquedaPersonaJuridicaDialog extends javax.swing.JDialog {

    /** Creates new form BusquedaPersonaJuridicaDialog */
    public BusquedaPersonaJuridicaDialog(JDialog parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParametrosBusquedaPersonaJuridica = new ar.gov.cjpmv.prestamos.gui.personas.PnlParametrosBusquedaPersonaJuridica();
        pnlResultadoBusqueda = new ar.gov.cjpmv.prestamos.gui.comunes.PnlResultadoBusqueda();
        xtsTituloParametroBusqueda = new org.jdesktop.swingx.JXTitledSeparator();
        btnCancelar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(BusquedaPersonaJuridicaDialog.class);
        setName("Form"); // NOI18N
        
        
        this.getContentPane().setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        
        
        pnlParametrosBusquedaPersonaJuridica.setName("pnlParametrosBusquedaPersonaJuridica"); // NOI18N

        pnlResultadoBusqueda.setName("pnlResultadoBusqueda"); // NOI18N

        xtsTituloParametroBusqueda.setForeground(resourceMap.getColor("xtsTituloParametroBusqueda.foreground")); // NOI18N
        xtsTituloParametroBusqueda.setFont(resourceMap.getFont("xtsTituloParametroBusqueda.font")); // NOI18N
        xtsTituloParametroBusqueda.setName("xtsTituloParametroBusqueda"); // NOI18N
        xtsTituloParametroBusqueda.setTitle(resourceMap.getString("xtsTituloParametroBusqueda.title")); // NOI18N

        btnCancelar.setFont(resourceMap.getFont("btnCancelar.font")); // NOI18N
        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon"));
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnSeleccionar.setFont(resourceMap.getFont("btnGuardar.font")); // NOI18N
        btnSeleccionar.setIcon(resourceMap.getIcon("btnSeleccionar.icon"));
        btnSeleccionar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnSeleccionar.setMaximumSize(new java.awt.Dimension(121, 23));
        btnSeleccionar.setName("btnGuardar"); // NOI18N
        btnSeleccionar.setPreferredSize(new java.awt.Dimension(101, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlResultadoBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addComponent(pnlParametrosBusquedaPersonaJuridica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTituloParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlParametrosBusquedaPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlResultadoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BusquedaPersonaJuridicaDialog dialog = new BusquedaPersonaJuridicaDialog(new JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private ar.gov.cjpmv.prestamos.gui.personas.PnlParametrosBusquedaPersonaJuridica pnlParametrosBusquedaPersonaJuridica;
    private ar.gov.cjpmv.prestamos.gui.comunes.PnlResultadoBusqueda pnlResultadoBusqueda;
    private org.jdesktop.swingx.JXTitledSeparator xtsTituloParametroBusqueda;
   
    
    // End of variables declaration//GEN-END:variables
	public ar.gov.cjpmv.prestamos.gui.personas.PnlParametrosBusquedaPersonaJuridica getPnlParametrosBusquedaPersonaJuridica() {
		return pnlParametrosBusquedaPersonaJuridica;
	}

	public ar.gov.cjpmv.prestamos.gui.comunes.PnlResultadoBusqueda getPnlResultadoBusqueda() {
		return pnlResultadoBusqueda;
	}

    public javax.swing.JButton getBtnSeleccionar() {
		return btnSeleccionar;
	}
    
    public javax.swing.JButton getBtnCancelar() {
		return btnCancelar;
	}
    
}
