/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlEmpleo.java
 *
 * Created on 03/01/2010, 17:09:51
 */

package ar.gov.cjpmv.prestamos.gui.personas;

import java.text.NumberFormat;

import javax.swing.JDialog;


/**
 *
 * @author daiana
 */
public class EmpleoDialog extends JDialog{

    /** Creates new form PnlEmpleo */
    public EmpleoDialog(JDialog parent, boolean modal) {
    	super(parent,  modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCategoria = new javax.swing.JComboBox();
        dtcFechaFin = new com.toedter.calendar.JDateChooser();
        dtcFechaInicio = new com.toedter.calendar.JDateChooser();
        cbxSituacion = new javax.swing.JComboBox();
        txtFuncion = new javax.swing.JTextField();
        lblOrganismo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblSituacion = new javax.swing.JLabel();
        lblFuncion = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtPersonaJuridica = new javax.swing.JTextField();
        btnBuscarPersonaJuridica = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(EmpleoDialog.class);
        this.getContentPane().setBackground(resourceMap.getColor("FondoBlanco")); // NOI18N
        setName("Form"); // NOI18N

        cbxCategoria.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        cbxCategoria.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        cbxCategoria.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtCategoria.border.lineColor"), 1, true)); // NOI18N
        cbxCategoria.setName("txtCategoria"); // NOI18N

        dtcFechaFin.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        dtcFechaFin.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        dtcFechaFin.setName("dtcFechaFin"); // NOI18N

        dtcFechaInicio.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        dtcFechaInicio.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        dtcFechaInicio.setName("dtcFechaInicio"); // NOI18N

        cbxSituacion.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        cbxSituacion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        cbxSituacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Planta Permanente", "Contrato de Servicio", "Contrato de Obra", "Temporario", "Otro" }));
        cbxSituacion.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("cbxSituacion.border.lineColor"), 1, true)); // NOI18N
        cbxSituacion.setName("cbxSituacion"); // NOI18N

        txtFuncion.setFont(resourceMap.getFont("ContenidoTextoCampo")); // NOI18N
        txtFuncion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        txtFuncion.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtFuncion.border.lineColor"), 1, true)); // NOI18N
        txtFuncion.setName("txtFuncion"); // NOI18N

        lblOrganismo.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblOrganismo.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblOrganismo.setText(resourceMap.getString("lblOrganismo.text")); // NOI18N
        lblOrganismo.setName("lblOrganismo"); // NOI18N

        lblFechaInicio.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblFechaInicio.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblFechaInicio.setText(resourceMap.getString("lblFechaInicio.text")); // NOI18N
        lblFechaInicio.setName("lblFechaInicio"); // NOI18N

        lblSituacion.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblSituacion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblSituacion.setText(resourceMap.getString("lblSituacion.text")); // NOI18N
        lblSituacion.setName("lblSituacion"); // NOI18N

        lblFuncion.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblFuncion.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblFuncion.setText(resourceMap.getString("lblFuncion.text")); // NOI18N
        lblFuncion.setName("lblFuncion"); // NOI18N

        lblFechaFin.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblFechaFin.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblFechaFin.setText(resourceMap.getString("lblFechaFin.text")); // NOI18N
        lblFechaFin.setName("lblFechaFin"); // NOI18N

        lblCategoria.setFont(resourceMap.getFont("Campo")); // NOI18N
        lblCategoria.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblCategoria.setText(resourceMap.getString("lblCategoria.text")); // NOI18N
        lblCategoria.setName("lblCategoria"); // NOI18N

        txtPersonaJuridica.setFont(resourceMap.getFont("txtPersonaJuridica.font")); // NOI18N
        txtPersonaJuridica.setForeground(resourceMap.getColor("txtPersonaJuridica.foreground")); // NOI18N
        txtPersonaJuridica.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("txtPersonaJuridica.border.lineColor"), 1, true)); // NOI18N
        txtPersonaJuridica.setName("txtPersonaJuridica"); // NOI18N

        btnBuscarPersonaJuridica.setIcon(resourceMap.getIcon("btnBuscarPersonaJuridica.icon")); // NOI18N
        btnBuscarPersonaJuridica.setName("btnBuscarPersonaJuridica"); // NOI18N

        btnGuardar.setIcon(resourceMap.getIcon("btnGuardar.icon")); // NOI18N
        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setMaximumSize(new java.awt.Dimension(121, 23));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPreferredSize(new java.awt.Dimension(101, 23));

        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrganismo)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblSituacion))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPersonaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dtcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(cbxSituacion, 0, 158, Short.MAX_VALUE)))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaFin)
                            .addComponent(lblCategoria)
                            .addComponent(lblFuncion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(dtcFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(cbxCategoria, 0, 192, Short.MAX_VALUE)))
                    .addComponent(btnCancelar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrganismo)
                            .addComponent(txtPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFuncion)
                                .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaInicio)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaFin))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacion)
                    .addComponent(lblCategoria)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPersonaJuridica;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JComboBox cbxSituacion;
    private com.toedter.calendar.JDateChooser dtcFechaFin;
    private com.toedter.calendar.JDateChooser dtcFechaInicio;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblOrganismo;
    private javax.swing.JLabel lblSituacion;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtPersonaJuridica;
    // End of variables declaration//GEN-END:variables
    
	public javax.swing.JButton getBtnBuscarPersonaJuridica() {
		return btnBuscarPersonaJuridica;
	}

	public javax.swing.JComboBox getCbxSituacion() {
		return cbxSituacion;
	}

	public com.toedter.calendar.JDateChooser getDtcFechaFin() {
		return dtcFechaFin;
	}

	public com.toedter.calendar.JDateChooser getDtcFechaInicio() {
		return dtcFechaInicio;
	}

	public javax.swing.JComboBox getCbxCategoria() {
		return cbxCategoria;
	}
	
	public javax.swing.JTextField getTxtFuncion() {
		return txtFuncion;
	}

	public javax.swing.JTextField getTxtPersonaJuridica() {
		return txtPersonaJuridica;
	}

	public javax.swing.JButton getBtnCancelar() {
		return btnCancelar;
	}

	public javax.swing.JButton getBtnGuardar() {
		return btnGuardar;
	}

    
    
}
