/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlDatosFamiliaresView.java
 *
 * Created on 02/01/2010, 22:53:12
 */

package ar.gov.cjpmv.prestamos.gui.personas;

/**
 *
 * @author daiana
 */
public class PnlDatosFamiliaresView extends javax.swing.JPanel {

    /** Creates new form PnlDatosFamiliaresView */
    public PnlDatosFamiliaresView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        pnlCuadroDatosFamiliaresEmpleos = new javax.swing.JPanel();
        sllpFamiliaresEmpleos = new javax.swing.JScrollPane();
        tblFamiliaresEmpleos = new javax.swing.JTable();
        lblTituloCuadro = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlDatosFamiliaresView.class);
        setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        setName("Form"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("TituloBarrita")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        pnlCuadroDatosFamiliaresEmpleos.setBackground(resourceMap.getColor("ColorGris")); // NOI18N
        pnlCuadroDatosFamiliaresEmpleos.setName("pnlCuadroDatosFamiliaresEmpleos"); // NOI18N

        sllpFamiliaresEmpleos.setName("sllpFamiliaresEmpleos"); // NOI18N

        tblFamiliaresEmpleos.setFont(resourceMap.getFont("ContenidoTabla")); // NOI18N
        tblFamiliaresEmpleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFamiliaresEmpleos.setName("tblFamiliaresEmpleos"); // NOI18N
        sllpFamiliaresEmpleos.setViewportView(tblFamiliaresEmpleos);

        lblTituloCuadro.setForeground(resourceMap.getColor("ColorTextoCampo")); // NOI18N
        lblTituloCuadro.setText(resourceMap.getString("lblTituloCuadro.text")); // NOI18N
        lblTituloCuadro.setName("lblTituloCuadro"); // NOI18N

        btnAgregar.setIcon(resourceMap.getIcon("btnAgregar.icon")); // NOI18N
        btnAgregar.setName("btnAgregar"); // NOI18N

        btnModificar.setIcon(resourceMap.getIcon("btnModificar.icon")); // NOI18N
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.setPreferredSize(new java.awt.Dimension(22, 22));

        btnEliminar.setIcon(resourceMap.getIcon("btnEliminar.icon")); // NOI18N
        btnEliminar.setName("btnEliminar"); // NOI18N

        javax.swing.GroupLayout pnlCuadroDatosFamiliaresEmpleosLayout = new javax.swing.GroupLayout(pnlCuadroDatosFamiliaresEmpleos);
        pnlCuadroDatosFamiliaresEmpleos.setLayout(pnlCuadroDatosFamiliaresEmpleosLayout);
        pnlCuadroDatosFamiliaresEmpleosLayout.setHorizontalGroup(
            pnlCuadroDatosFamiliaresEmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                        .addComponent(sllpFamiliaresEmpleos, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                        .addComponent(lblTituloCuadro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        pnlCuadroDatosFamiliaresEmpleosLayout.setVerticalGroup(
            pnlCuadroDatosFamiliaresEmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTituloCuadro))
                    .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pnlCuadroDatosFamiliaresEmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, 0, 0, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(7, 7, 7)
                .addComponent(sllpFamiliaresEmpleos, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(pnlCuadroDatosFamiliaresEmpleos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCuadroDatosFamiliaresEmpleos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblTituloCuadro;
    private javax.swing.JPanel pnlCuadroDatosFamiliaresEmpleos;
    private javax.swing.JScrollPane sllpFamiliaresEmpleos;
    private javax.swing.JTable tblFamiliaresEmpleos;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtnAgregar() {
		return btnAgregar;
	}

	public javax.swing.JButton getBtnEliminar() {
		return btnEliminar;
	}

	public javax.swing.JButton getBtnModificar() {
		return btnModificar;
	}

	public javax.swing.JTable getTblFamiliaresEmpleos() {
		return tblFamiliaresEmpleos;
	}

    
    
}
