/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlABMAsientoContable.java
 *
 * Created on 29/08/2011, 20:02:59
 */
package ar.gov.cjpmv.prestamos.gui.contable;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.AdministradorAsientoContable;
import ar.gov.cjpmv.prestamos.core.business.AdministradorPlanCuenta;
import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.contable.Asiento;
import ar.gov.cjpmv.prestamos.core.persistence.contable.AsientoModelo;
import ar.gov.cjpmv.prestamos.core.persistence.contable.Cuenta;
import ar.gov.cjpmv.prestamos.core.persistence.contable.Movimiento;
import ar.gov.cjpmv.prestamos.core.persistence.contable.PlanCuenta;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.CbxAsientoModeloRenderer;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.MovimientoTblModel;
import ar.gov.cjpmv.prestamos.gui.utiles.Utiles;

/**
 *
 * @author daiana
 */
public class PnlABMAsientoContable extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -783232053476876940L;
	private Asiento asientoContable;
	private MovimientoTblModel modeloTblMovimiento;
	private AdministradorAsientoContable adminAsientoContable;
	private AdministradorPlanCuenta adminPlanCuenta;
	private AdminContableView vistaPadre;
	
    /** Creates new form PnlABMAsientoContable 
     * @throws LogicaException */
	public PnlABMAsientoContable(AdminContableView vista) throws LogicaException {
		this.vistaPadre = vista;
		this.adminAsientoContable = AdministracionFactory.getInstance().getAdministradorAsientoContable();
		this.adminPlanCuenta = AdministracionFactory.getInstance().getAdministradorPlanCuenta();
		initComponents();
		this.cbxAsientoModelo.setRenderer(new CbxAsientoModeloRenderer());
		inicializarModelos();
		inicializarEventos();
	
	}

    private void inicializarModelos() throws LogicaException {
    	this.modeloTblMovimiento = new MovimientoTblModel();
    	this.tblDetalleAsiento.setModel(modeloTblMovimiento);
		List<AsientoModelo> lista= new ArrayList<AsientoModelo>(); 
		lista.add(0, null);
		lista.addAll(adminAsientoContable.getListaAsientosModelo());
		this.cbxAsientoModelo.setModel(new DefaultComboBoxModel(lista.toArray()));
		actualizarPlanCuenta();
    }

    public void actualizarPlanCuenta() throws LogicaException {
    	PlanCuenta planCuentaActivo = this.adminPlanCuenta.getPlanCuentaActivo();
    	if (planCuentaActivo != null) {
    		this.tArbol.setPlanCuenta(planCuentaActivo);
    	}
    }
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlBlanco = new javax.swing.JPanel();
        pnlParametrosBusqueda = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCodigo1 = new javax.swing.JLabel();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        lblCodigo2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlAsiento = new javax.swing.JPanel();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        pnlBotonera.setOpaque(false);
        lblDetalles = new javax.swing.JLabel();
        lblEjerciciosContables1 = new javax.swing.JLabel();
        cbxAsientoModelo = new javax.swing.JComboBox();
        lblEjerciciosContables2 = new javax.swing.JLabel();
        lblTituloPnlDcha = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlABMAsientoContable.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        pnlBlanco.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        pnlBlanco.setName("jPanel1"); // NOI18N
       
        Color colorFondoPaneles = resourceMap.getColor("pnlParametrosBusqueda.background");
        pnlParametrosBusqueda.setBackground(colorFondoPaneles); // NOI18N
        pnlParametrosBusqueda.setName("pnlParametrosBusqueda"); // NOI18N

        lblCodigo.setFont(resourceMap.getFont("lblCodigo.font")); // NOI18N
        lblCodigo.setForeground(resourceMap.getColor("lblCodigo.foreground")); // NOI18N
        lblCodigo.setText(resourceMap.getString("lblCodigo.text")); // NOI18N
        lblCodigo.setName("lblCodigo"); // NOI18N

        txtNumero.setName("txtNumero"); // NOI18N

        lblCodigo1.setFont(resourceMap.getFont("lblCodigo1.font")); // NOI18N
        lblCodigo1.setForeground(resourceMap.getColor("lblCodigo1.foreground")); // NOI18N
        lblCodigo1.setText(resourceMap.getString("lblCodigo1.text")); // NOI18N
        lblCodigo1.setName("lblCodigo1"); // NOI18N

        dtcFecha.setForeground(resourceMap.getColor("dtcFecha.foreground")); // NOI18N
        dtcFecha.setFont(resourceMap.getFont("dtcFecha.font")); // NOI18N
        dtcFecha.setName("dtcFecha"); // NOI18N

        lblCodigo2.setFont(resourceMap.getFont("lblCodigo2.font")); // NOI18N
        lblCodigo2.setForeground(resourceMap.getColor("lblCodigo2.foreground")); // NOI18N
        lblCodigo2.setText(resourceMap.getString("lblCodigo2.text")); // NOI18N
        lblCodigo2.setName("lblCodigo2"); // NOI18N

        txtDescripcion.setName("txtDescripcion"); // NOI18N

        javax.swing.GroupLayout gl_pnlParametrosBusqueda = new javax.swing.GroupLayout(pnlParametrosBusqueda);
        gl_pnlParametrosBusqueda.setHorizontalGroup(
        	gl_pnlParametrosBusqueda.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnlParametrosBusqueda.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pnlParametrosBusqueda.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCodigo)
        				.addComponent(lblCodigo2))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(gl_pnlParametrosBusqueda.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_pnlParametrosBusqueda.createSequentialGroup()
        					.addComponent(txtNumero, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblCodigo1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(dtcFecha, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE))
        				.addComponent(txtDescripcion, GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        			.addContainerGap())
        );
        gl_pnlParametrosBusqueda.setVerticalGroup(
        	gl_pnlParametrosBusqueda.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnlParametrosBusqueda.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pnlParametrosBusqueda.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_pnlParametrosBusqueda.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblCodigo)
        					.addComponent(txtNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lblCodigo1, GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        				.addComponent(dtcFecha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_pnlParametrosBusqueda.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblCodigo2, GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        				.addComponent(txtDescripcion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        pnlParametrosBusqueda.setLayout(gl_pnlParametrosBusqueda);

        xtsTitulo.setForeground(resourceMap.getColor("xtsTitulo.foreground")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        btnAceptar.setFont(resourceMap.getFont("btnAceptar.font")); // NOI18N
        btnAceptar.setForeground(resourceMap.getColor("btnAceptar.foreground")); // NOI18N
        btnAceptar.setIcon(resourceMap.getIcon("btnAceptar.icon")); // NOI18N
        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setName("btnAceptar"); // NOI18N

        btnCancelar.setFont(resourceMap.getFont("btnCancelar.font")); // NOI18N
        btnCancelar.setForeground(resourceMap.getColor("btnCancelar.foreground")); // NOI18N
        btnCancelar.setIcon(resourceMap.getIcon("btnCancelar.icon")); // NOI18N
        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setName("btnCancelar"); // NOI18N

        pnlAsiento.setName("pnlParametrosBusqueda1"); // NOI18N
        pnlAsiento.setBackground(colorFondoPaneles);
        
        lblEjerciciosContables.setFont(resourceMap.getFont("lblEjerciciosContables.font")); // NOI18N
        lblEjerciciosContables.setForeground(resourceMap.getColor("lblEjerciciosContables.foreground")); // NOI18N
        lblEjerciciosContables.setText(resourceMap.getString("lblEjerciciosContables.text")); // NOI18N
        lblEjerciciosContables.setName("lblEjerciciosContables"); // NOI18N

        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblDetalles.setFont(resourceMap.getFont("lblDetalles.font")); // NOI18N
        lblDetalles.setForeground(resourceMap.getColor("lblDetalles.foreground")); // NOI18N
        lblDetalles.setIcon(resourceMap.getIcon("lblDetalles.icon")); // NOI18N
        lblDetalles.setText(resourceMap.getString("lblDetalles.text")); // NOI18N
        lblDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDetalles.setName("lblDetalles"); // NOI18N
        pnlBotonera.add(lblDetalles);

        lblEjerciciosContables1.setFont(resourceMap.getFont("lblEjerciciosContables1.font")); // NOI18N
        lblEjerciciosContables1.setForeground(resourceMap.getColor("lblEjerciciosContables1.foreground")); // NOI18N
        lblEjerciciosContables1.setText(resourceMap.getString("lblEjerciciosContables1.text")); // NOI18N
        lblEjerciciosContables1.setName("lblEjerciciosContables1"); // NOI18N

        cbxAsientoModelo.setForeground(resourceMap.getColor("cbxAsientoModelo.foreground")); // NOI18N
        cbxAsientoModelo.setName("cbxAsientoModelo"); // NOI18N

        lblEjerciciosContables2.setFont(new Font("Dialog", Font.BOLD, 11)); // NOI18N
        lblEjerciciosContables2.setForeground(resourceMap.getColor("lblEjerciciosContables2.foreground")); // NOI18N
        lblEjerciciosContables2.setText(resourceMap.getString("lblEjerciciosContables2.text")); // NOI18N
        lblEjerciciosContables2.setName("lblEjerciciosContables2");
        
        JSplitPane splitPane = new JSplitPane();
        splitPane.setResizeWeight(.5d);
        javax.swing.GroupLayout gl_pnlAsiento = new javax.swing.GroupLayout(pnlAsiento);
        gl_pnlAsiento.setHorizontalGroup(
        	gl_pnlAsiento.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_pnlAsiento.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pnlAsiento.createParallelGroup(Alignment.LEADING)
        				.addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        				.addComponent(lblEjerciciosContables, GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        				.addGroup(gl_pnlAsiento.createSequentialGroup()
        					.addComponent(lblEjerciciosContables2)
        					.addPreferredGap(ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
        					.addComponent(lblEjerciciosContables1, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cbxAsientoModelo, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(pnlBotonera, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        gl_pnlAsiento.setVerticalGroup(
        	gl_pnlAsiento.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnlAsiento.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblEjerciciosContables)
        			.addGap(12)
        			.addGroup(gl_pnlAsiento.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_pnlAsiento.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblEjerciciosContables2, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cbxAsientoModelo, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lblEjerciciosContables1))
        				.addComponent(pnlBotonera, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        			.addContainerGap())
        );
        tArbol = new PnlFiltradoPlanCuenta();
        splitPane.setLeftComponent(tArbol);
        tArbol.getBtnEliminar().setFont(new Font("Dialog", Font.BOLD, 9));
        tArbol.getBtnAgregar().setFont(new Font("Dialog", Font.BOLD, 9));
        
                tArbol.setName("tArbol");
                jScrollPane1 = new javax.swing.JScrollPane();
                splitPane.setRightComponent(jScrollPane1);
                tblDetalleAsiento = new javax.swing.JTable();
                
                        jScrollPane1.setName("jScrollPane1"); // NOI18N
                        
                                tblDetalleAsiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                tblDetalleAsiento.setName("tblDetalleAsiento"); // NOI18N
                                jScrollPane1.setViewportView(tblDetalleAsiento);
        pnlAsiento.setLayout(gl_pnlAsiento);

        javax.swing.GroupLayout gl_pnlBlanco = new javax.swing.GroupLayout(pnlBlanco);
        gl_pnlBlanco.setHorizontalGroup(
        	gl_pnlBlanco.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnlBlanco.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pnlBlanco.createParallelGroup(Alignment.LEADING)
        				.addComponent(pnlParametrosBusqueda, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        				.addComponent(xtsTitulo, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        				.addGroup(Alignment.TRAILING, gl_pnlBlanco.createSequentialGroup()
        					.addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE))
        				.addComponent(pnlAsiento, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        			.addContainerGap())
        );
        gl_pnlBlanco.setVerticalGroup(
        	gl_pnlBlanco.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_pnlBlanco.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(xtsTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(pnlParametrosBusqueda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(5)
        			.addComponent(pnlAsiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_pnlBlanco.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnAceptar, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addGap(23))
        );
        pnlBlanco.setLayout(gl_pnlBlanco);

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(pnlBlanco, GroupLayout.PREFERRED_SIZE, 676, Short.MAX_VALUE)
        				.addComponent(lblTituloPnlDcha, GroupLayout.PREFERRED_SIZE, 559, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(11)
        			.addComponent(lblTituloPnlDcha)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(pnlBlanco, GroupLayout.PREFERRED_SIZE, 545, Short.MAX_VALUE)
        			.addContainerGap())
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbxAsientoModelo;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JPanel pnlBlanco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEjerciciosContables1;
    private javax.swing.JLabel lblEjerciciosContables2;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda;
    private javax.swing.JPanel pnlAsiento;
    private PnlFiltradoPlanCuenta tArbol;
    private javax.swing.JTable tblDetalleAsiento;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNumero;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables
    
	public void setAsiento(Asiento pAsiento) {
		this.asientoContable = pAsiento;
		this.actualizarVista();
	}
	 
	private void detalles() {
		int locSeleccionado= this.tblDetalleAsiento.getSelectedRow();
		Movimiento locMov= this.modeloTblMovimiento.getMovimiento(locSeleccionado);
		PnlDetalleAsientoContable detalleView= new PnlDetalleAsientoContable(vistaPadre, true, locMov);
		detalleView.setTitle("Asiento Contable: Detalles");
		detalleView.setLocationRelativeTo(this.vistaPadre);
		detalleView.setVisible(true);		
	}

	private void inicializarEventos() {
		this.lblDetalles.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				detalles();
			}

		});

		this.tblDetalleAsiento.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowAsiento()){
					lblDetalles.setEnabled(true);
				}
			}
		});
		
		this.btnAceptar.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				guardar();				
			}
		});

		this.btnCancelar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				cancelar();
			}
		});
		
		this.tArbol.gettArbol().addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2) {
					agregarCuenta();
				}
			}
		});
		
		this.tArbol.getBtnAgregar().addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				agregarCuenta();
			}

		});

		this.tArbol.getBtnEliminar().addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				int fila = tblDetalleAsiento.getSelectedRow();
				if (fila != -1) {
					modeloTblMovimiento.eliminarFila(fila);
				}
			}
		});
		this.cbxAsientoModelo.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				actualizarModeloTblAsientos();
			}
		});
	}
		
	private void agregarCuenta() {
		try {
			Cuenta cuenta = tArbol.getCuentaSeleccionada();
			if (cuenta != null) {
				if (!cuenta.isRecibeAsiento()) {
					JOptionPane.showMessageDialog(
							PnlABMAsientoContable.this, 
							"La cuenta no puede recibir asientos", 
							"Error", 
							JOptionPane.ERROR_MESSAGE);
				}
				else {
					Movimiento movimiento = new Movimiento();
					movimiento.setAsiento(asientoContable);
					movimiento.setCuenta(cuenta);
					movimiento.setMontoDebe(new BigDecimal("0.00"));
					movimiento.setMontoHaber(new BigDecimal("0.00"));
					modeloTblMovimiento.agregar(movimiento);
				}
			}
		}
		catch(LogicaException ex) {
			mostrarMensaje(ex);
		}
	}
	
	private void cancelar() {
		String pMensaje= "¿Realmente desea cancelar la operación?";
		String pTitulo= "Confirmación";
	
		int locConfirmacion= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
		if(locConfirmacion==JOptionPane.YES_OPTION){
			this.vistaPadre.actualizarListaAsiento();
			this.vistaPadre.mostrarAdminAsientoContable();
		}
	}
		
	private void actualizarModeloTblAsientos() {
		String mensaje="Al aplicar la plantilla se modificaran los cambios que haya efectuado \nen las cuentas. ¿Realmente desea aplicar la plantilla?";
		int locConfirmacion= JOptionPane.showConfirmDialog(this, mensaje, "Confirmación", JOptionPane.YES_NO_OPTION);
		AsientoModelo locAsientoModelo= (AsientoModelo) this.cbxAsientoModelo.getSelectedItem();
		if(locConfirmacion==JOptionPane.YES_OPTION){
			if(locAsientoModelo!=null){
				this.modeloTblMovimiento.setListaMovimiento(locAsientoModelo.getListaMovimiento());
			}
			else{
				modeloTblMovimiento.setListaMovimiento(new ArrayList<Movimiento>());
			}
		}
	}

	private void mostrarMensaje(LogicaException e) {
		JOptionPane.showMessageDialog(
				this, 
				e.getMessage(), 
				"Error", 
				JOptionPane.ERROR_MESSAGE);
	}

	private void guardar() {
		try {
			actualizarModelo();
			adminAsientoContable.agregarAsiento(this.asientoContable);
			String mensaje= "Los datos se han guardado correctamente.";
			String titulo= "Actualizar asiento";
			JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
			setAsiento(new Asiento());
		}
		catch(LogicaException e) {
			mostrarMensaje(e);
		}
		catch(Exception e){
			e.printStackTrace();
			String mensaje="Se ha producido un error. Algunos de los datos tiene un formato incorrecto.";
			String titulo="Error";
			JOptionPane.showMessageDialog(this,mensaje, titulo, JOptionPane.ERROR_MESSAGE);
		}
	}

	private boolean isSelectedRowAsiento() {
		return this.tblDetalleAsiento.getSelectedRow() != -1;
	}

	private void actualizarModelo() {
		if (asientoContable == null) {
			asientoContable = new Asiento();
		}
		asientoContable.setListaMovimiento(modeloTblMovimiento.getListaMovimiento());
		asientoContable.setDescripcion(Utiles.nuloSiVacio(txtDescripcion.getText()));
		asientoContable.setFecha(dtcFecha.getDate());
		String numero = Utiles.nuloSiVacio(txtNumero.getText());
		if (numero == null) {
			asientoContable.setNumero(null);			
		}
		else {
			asientoContable.setNumero(Integer.parseInt(numero));
		}
	}

	private void actualizarVista() {
		if(this.asientoContable.getId() != null) {
			this.txtNumero.setText(this.asientoContable.getNumero().toString());
			this.dtcFecha.setDate(this.asientoContable.getFecha());
			this.txtDescripcion.setText(Utiles.vacioSiNulo(this.asientoContable.getDescripcion()));
			this.modeloTblMovimiento.setListaMovimiento(asientoContable.getListaMovimiento());
			this.cbxAsientoModelo.setVisible(false);
			this.lblEjerciciosContables1.setVisible(false);
		}
		else{
			//cambiar estos dos valores a true cuando este hecha la parte de asientos modelos
			this.cbxAsientoModelo.setVisible(false);
			this.lblEjerciciosContables1.setVisible(false);
			
			Integer numero = adminAsientoContable.getNumeroSiguienteAsiento();
			this.txtNumero.setText(Utiles.vacioSiNulo(numero.toString()));
			this.dtcFecha.setDate(Calendar.getInstance().getTime());
			this.txtDescripcion.setText("");
			modeloTblMovimiento.setListaMovimiento(new ArrayList<Movimiento>());
		}
		this.lblDetalles.setEnabled(false);
	}

	public static void main(String[] args) throws LogicaException {
		JFrame frame = new JFrame();
		frame.getContentPane().add(new PnlABMAsientoContable(null));
		frame.pack();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}
}
