/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlBusquedaPlanesCuenta.java
 *
 * Created on 14/07/2011, 20:44:50
 */
package ar.gov.cjpmv.prestamos.gui.contable;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.persistence.contable.Cuenta;
import ar.gov.cjpmv.prestamos.core.persistence.contable.EjercicioContable;
import ar.gov.cjpmv.prestamos.core.persistence.contable.PlanCuenta;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.CuentaTableModel;

/**
 *
 * @author pulpol
 */
public class PnlBusquedaPlanesCuenta extends javax.swing.JPanel {

    private static final long serialVersionUID = -9150889965572946435L;

	/** Creates new form PnlBusquedaPlanesCuenta */
    public PnlBusquedaPlanesCuenta() {
        initComponents();
        
        inicializarRenderers();
        inicializarModelos();
        inicializarEventos();
    }

    private void inicializarRenderers() {
    	this.lPlanCuenta.setCellRenderer(new PlanCuentaListCellRenderer());
	}

	private void inicializarEventos() {
    	this.lPlanCuenta.addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent e) {
				enSeleccionLista();
			}
		});
	}

	private void inicializarModelos() {
		this.tblCuenta.setModel(this.modeloTablaCuentas);
    	if (listaPlanesCuenta != null) {
    		this.lPlanCuenta.setListData(this.listaPlanesCuenta.toArray());
    	}
    	else {
    		this.lPlanCuenta.setListData(new Object[0]);
    	}
	}

	private void enSeleccionLista() {
		PlanCuenta planCuenta = (PlanCuenta)lPlanCuenta.getSelectedValue();
		
		//FIXME ACÁ DEBERÍA TRAER TODAS las cuentas desde el dao directamente, esta conversión no iría
		List<Cuenta> cuentas = getListaCuentas(planCuenta);		
		this.modeloTablaCuentas.setCuentas(cuentas);
	}
	//FIXME reemplazar por una llamada al dao
	@Deprecated
	private List<Cuenta> getListaCuentas(PlanCuenta planCuenta) {
		List<Cuenta> cuentas = new ArrayList<Cuenta>();
		for (Cuenta cuenta : planCuenta.getListaCuenta()) {
			cuentas.addAll(getListaCuentas(cuenta));
		}
		return cuentas;
	}

	@Deprecated
	private List<Cuenta> getListaCuentas(Cuenta cuenta) {
		List<Cuenta> cuentas = new ArrayList<Cuenta>();
		cuentas.add(cuenta);
		for (Cuenta cadaCuenta : cuenta.getCuentasHijas()) {
			cuentas.addAll(getListaCuentas(cadaCuenta));
		}
		return cuentas;
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPrincipal = new javax.swing.JLabel();
        javax.swing.JPanel pnlBlanco = new javax.swing.JPanel();
        javax.swing.JPanel pnlCuenta = new javax.swing.JPanel();
        javax.swing.JScrollPane scpTblCuentas = new javax.swing.JScrollPane();
        tblCuenta = new javax.swing.JTable();
        javax.swing.JLabel lblTituloCuenta = new javax.swing.JLabel();
        javax.swing.JPanel pnlPlanCuenta = new javax.swing.JPanel();
        lblModificar = new javax.swing.JLabel();
        javax.swing.JLabel lblTituloPlanCuenta = new javax.swing.JLabel();
        javax.swing.JScrollPane spPlanesCuenta = new javax.swing.JScrollPane();
        lPlanCuenta = new javax.swing.JList();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlBusquedaPlanesCuenta.class);
        setBackground(resourceMap.getColor("FondoCeleste")); // NOI18N
        setName("Form"); // NOI18N

        lblTituloPrincipal.setFont(resourceMap.getFont("lblTituloPrincipal.font")); // NOI18N
        lblTituloPrincipal.setForeground(resourceMap.getColor("lblTituloPrincipal.foreground")); // NOI18N
        lblTituloPrincipal.setText(resourceMap.getString("lblTituloPrincipal.text")); // NOI18N
        lblTituloPrincipal.setName("lblTituloPrincipal"); // NOI18N

        pnlBlanco.setBackground(resourceMap.getColor("FondoBlanco")); // NOI18N
        pnlBlanco.setName("pnlBlanco"); // NOI18N

        pnlCuenta.setName("jPanel2"); // NOI18N

        scpTblCuentas.setName("scpTblCuentas"); // NOI18N

        tblCuenta.setName("tblCuenta"); // NOI18N
        scpTblCuentas.setViewportView(tblCuenta);

        lblTituloCuenta.setText(resourceMap.getString("lblTituloCuenta.text")); // NOI18N
        lblTituloCuenta.setName("lblTituloCuenta"); // NOI18N

        javax.swing.GroupLayout pnlCuentaLayout = new javax.swing.GroupLayout(pnlCuenta);
        pnlCuenta.setLayout(pnlCuentaLayout);
        pnlCuentaLayout.setHorizontalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpTblCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addComponent(lblTituloCuenta))
                .addContainerGap())
        );
        pnlCuentaLayout.setVerticalGroup(
            pnlCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpTblCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPlanCuenta.setBackground(resourceMap.getColor("pnlPlanCuenta.background")); // NOI18N
        pnlPlanCuenta.setName("pnlPlanCuenta"); // NOI18N

        lblModificar.setIcon(resourceMap.getIcon("lblModificar.icon")); // NOI18N
        lblModificar.setText(resourceMap.getString("lblModificar.text")); // NOI18N
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.setName("lblModificar"); // NOI18N

        lblTituloPlanCuenta.setText(resourceMap.getString("lblTituloPlanCuenta.text")); // NOI18N
        lblTituloPlanCuenta.setName("lblTituloPlanCuenta"); // NOI18N

        spPlanesCuenta.setName("spPlanesCuenta"); // NOI18N

        lPlanCuenta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lPlanCuenta.setName("lPlanCuenta"); // NOI18N
        spPlanesCuenta.setViewportView(lPlanCuenta);

        javax.swing.GroupLayout pnlPlanCuentaLayout = new javax.swing.GroupLayout(pnlPlanCuenta);
        pnlPlanCuenta.setLayout(pnlPlanCuentaLayout);
        pnlPlanCuentaLayout.setHorizontalGroup(
            pnlPlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlanCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spPlanesCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addGroup(pnlPlanCuentaLayout.createSequentialGroup()
                        .addComponent(lblTituloPlanCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 544, Short.MAX_VALUE)
                        .addComponent(lblModificar)))
                .addContainerGap())
        );
        pnlPlanCuentaLayout.setVerticalGroup(
            pnlPlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar)
                    .addComponent(lblTituloPlanCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPlanesCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBlancoLayout = new javax.swing.GroupLayout(pnlBlanco);
        pnlBlanco.setLayout(pnlBlancoLayout);
        pnlBlancoLayout.setHorizontalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlanCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBlancoLayout.setVerticalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPlanCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList lPlanCuenta;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JTable tblCuenta;
    // End of variables declaration//GEN-END:variables
    private List<PlanCuenta> listaPlanesCuenta;
    private CuentaTableModel modeloTablaCuentas = new CuentaTableModel();
    
    public void add(PlanCuenta pPlanCuenta)  {
    	if (this.listaPlanesCuenta == null) {
    		this.listaPlanesCuenta = new ArrayList<PlanCuenta>();
    	}
    	if (pPlanCuenta != null 
    		&& !this.listaPlanesCuenta.contains(pPlanCuenta)) {
    		this.listaPlanesCuenta.add(pPlanCuenta);
    		this.lPlanCuenta.setListData(listaPlanesCuenta.toArray());
    	}
    }
    
    public static void main(String[] args) {
    	PnlBusquedaPlanesCuenta pnl = new PnlBusquedaPlanesCuenta();
    	
    	Calendar calendario = Calendar.getInstance();
		calendario.set(Calendar.MONTH, Calendar.JANUARY);
		
		PlanCuenta planCuenta1 = new PlanCuenta();
		planCuenta1.setPeriodo(new EjercicioContable());
		planCuenta1.getPeriodo().setFechaInicio(calendario.getTime());
		calendario.set(Calendar.MONTH, Calendar.DECEMBER);
		planCuenta1.getPeriodo().setFechaFin(calendario.getTime());
		pnl.add(planCuenta1);
    	
		Cuenta cuenta1 = new Cuenta();
		cuenta1.setNombre("asdasd");
		cuenta1.setCodigo("00");
		cuenta1.setPadre(null);
		cuenta1.setPlanCuenta(planCuenta1);
		
		Cuenta cuenta11 = new Cuenta();
		cuenta11.setNombre("ssss");
		cuenta11.setCodigo("01");
		cuenta11.setPadre(cuenta1);
		cuenta11.setPlanCuenta(planCuenta1);
		
		Cuenta cuenta12 = new Cuenta();
		cuenta12.setCodigo("02");
		cuenta12.setNombre("ddddd");
		cuenta12.setPadre(cuenta1);
		cuenta12.setPlanCuenta(planCuenta1);
		
		cuenta1.getCuentasHijas().add(cuenta11);
		cuenta1.getCuentasHijas().add(cuenta12);
		
		Cuenta cuenta2 = new Cuenta();
		cuenta2.setCodigo("01");
		cuenta2.setNombre("fffff");
		cuenta2.setPadre(null);
		cuenta2.setPlanCuenta(planCuenta1);
		
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.add(pnl);
		frame.pack();
		frame.setVisible(true);
	}
    
}
