/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlBusquedaAsientoContable.java
 *
 * Created on 29/08/2011, 18:54:57
 */
package ar.gov.cjpmv.prestamos.gui.contable;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.contable.Asiento;
import ar.gov.cjpmv.prestamos.core.persistence.contable.EjercicioContable;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.AsientoContableTblModel;
import ar.gov.cjpmv.prestamos.gui.utiles.Utiles;

/**
 *
 * @author daiana
 */
public class PnlBusquedaAsientoContable extends javax.swing.JPanel {

	private AdminContableView adminContable;
	private AdministracionFactory adminFactory;
	
	private Date fechaDesde;
	private Date fechaHasta;
	private String descripcion;
	private Integer numeroAsiento;
	private AsientoContableTblModel modeloTblAsiento;
	
	
	private List<Asiento> listaAsiento;
	
	
    /** Creates new form PnlBusquedaAsientoContable */
    public PnlBusquedaAsientoContable(AdminContableView adminContableView) {
        initComponents();
        this.adminContable= adminContableView;
        this.adminFactory= AdministracionFactory.getInstance();
        
 	   this.listaAsiento= new ArrayList<Asiento>();
 	   this.modeloTblAsiento= new AsientoContableTblModel();
 	   this.modeloTblAsiento.setListaAsiento(this.listaAsiento);

 	   this.inicializarEventos();
 	   this.inicializarVista();
        
    }
    
 
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlParametrosBusqueda1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsientos = new javax.swing.JTable();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        pnlParametrosBusqueda = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        dtcFechaDesde = new com.toedter.calendar.JDateChooser();
        lblCodigo1 = new javax.swing.JLabel();
        lblCodigo2 = new javax.swing.JLabel();
        dtcFechaHasta = new com.toedter.calendar.JDateChooser();
        txtNumero = new javax.swing.JTextField();
        lblCodigo3 = new javax.swing.JLabel();
        lblTituloPnlDcha = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlBusquedaAsientoContable.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        pnlParametrosBusqueda1.setName("pnlParametrosBusqueda1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "N° Asiento", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAsientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblAsientos.setName("tblAsientos"); // NOI18N
        jScrollPane1.setViewportView(tblAsientos);

        lblEjerciciosContables.setFont(resourceMap.getFont("lblEjerciciosContables.font")); // NOI18N
        lblEjerciciosContables.setForeground(resourceMap.getColor("lblEjerciciosContables.foreground")); // NOI18N
        lblEjerciciosContables.setText(resourceMap.getString("lblEjerciciosContables.text")); // NOI18N
        lblEjerciciosContables.setName("lblEjerciciosContables"); // NOI18N

        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblAgregar.setFont(resourceMap.getFont("lblAgregar.font")); // NOI18N
        lblAgregar.setForeground(resourceMap.getColor("lblAgregar.foreground")); // NOI18N
        lblAgregar.setIcon(resourceMap.getIcon("lblAgregar.icon")); // NOI18N
        lblAgregar.setText(resourceMap.getString("lblAgregar.text")); // NOI18N
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setName("lblAgregar"); // NOI18N
        pnlBotonera.add(lblAgregar);

        lblEditar.setFont(resourceMap.getFont("lblEditar.font")); // NOI18N
        lblEditar.setForeground(resourceMap.getColor("lblEditar.foreground")); // NOI18N
        lblEditar.setIcon(resourceMap.getIcon("lblEditar.icon")); // NOI18N
        lblEditar.setText(resourceMap.getString("lblEditar.text")); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.setName("lblEditar"); // NOI18N
        pnlBotonera.add(lblEditar);

        lblEliminar.setFont(resourceMap.getFont("lblEliminar.font")); // NOI18N
        lblEliminar.setForeground(resourceMap.getColor("lblEliminar.foreground")); // NOI18N
        lblEliminar.setIcon(resourceMap.getIcon("lblEliminar.icon")); // NOI18N
        lblEliminar.setText(resourceMap.getString("lblEliminar.text")); // NOI18N
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setName("lblEliminar"); // NOI18N
        pnlBotonera.add(lblEliminar);

        javax.swing.GroupLayout pnlParametrosBusqueda1Layout = new javax.swing.GroupLayout(pnlParametrosBusqueda1);
        pnlParametrosBusqueda1.setLayout(pnlParametrosBusqueda1Layout);
        pnlParametrosBusqueda1Layout.setHorizontalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusqueda1Layout.setVerticalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblEjerciciosContables))
                    .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlParametrosBusqueda.setName("pnlParametrosBusqueda"); // NOI18N

        lblNombre.setFont(resourceMap.getFont("lblNombre.font")); // NOI18N
        lblNombre.setForeground(resourceMap.getColor("lblNombre.foreground")); // NOI18N
        lblNombre.setText(resourceMap.getString("lblNombre.text")); // NOI18N
        lblNombre.setName("lblNombre"); // NOI18N

        txtDescripcion.setName("txtDescripcion"); // NOI18N

        btnBuscar.setIcon(resourceMap.getIcon("btnBuscar.icon")); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setName("btnBuscar"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("xtsTitulo.foreground")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        dtcFechaDesde.setForeground(resourceMap.getColor("dtcFechaDesde.foreground")); // NOI18N
        dtcFechaDesde.setFont(resourceMap.getFont("dtcFechaDesde.font")); // NOI18N
        dtcFechaDesde.setName("dtcFechaDesde"); // NOI18N

        lblCodigo1.setFont(resourceMap.getFont("lblCodigo1.font")); // NOI18N
        lblCodigo1.setForeground(resourceMap.getColor("lblCodigo1.foreground")); // NOI18N
        lblCodigo1.setText(resourceMap.getString("lblCodigo1.text")); // NOI18N
        lblCodigo1.setName("lblCodigo1"); // NOI18N

        lblCodigo2.setFont(resourceMap.getFont("lblCodigo2.font")); // NOI18N
        lblCodigo2.setForeground(resourceMap.getColor("lblCodigo2.foreground")); // NOI18N
        lblCodigo2.setText(resourceMap.getString("lblCodigo2.text")); // NOI18N
        lblCodigo2.setName("lblCodigo2"); // NOI18N

        dtcFechaHasta.setForeground(resourceMap.getColor("dtcFechaHasta.foreground")); // NOI18N
        dtcFechaHasta.setFont(resourceMap.getFont("dtcFechaHasta.font")); // NOI18N
        dtcFechaHasta.setName("dtcFechaHasta"); // NOI18N

        txtNumero.setName("txtNumero"); // NOI18N

        lblCodigo3.setFont(resourceMap.getFont("lblCodigo3.font")); // NOI18N
        lblCodigo3.setForeground(resourceMap.getColor("lblCodigo3.foreground")); // NOI18N
        lblCodigo3.setText(resourceMap.getString("lblCodigo3.text")); // NOI18N
        lblCodigo3.setName("lblCodigo3"); // NOI18N

        javax.swing.GroupLayout pnlParametrosBusquedaLayout = new javax.swing.GroupLayout(pnlParametrosBusqueda);
        pnlParametrosBusqueda.setLayout(pnlParametrosBusquedaLayout);
        pnlParametrosBusquedaLayout.setHorizontalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(dtcFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblCodigo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtcFechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusquedaLayout.setVerticalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodigo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCodigo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtcFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(dtcFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodigo3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloPnlDcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private com.toedter.calendar.JDateChooser dtcFechaDesde;
    private com.toedter.calendar.JDateChooser dtcFechaHasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblCodigo3;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda;
    private javax.swing.JPanel pnlParametrosBusqueda1;
    private javax.swing.JTable tblAsientos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNumero;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables
    
    
    
 	private void inicializarVista() {
 		this.tblAsientos.setModel(this.modeloTblAsiento);
 		this.lblEditar.setEnabled(false);
 		this.lblEliminar.setEnabled(false);
 	}

 	private void inicializarEventos() {
 		this.btnBuscar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				lblEditar.setEnabled(false);
				lblEliminar.setEnabled(false);
				buscarAsiento();
			}
		});
 		
 		this.lblAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				agregar();
			}
		});
		
		this.lblEditar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				editar();
			}
		});
		
		this.lblEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				eliminar();
			}
		});
		
		this.tblAsientos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowAsiento()){
					int seleccionado= tblAsientos.getSelectedRow();
					lblEditar.setEnabled(true);
					lblEliminar.setEnabled(true);
				}
			}
		});
 		
 	}
 	
 	
 	private boolean isSelectedRowAsiento() {
 		return this.tblAsientos.getSelectedRow() != -1;
	}
 	
 	private void agregar() {
  		this.adminContable.mostrarABMAsientoContable();
		this.adminContable.getPnlABMAsientoContable().setAsiento(new Asiento());
	}
 	
 	
	private void editar() {
		int seleccionado= this.tblAsientos.getSelectedRow();
    	Asiento locAsiento= this.modeloTblAsiento.getAsiento(seleccionado);
    	this.adminContable.mostrarABMAsientoContable();
    	this.adminContable.getPnlABMAsientoContable().setAsiento(locAsiento);
	}

	private void eliminar() {
		try{
			int seleccionado= this.tblAsientos.getSelectedRow();
			Asiento locAsiento= this.modeloTblAsiento.getAsiento(seleccionado);
		
			String pMensaje= "¿Realmente desea eliminar el asiento contable "+locAsiento.getNumero()+": "+locAsiento.getDescripcion()+"?";
			String pTitulo= "Eliminar Asiento Contable";
			int locConfirm= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
			if(locConfirm==JOptionPane.YES_OPTION){
				this.adminFactory.getAdministradorAsientoContable().eliminarAsiento(locAsiento);
				this.buscarAsiento();
			}
		}
		catch (LogicaException e){
			String pMensaje=e.getMessage();
			String pTitulo=e.getTitulo();
			JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.ERROR_MESSAGE);
		}	
	}

 	


 	
 	
 	public void buscarAsiento(){
 		try{
	 		this.actualizarModelo();
	 		this.listaAsiento = this.adminFactory.getAdministradorAsientoContable().findListaAsientoContable(this.fechaDesde, this.fechaHasta, this.descripcion, this.numeroAsiento);
	 		if(this.listaAsiento!=null){
	 			this.modeloTblAsiento.setListaAsiento(this.listaAsiento);
	 			this.tblAsientos.setModel(this.modeloTblAsiento);
	 		}
	 		else{
	 			this.listaAsiento= new ArrayList<Asiento>();
	 			this.modeloTblAsiento.setListaAsiento(this.listaAsiento);
	 			this.tblAsientos.setModel(this.modeloTblAsiento);
	 		}
		
 		}
 		catch(LogicaException e){
 			e.printStackTrace();
 			JOptionPane.showMessageDialog(this, e.getMessage(), e.getTitulo(), JOptionPane.ERROR_MESSAGE);
 			this.listaAsiento= new ArrayList<Asiento>();
 			this.modeloTblAsiento.setListaAsiento(this.listaAsiento);
 			this.tblAsientos.setModel(this.modeloTblAsiento);
	}
 			
 }




	private void actualizarModelo() throws LogicaException {

			if(this.dtcFechaDesde.getDate()!=null){
				this.fechaDesde= this.dtcFechaDesde.getDate();
			
			}
			if(this.dtcFechaHasta.getDate()!=null){
				this.fechaHasta= this.dtcFechaHasta.getDate();
			}
				
			if((this.fechaDesde!=null && this.fechaHasta==null) || (this.fechaDesde==null && this.fechaHasta!=null)){
				int codigo= 121;
				String campo="";
				throw new LogicaException(codigo, campo);
			}
			
			if((this.fechaDesde!=null) && (this.fechaHasta!=null)){
				if(this.fechaDesde.after(this.fechaHasta)){
					int codigo= 113;
					String campo="";
					throw new LogicaException(codigo, campo);
				}
			}
			
				
			this.descripcion= Utiles.nuloSiVacio(this.txtDescripcion.getText().trim());
		
			String txtNumero= Utiles.nuloSiVacio(this.txtNumero.getText().trim());
			if(txtNumero!=null){
				try{
					this.numeroAsiento= Integer.parseInt(txtNumero);
				}
				catch(NumberFormatException e){
					String locCampo="";
					Integer cod=120;
					throw new LogicaException(cod, locCampo);
				}
			}
					
	}
	
	
}
