/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlCopiaPlanCuentas.java
 *
 * Created on 28/06/2011, 21:38:35
 */

package ar.gov.cjpmv.prestamos.gui.contable;

import java.util.Calendar;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingWorker;

import org.hibernate.cfg.NotYetImplementedException;

import ar.gov.cjpmv.prestamos.core.business.AdministradorPlanCuenta;
import ar.gov.cjpmv.prestamos.core.persistence.contable.PlanCuenta;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;

/**
 *
 * @author dernst
 */
public class PnlCopiaPlanCuentas extends javax.swing.JPanel {

	private static final long serialVersionUID = -4487789112206672911L;
	private AdministradorPlanCuenta administradorPlanCuenta;
	
	/** Creates new form PnlCopiaPlanCuentas */
    public PnlCopiaPlanCuentas() {
    	this.administradorPlanCuenta = AdministracionFactory.getInstance().getAdministradorPlanCuenta();
        initComponents();
        inicializarModelos();
    }

    private void inicializarModelos() {
    	SwingWorker<Void, Void> background = new SwingWorker<Void, Void>() {
    		@Override
    		protected Void doInBackground() throws Exception {
    			int anio = Calendar.getInstance().get(Calendar.YEAR);
    			spAnio.setModel(new SpinnerNumberModel(anio,1980,2100,1));
    			actualizarListaPlanes();
    			return null;
    		}
    	};
    	background.execute();
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblCopiarPlan = new javax.swing.JLabel();
        lblCopiarPlan.setVisible(false);
        cbxPeriodo = new javax.swing.JComboBox();
        cbxPeriodo.setVisible(false);
        btnActualizar = new javax.swing.JButton();
        btnActualizar.setVisible(false);
        javax.swing.JLabel lblPeriodoContable = new javax.swing.JLabel();
        spAnio = new javax.swing.JSpinner();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlCopiaPlanCuentas.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        lblCopiarPlan.setFont(resourceMap.getFont("lblCopiarPlan.font")); // NOI18N
        lblCopiarPlan.setForeground(resourceMap.getColor("lblCopiarPlan.foreground")); // NOI18N
        lblCopiarPlan.setText(resourceMap.getString("lblCopiarPlan.text")); // NOI18N
        lblCopiarPlan.setName("lblCopiarPlan"); // NOI18N

        cbxPeriodo.setForeground(resourceMap.getColor("cbxPeriodo.foreground")); // NOI18N
        cbxPeriodo.setName("cbxPeriodo"); // NOI18N

        btnActualizar.setFont(resourceMap.getFont("btnActualizar.font")); // NOI18N
        btnActualizar.setForeground(resourceMap.getColor("btnActualizar.foreground")); // NOI18N
        btnActualizar.setText(resourceMap.getString("btnActualizar.text")); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setMaximumSize(new java.awt.Dimension(87, 26));
        btnActualizar.setMinimumSize(new java.awt.Dimension(87, 26));
        btnActualizar.setName("btnActualizar"); // NOI18N

        lblPeriodoContable.setFont(resourceMap.getFont("lblPeriodoContable.font")); // NOI18N
        lblPeriodoContable.setForeground(resourceMap.getColor("lblPeriodoContable.foreground")); // NOI18N
        lblPeriodoContable.setText(resourceMap.getString("lblPeriodoContable.text")); // NOI18N
        lblPeriodoContable.setName("lblPeriodoContable"); // NOI18N

        spAnio.setName("spAnio"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCopiarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPeriodo, 0, 105, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodoContable)
                    .addComponent(spAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCopiarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox cbxPeriodo;
    private javax.swing.JSpinner spAnio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JComboBox getCbxPeriodo() {
        return cbxPeriodo;
    }

    public javax.swing.JSpinner getSpAnio() {
		return spAnio;
	}
    
    public PlanCuenta getPlanCuentaSeleccionado() {
    	//TODO revisar el dao y devolver un plan de cuenta que se corresponda con 
    	//el año
    	throw new NotYetImplementedException("getPlanCuenta no ta terminado");
    }

	public void actualizarListaPlanes() {
		List<PlanCuenta> listaPlanesCuenta = administradorPlanCuenta.getListaPlanesCuenta();
		cbxPeriodo.setModel(new DefaultComboBoxModel(listaPlanesCuenta.toArray()));
	}
}
