/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlEjercioContable.java
 *
 * Created on 19/07/2011, 20:31:44
 */
package ar.gov.cjpmv.prestamos.gui.contable;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.contable.EjercicioContable;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.EjercicioContableTableModel;
import ar.gov.cjpmv.prestamos.gui.utiles.Utiles;

/**
 *
 * @author daiana
 */
public class PnlEjercicioContable extends javax.swing.JPanel {

	
	private static final long serialVersionUID = -1099363652075867363L;

	private String nombre;
	private List<EjercicioContable> listaPeriodo;
	private EjercicioContableTableModel modeloEjercicios;
	private AdminContableView adminContable;
	private AdministracionFactory adminFactory;
	
	
    /** Creates new form PnlEjercioContable 
     * @param adminContableView */
      
    public PnlEjercicioContable(AdminContableView adminContableView) {
        initComponents();
      
        this.adminContable= adminContableView;
        this.listaPeriodo= new ArrayList<EjercicioContable>();
        this.modeloEjercicios= new EjercicioContableTableModel();
        this.modeloEjercicios.setEjercicios(this.listaPeriodo);
        this.adminFactory= AdministracionFactory.getInstance();
        
        this.inicializarVista();
        this.inicializarEventos();
    }

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlParametrosBusqueda1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjercicios = new javax.swing.JTable();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblActivar = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        pnlParametrosBusqueda = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombreEjercicio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        lblTituloPnlDcha = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlEjercicioContable.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        pnlParametrosBusqueda1.setName("pnlParametrosBusqueda1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Activo", "Nombre", "Fecha de Inicio", "Fecha de Fin", "Plan de Cuentas"
            }
        ));
        tblEjercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblEjercicios.setName("tblEjercicios"); // NOI18N
        jScrollPane1.setViewportView(tblEjercicios);

        lblEjerciciosContables.setFont(resourceMap.getFont("lblEjerciciosContables.font")); // NOI18N
        lblEjerciciosContables.setForeground(resourceMap.getColor("lblEjerciciosContables.foreground")); // NOI18N
        lblEjerciciosContables.setText(resourceMap.getString("lblEjerciciosContables.text")); // NOI18N
        lblEjerciciosContables.setName("lblEjerciciosContables"); // NOI18N

        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblActivar.setFont(resourceMap.getFont("lblActivar.font")); // NOI18N
        lblActivar.setForeground(resourceMap.getColor("lblActivar.foreground")); // NOI18N
        lblActivar.setIcon(resourceMap.getIcon("lblActivar.icon")); // NOI18N
        lblActivar.setText(resourceMap.getString("lblActivar.text")); // NOI18N
        lblActivar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActivar.setName("lblActivar"); // NOI18N
        pnlBotonera.add(lblActivar);

        lblAgregar.setFont(resourceMap.getFont("lblAgregar.font")); // NOI18N
        lblAgregar.setForeground(resourceMap.getColor("lblAgregar.foreground")); // NOI18N
        lblAgregar.setIcon(resourceMap.getIcon("lblAgregar.icon")); // NOI18N
        lblAgregar.setText(resourceMap.getString("lblAgregar.text")); // NOI18N
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setName("lblAgregar"); // NOI18N
        pnlBotonera.add(lblAgregar);

        lblEditar.setFont(resourceMap.getFont("lblEditar.font")); // NOI18N
        lblEditar.setForeground(resourceMap.getColor("lblEditar.foreground")); // NOI18N
        lblEditar.setIcon(resourceMap.getIcon("lblEditar.icon")); // NOI18N
        lblEditar.setText(resourceMap.getString("lblEditar.text")); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.setName("lblEditar"); // NOI18N
        pnlBotonera.add(lblEditar);

        lblEliminar.setFont(resourceMap.getFont("lblEliminar.font")); // NOI18N
        lblEliminar.setForeground(resourceMap.getColor("lblEliminar.foreground")); // NOI18N
        lblEliminar.setIcon(resourceMap.getIcon("lblEliminar.icon")); // NOI18N
        lblEliminar.setText(resourceMap.getString("lblEliminar.text")); // NOI18N
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setName("lblEliminar"); // NOI18N
        pnlBotonera.add(lblEliminar);

        javax.swing.GroupLayout pnlParametrosBusqueda1Layout = new javax.swing.GroupLayout(pnlParametrosBusqueda1);
        pnlParametrosBusqueda1.setLayout(pnlParametrosBusqueda1Layout);
        pnlParametrosBusqueda1Layout.setHorizontalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusqueda1Layout.setVerticalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlParametrosBusqueda.setName("pnlParametrosBusqueda"); // NOI18N

        lblNombre.setFont(resourceMap.getFont("lblNombre.font")); // NOI18N
        lblNombre.setForeground(resourceMap.getColor("lblNombre.foreground")); // NOI18N
        lblNombre.setText(resourceMap.getString("lblNombre.text")); // NOI18N
        lblNombre.setName("lblNombre"); // NOI18N

        txtNombreEjercicio.setName("txtNombreEjercicio"); // NOI18N

        btnBuscar.setIcon(resourceMap.getIcon("btnBuscar.icon")); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setName("btnBuscar"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("xtsTitulo.foreground")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        javax.swing.GroupLayout pnlParametrosBusquedaLayout = new javax.swing.GroupLayout(pnlParametrosBusqueda);
        pnlParametrosBusqueda.setLayout(pnlParametrosBusquedaLayout);
        pnlParametrosBusquedaLayout.setHorizontalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xtsTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlParametrosBusquedaLayout.setVerticalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setIcon(resourceMap.getIcon("lblTituloPnlDcha.icon")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloPnlDcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActivar;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda;
    private javax.swing.JPanel pnlParametrosBusqueda1;
    private javax.swing.JTable tblEjercicios;
    private javax.swing.JTextField txtNombreEjercicio;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables
    
    public PnlEjercicioContable getVista() {
    	return this;
    }

    private void inicializarEventos() {
		this.btnBuscar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				activarLabel(lblActivar, false);
				activarLabel(lblEliminar, false);
				activarLabel(lblEditar, false);
				buscar();
			}
		});
		
		this.lblActivar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				activar();
			}

		});
    
		this.lblAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				agregar();
			}
		});
		
		this.lblEditar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				editar();
			}
		});
		
		this.lblEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				eliminar();
			}

		});
		
		this.tblEjercicios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowCreditos()){
					int seleccionado= tblEjercicios.getSelectedRow();
					if(!modeloEjercicios.getEjercicio(seleccionado).isActivo()){
						activarLabel(lblActivar, true);
					}
					else{
						activarLabel(lblActivar, false);
					}
					activarLabel(lblEliminar, true);
					activarLabel(lblEditar, true);
				}
			}
		});
	}
	
	private void activarLabel(JLabel pLabel, boolean pValor) {
		pLabel.setEnabled(pValor);
	}
	
	private boolean isSelectedRowCreditos(){
		return this.tblEjercicios.getSelectedRow() != -1;
	}
    private void editar() {
    	int seleccionado= this.tblEjercicios.getSelectedRow();
    	EjercicioContable locEjercicio= this.modeloEjercicios.getEjercicio(seleccionado);
    	this.adminContable.mostrarABMEjercicioContable();
    	this.adminContable.getPnlABMEjercicioContable().setEjercicio(locEjercicio);
	}
    
	private void agregar() {
		this.adminContable.mostrarABMEjercicioContable();
		this.adminContable.getPnlABMEjercicioContable().setEjercicio(new EjercicioContable());
	}

	private void activar() {
		try{
			int seleccionado= this.tblEjercicios.getSelectedRow();
			if(seleccionado!=-1){
				EjercicioContable locEjercicio= modeloEjercicios.getEjercicio(seleccionado);
				locEjercicio.setActivo(true);
				this.adminFactory.getAdmistradorEjercicioContable().activarPeriodo(locEjercicio);
			
				String mensaje="El Ejercicio  " + locEjercicio.getAnio() + " se ha establecido como Ejercicio Activo.";
				String titulo="Activar Ejercicio Contable";
				JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
				this.buscar();
			}	
		}
		catch(LogicaException e){
			JOptionPane.showMessageDialog(this, e.getMessage(), e.getTitulo(), JOptionPane.ERROR_MESSAGE);
		}
	}
	
	private void eliminar() {
		try{
			int seleccionado= this.tblEjercicios.getSelectedRow();
			EjercicioContable locEjercicio= this.modeloEjercicios.getEjercicio(seleccionado);
		
			String pMensaje= "¿Realmente desea eliminar el ejercicio contable "+locEjercicio.getAnio()+"?";
			String pTitulo= "Eliminar Ejercicio";
			int locConfirm= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
			if(locConfirm==JOptionPane.YES_OPTION){
				this.adminFactory.getAdmistradorEjercicioContable().eliminarEjercicio(locEjercicio);
				this.buscar();
				this.inicializarVista();
			}
		}
		catch (LogicaException e){
			String pMensaje=e.getMessage();
			String pTitulo=e.getTitulo();
			JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.ERROR_MESSAGE);
		}	
	}
    
	public void buscar() {
		String valorTextField = this.txtNombreEjercicio.getText().trim();
		this.nombre = Utiles.nuloSiVacio(valorTextField);
		this.listaPeriodo= this.adminFactory
				.getAdmistradorEjercicioContable()
				.findListaEjercicioContable(this.nombre);

		if(this.listaPeriodo!=null) {
			this.modeloEjercicios.setEjercicios(this.listaPeriodo);
			this.tblEjercicios.setModel(this.modeloEjercicios);
		}
	}

	public void inicializarVista() {
		activarLabel(lblActivar , false);
		activarLabel(lblEliminar , false);
		activarLabel(lblEditar , false);
		this.tblEjercicios.setModel(this.modeloEjercicios);
	}
}
