/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelFiltradoPlanCuenta.java
 *
 * Created on 28/06/2011, 21:10:16
 */

package ar.gov.cjpmv.prestamos.gui.contable;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.tree.DefaultMutableTreeNode;

import org.jdesktop.swingx.search.TreeSearchable;

import ar.gov.cjpmv.prestamos.core.business.AdministradorPlanCuenta;
import ar.gov.cjpmv.prestamos.core.persistence.contable.Cuenta;
import ar.gov.cjpmv.prestamos.core.persistence.contable.PlanCuenta;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.CuentaTreeNodeModel;
import ar.gov.cjpmv.prestamos.gui.contable.modelos.PlanCuentaTreeModel;

/**
 *
 * @author pulpol
 */
public class PnlFiltradoPlanCuenta extends JPanel {

	private static final long serialVersionUID = 8418722323259688829L;
	
	public PnlFiltradoPlanCuenta() {
		initComponents();
		configurarFiltrado();
	}
	
	/** Creates new form BeanForm */
    public PnlFiltradoPlanCuenta(PlanCuenta pPlanCuenta) {
    	this();
        setPlanCuenta(pPlanCuenta);
    }

	private void configurarFiltrado() {
		buscador = new TreeSearchable(this.tArbol);
		this.txtFiltro.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				if (txtFiltro.getText().length() >= 3) {
					buscarAction();
				}
			}
		});
	}

	private void buscarAction() {
		tArbol.expandAll();
		//Limpia los dobles espacios y lo convierte en una expresión regular
		String texto = txtFiltro.getText().replaceAll("\\s{2,}"," "); 
		texto = texto.replace(" ","^|");
		
		if (texto.equals(filtro)) {
			filtro = texto;
			ultimoIndiceBusqueda = buscador.search(filtro,ultimoIndiceBusqueda);
		}
		else {
			//el filtro cambió
			ultimoIndiceBusqueda = -1;
			filtro = texto;
			if (!filtro.trim().isEmpty()) {
				ultimoIndiceBusqueda = buscador.search(filtro);
			}
		}
	}
	
	public void setPlanCuenta(PlanCuenta pPlanCuenta) {
        planCuentaTreeModel = new PlanCuentaTreeModel(pPlanCuenta);
        this.tArbol.setModel(planCuentaTreeModel);
        tArbol.setCellRenderer(new PlanCuentaTreeCellRenderer());	
	}
	
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        spArbol = new javax.swing.JScrollPane();
        tArbol = new org.jdesktop.swingx.JXTree();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlFiltradoPlanCuenta.class);
        setBackground(resourceMap.getColor("ColorBlanco")); // NOI18N
        setName("Form"); // NOI18N

        txtFiltro.setText(resourceMap.getString("txtFiltro.text")); // NOI18N
        txtFiltro.setName("txtFiltro"); // NOI18N

        spArbol.setName("spArbol"); // NOI18N

        tArbol.setModel(null);
        tArbol.setName("tArbol"); // NOI18N
        spArbol.setViewportView(tArbol);

        btnAgregar.setIcon(resourceMap.getIcon("btnAgregar.icon")); // NOI18N
        btnAgregar.setText(resourceMap.getString("btnAgregar.text")); // NOI18N
        btnAgregar.setName("btnAgregar"); // NOI18N

        btnEliminar.setIcon(resourceMap.getIcon("btnEliminar.icon")); // NOI18N
        btnEliminar.setText(resourceMap.getString("btnEliminar.text")); // NOI18N
        btnEliminar.setName("btnEliminar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addComponent(btnEliminar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addComponent(spArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane spArbol;
    private org.jdesktop.swingx.JXTree tArbol;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    private PlanCuentaTreeModel planCuentaTreeModel;
    private TreeSearchable buscador;
    private String filtro;
    private int ultimoIndiceBusqueda;
    
  	public void cargarPlanCuenta(PlanCuenta planCuenta) {
		if (planCuenta == null) {
			planCuentaTreeModel = null;
			setEnabled(false);
		}
		else {
			planCuentaTreeModel = new PlanCuentaTreeModel(planCuenta);
			setEnabled(true);
		}

		tArbol.setModel(planCuentaTreeModel);
	}
	
	public void setEnabled(boolean enabled) {
		super.setEnabled(enabled);
		btnAgregar.setEnabled(enabled);
		btnEliminar.setEnabled(enabled);
		txtFiltro.setEnabled(enabled);
		tArbol.setEnabled(enabled);
	}
	
	public org.jdesktop.swingx.JXTree gettArbol() {
		return tArbol;
	}

	public void actualizarModeloPlanCuenta() {
		planCuentaTreeModel.refrescar();
	}
	
	public javax.swing.JButton getBtnEliminar() {
		return btnEliminar;
	}
	
	public javax.swing.JButton getBtnAgregar() {
		return btnAgregar;
	}
	
	/**
	 * Devuelve la cuenta seleccionada (si hay alguna) 
	 * @return
	 */
	public Cuenta getCuentaSeleccionada() {
		DefaultMutableTreeNode nodo = (DefaultMutableTreeNode)tArbol.getLastSelectedPathComponent();
		if ((nodo != null) && (nodo instanceof CuentaTreeNodeModel)) {
			return ((CuentaTreeNodeModel)nodo).getUserObject();
		}
		return null;
	}
}
