/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminSueldosView.java
 *
 * Created on 23/12/2011, 18:24:47
 */
package ar.gov.cjpmv.prestamos.gui.sueldos;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.SwingWorker;

import org.jdesktop.swingx.JXHyperlink;

import ar.gov.cjpmv.prestamos.core.persistence.enums.EstadoPersonaFisica;
import ar.gov.cjpmv.prestamos.gui.contable.AdminContableView;
import ar.gov.cjpmv.prestamos.gui.contable.PnlABMAsientoContable;
import ar.gov.cjpmv.prestamos.gui.contable.PnlABMCuenta;
import ar.gov.cjpmv.prestamos.gui.contable.PnlABMEjercicioContable;
import ar.gov.cjpmv.prestamos.gui.contable.PnlAdminPlanCuentas;
import ar.gov.cjpmv.prestamos.gui.contable.PnlBusquedaAsientoContable;
import ar.gov.cjpmv.prestamos.gui.contable.PnlEjercicioContable;

/**
 *
 * @author daiana
 */
public class AdminSueldosView extends javax.swing.JDialog {
    /**
	 * 
	 */
	private static final long serialVersionUID = -9185812631835138736L;
	
	
	
	private PnlAdminConcepto pnlAdminConcepto;
	private PnlAMConcepto pnlAMConcepto;
	private PnlAdminPlantilla pnlAdminPlantilla;
	private PnlAMPlantilla pnlAMPlantilla;
	private PnlAdminLiquidacionHaberes pnlAdminLiquidacionHaberes;
	private PnlAMLiquidacionHaberes pnlAMLiquidacionHaberes;
	private PnlAdminEscalaCategoria pnlAdminEscalaCategoria;
	
	
    /** Creates new form AdminSueldosView */
    public AdminSueldosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPanelesSegundoPlano();
    }

    private void cargarPanelesSegundoPlano() {
    	SwingWorker<Void, Void> segundoPlano = new SwingWorker<Void, Void>() {
			@Override
			protected Void doInBackground() throws Exception {
				getXhAdministracionConcepto().setEnabled(false);
				getXhAdministracionPlantilla().setEnabled(false);
				getXhAdministracionLiquidacionHaberes().setEnabled(false);
				getXhImprimirReciboHaberes().setEnabled(false);
				getXhEscalaSalariaActivos().setEnabled(false);
				getXhEscalaSalariaPasivos().setEnabled(false);
				
				pnlAdminConcepto= new PnlAdminConcepto(AdminSueldosView.this);
				pnlAMConcepto= new PnlAMConcepto(AdminSueldosView.this);
				pnlAdminPlantilla= new PnlAdminPlantilla(AdminSueldosView.this);
				pnlAMPlantilla= new PnlAMPlantilla(AdminSueldosView.this);
				pnlAdminLiquidacionHaberes= new PnlAdminLiquidacionHaberes(AdminSueldosView.this);
				pnlAMLiquidacionHaberes= new PnlAMLiquidacionHaberes(AdminSueldosView.this);
				pnlAdminEscalaCategoria= new PnlAdminEscalaCategoria(AdminSueldosView.this);
				
				
				inicializarEventos();
				mostrarAdminLiquidacionHaberes();
				return null;
			}

			@Override
			protected void done() {
				try {
					get();
				} catch (Exception e) {
					e.printStackTrace();
				}
				getXhAdministracionConcepto().setEnabled(true);
				getXhAdministracionPlantilla().setEnabled(true);
				getXhAdministracionLiquidacionHaberes().setEnabled(true);
				getXhImprimirReciboHaberes().setEnabled(true);
				getXhEscalaSalariaActivos().setEnabled(true);
				getXhEscalaSalariaPasivos().setEnabled(true);
				inicializarEventos();
			}
    	};
		segundoPlano.execute();
		
	}
    
    
    private void inicializarEventos() {
		getXhAdministracionConcepto().addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminConcepto();
			}
		});
		
		getXhAdministracionPlantilla().addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminPlantilla();
			}
		});
		
		getXhAdministracionLiquidacionHaberes().addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminLiquidacionHaberes();				
			}
		});
		
		getXhImprimirReciboHaberes().addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminLiquidacionHaberesImpresion();
			}
		});
		
		getXhEscalaSalariaActivos().addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminEscalaSalarial(EstadoPersonaFisica.ACTIVO);
				
			}
		});
		
		getXhEscalaSalariaPasivos().addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				mostrarAdminEscalaSalarial(EstadoPersonaFisica.PASIVO);
				
			}
		});
	
		
	}
    
    

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPrincipal = new javax.swing.JSplitPane();
        spIzquierda = new javax.swing.JScrollPane();
        pnlBotoneraSueldos1 = new ar.gov.cjpmv.prestamos.gui.sueldos.PnlBotoneraSueldos();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        spPrincipal.setDividerSize(2);
        spPrincipal.setName("spPrincipal"); // NOI18N

        spIzquierda.setMinimumSize(new java.awt.Dimension(270, 717));
        spIzquierda.setName("spIzquierda"); // NOI18N

        pnlBotoneraSueldos1.setName("pnlBotoneraSueldos1"); // NOI18N
        spIzquierda.setViewportView(pnlBotoneraSueldos1);

        spPrincipal.setLeftComponent(spIzquierda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AdminSueldosView dialog = new AdminSueldosView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.gov.cjpmv.prestamos.gui.sueldos.PnlBotoneraSueldos pnlBotoneraSueldos1;
    private javax.swing.JScrollPane spIzquierda;
    private javax.swing.JSplitPane spPrincipal;
    // End of variables declaration//GEN-END:variables
    
    
	public JXHyperlink getXhAdministracionConcepto() {
		return this.pnlBotoneraSueldos1.getXhAdministracionConcepto();
	}
	
	public JXHyperlink getXhAdministracionPlantilla() {
		return this.pnlBotoneraSueldos1.getXhAdministracionPlantilla();
	}
	
	public JXHyperlink getXhAdministracionLiquidacionHaberes() {
		return this.pnlBotoneraSueldos1.getXhGenenarionLiquidacionHaberes();
	}
		
	public JXHyperlink getXhGenerarLiquidacionHaberes() {
		return this.pnlBotoneraSueldos1.getXhGenenarionLiquidacionHaberes();
	}
	
	public JXHyperlink getXhImprimirReciboHaberes(){
		return this.pnlBotoneraSueldos1.getXhImprimirReciboHaberes();
	}
	
	public JXHyperlink getXhEscalaSalariaActivos(){
		return this.pnlBotoneraSueldos1.getXhEscalaSalarialActivos();
	}
	
	public JXHyperlink getXhEscalaSalariaPasivos(){
		return this.pnlBotoneraSueldos1.getXhEscalaSalarialPasivos();
	}
	
	public void mostrarAdminConcepto() {
		this.spPrincipal.setRightComponent(this.pnlAdminConcepto);
		this.pnlAdminConcepto.buscar();
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
	
	public void mostrarAdminPlantilla(){
		this.spPrincipal.setRightComponent(this.pnlAdminPlantilla);
		this.pnlAdminPlantilla.buscar();
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
		
	public void mostrar() {
		Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
		pantalla.height -= 30;
        this.setPreferredSize(pantalla);
        this.pack();
        this.setVisible(true);
	}
	

	public void mostrarAdminLiquidacionHaberes() {
		this.spPrincipal.setRightComponent(this.pnlAdminLiquidacionHaberes);
		this.pnlAdminLiquidacionHaberes.buscar();
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
	
	public void mostrarAdminEscalaSalarial(EstadoPersonaFisica pEstado) {
		this.spPrincipal.setRightComponent(this.pnlAdminEscalaCategoria);
		this.pnlAdminEscalaCategoria.inicializarModelo(pEstado);
		this.pnlAdminEscalaCategoria.inicializarVista();
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
	
	public void mostrarAdminLiquidacionHaberesImpresion() {
		this.spPrincipal.setRightComponent(this.pnlAdminLiquidacionHaberes);
		this.pnlAdminLiquidacionHaberes.buscarImpresion();
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
	
	public void mostrarAMConcepto() {
		this.spPrincipal.setRightComponent(this.pnlAMConcepto);
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}

	public PnlAMConcepto getPnlAMConcepto() {
		return this.pnlAMConcepto;
	}

	public void mostrarAMPlantilla() {
		this.spPrincipal.setRightComponent(this.pnlAMPlantilla);
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
		
	}

	public PnlAMPlantilla getPnlAMPlantilla() {
		return this.pnlAMPlantilla;
	}
	
	public PnlAMLiquidacionHaberes getPnlAMLiquidacionHaberes(){
		return this.pnlAMLiquidacionHaberes;
	}

	public void mostrarAMLiquidacionHaberes() {
		this.spPrincipal.setRightComponent(this.pnlAMLiquidacionHaberes);
		this.spPrincipal.repaint();
		this.spPrincipal.getRightComponent().repaint();
	}
		
	
}
