/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlAdminLiquidacionHaberes.java
 *
 * Created on 23/12/2011, 23:51:54
 */
package ar.gov.cjpmv.prestamos.gui.sueldos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.LiquidacionHaberes;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.Plantilla;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.TipoLiquidacion;
import ar.gov.cjpmv.prestamos.core.tareas.CargarViasCobro;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.Principal;
import ar.gov.cjpmv.prestamos.gui.sueldos.model.TblLiquidacionHaberesModel;

/**
 *
 * @author daiana
 */
public class PnlAdminLiquidacionHaberes extends javax.swing.JPanel {

    /** Creates new form PnlAdminLiquidacionHaberes */
  
	private AdminSueldosView adminSueldo;
	private AdministracionFactory adminFactory;
	private List<LiquidacionHaberes> listaLiquidacionHaberes;
	private DefaultComboBoxModel modeloTipoLiquidacion;
	private TipoLiquidacion tipoLiquidacion;
	private TblLiquidacionHaberesModel modeloLiquidacionHaberes;
	private Integer anio;
	private Integer mes;


    public PnlAdminLiquidacionHaberes(AdminSueldosView adminSueldosView) {
    	initComponents();
    	this.adminSueldo= adminSueldosView;
    	this.adminFactory= AdministracionFactory.getInstance();
    	this.listaLiquidacionHaberes= new ArrayList<LiquidacionHaberes>();
    	this.modeloLiquidacionHaberes= new TblLiquidacionHaberesModel(this.listaLiquidacionHaberes);
    	this.inicializarEventos();
    	this.inicializarModelo();
    	this.inicializarVista();
    	this.cbxTipoLiquidacion.setRenderer(new TipoLiquidacionCellRenderer());
	}




	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPnlDcha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlParametrosBusqueda1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLiquidaciones = new javax.swing.JTable();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblVerDetalle = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        pnlParametrosBusqueda = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        lblDescripcion = new javax.swing.JLabel();
        cbxTipoLiquidacion = new javax.swing.JComboBox();
        mchMes = new com.toedter.calendar.JMonthChooser();
        lblMes1 = new javax.swing.JLabel();
        btnBuscarImpresion = new javax.swing.JButton();
        ycAnio = new com.toedter.calendar.JYearChooser();
        lblMes = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlAdminLiquidacionHaberes.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setIcon(resourceMap.getIcon("lblTituloPnlDcha.icon")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        pnlParametrosBusqueda1.setName("pnlParametrosBusqueda1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblLiquidaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Tipo"
            }
        ));
        tblLiquidaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblLiquidaciones.setName("tblLiquidaciones"); // NOI18N
        jScrollPane1.setViewportView(tblLiquidaciones);

        lblEjerciciosContables.setFont(resourceMap.getFont("lblEjerciciosContables.font")); // NOI18N
        lblEjerciciosContables.setForeground(resourceMap.getColor("lblEjerciciosContables.foreground")); // NOI18N
        lblEjerciciosContables.setText(resourceMap.getString("lblEjerciciosContables.text")); // NOI18N
        lblEjerciciosContables.setName("lblEjerciciosContables"); // NOI18N

        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblVerDetalle.setFont(resourceMap.getFont("lblVerDetalle.font")); // NOI18N
        lblVerDetalle.setForeground(resourceMap.getColor("lblVerDetalle.foreground")); // NOI18N
        lblVerDetalle.setIcon(resourceMap.getIcon("lblVerDetalle.icon")); // NOI18N
        lblVerDetalle.setText(resourceMap.getString("lblVerDetalle.text")); // NOI18N
        lblVerDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerDetalle.setName("lblVerDetalle"); // NOI18N
        pnlBotonera.add(lblVerDetalle);

        lblAgregar.setFont(resourceMap.getFont("lblAgregar.font")); // NOI18N
        lblAgregar.setForeground(resourceMap.getColor("lblAgregar.foreground")); // NOI18N
        lblAgregar.setIcon(resourceMap.getIcon("lblAgregar.icon")); // NOI18N
        lblAgregar.setText(resourceMap.getString("lblAgregar.text")); // NOI18N
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setName("lblAgregar"); // NOI18N
        pnlBotonera.add(lblAgregar);

        lblEditar.setFont(resourceMap.getFont("lblEditar.font")); // NOI18N
        lblEditar.setForeground(resourceMap.getColor("lblEditar.foreground")); // NOI18N
        lblEditar.setIcon(resourceMap.getIcon("lblEditar.icon")); // NOI18N
        lblEditar.setText(resourceMap.getString("lblEditar.text")); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.setName("lblEditar"); // NOI18N
        pnlBotonera.add(lblEditar);

        lblEliminar.setFont(resourceMap.getFont("lblEliminar.font")); // NOI18N
        lblEliminar.setForeground(resourceMap.getColor("lblEliminar.foreground")); // NOI18N
        lblEliminar.setIcon(resourceMap.getIcon("lblEliminar.icon")); // NOI18N
        lblEliminar.setText(resourceMap.getString("lblEliminar.text")); // NOI18N
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setName("lblEliminar"); // NOI18N
        pnlBotonera.add(lblEliminar);

        javax.swing.GroupLayout pnlParametrosBusqueda1Layout = new javax.swing.GroupLayout(pnlParametrosBusqueda1);
        pnlParametrosBusqueda1.setLayout(pnlParametrosBusqueda1Layout);
        pnlParametrosBusqueda1Layout.setHorizontalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusqueda1Layout.setVerticalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblEjerciciosContables.getAccessibleContext().setAccessibleName(resourceMap.getString("lblEjerciciosContables.AccessibleContext.accessibleName")); // NOI18N

        pnlParametrosBusqueda.setName("pnlParametrosBusqueda"); // NOI18N

        btnBuscar.setIcon(resourceMap.getIcon("btnBuscar.icon")); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setName("btnBuscar"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("xtsTitulo.foreground")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        lblDescripcion.setFont(resourceMap.getFont("lblDescripcion.font")); // NOI18N
        lblDescripcion.setForeground(resourceMap.getColor("lblDescripcion.foreground")); // NOI18N
        lblDescripcion.setText(resourceMap.getString("lblDescripcion.text")); // NOI18N
        lblDescripcion.setName("lblDescripcion"); // NOI18N

        cbxTipoLiquidacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activos - Normal", "Activos - SAC", "Jubilados - Normal", "Jubilados - SAC", "Pensionados - Normal", "Pensionados - SAC" }));
        cbxTipoLiquidacion.setName("cbxTipoLiquidacion"); // NOI18N

        mchMes.setName("mchMes"); // NOI18N
        mchMes.setYearChooser(null);

        lblMes1.setFont(resourceMap.getFont("lblMes1.font")); // NOI18N
        lblMes1.setForeground(resourceMap.getColor("lblMes1.foreground")); // NOI18N
        lblMes1.setText(resourceMap.getString("lblMes1.text")); // NOI18N
        lblMes1.setName("lblMes1"); // NOI18N

        btnBuscarImpresion.setIcon(resourceMap.getIcon("btnBuscarImpresion.icon")); // NOI18N
        btnBuscarImpresion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarImpresion.setName("btnBuscarImpresion"); // NOI18N

        javax.swing.GroupLayout pnlParametrosBusquedaLayout = new javax.swing.GroupLayout(pnlParametrosBusqueda);
        pnlParametrosBusqueda.setLayout(pnlParametrosBusquedaLayout);
        pnlParametrosBusquedaLayout.setHorizontalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblMes1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mchMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusquedaLayout.setVerticalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipoLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mchMes, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(lblMes1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ycAnio.setName("ycAnio"); // NOI18N

        lblMes.setFont(resourceMap.getFont("lblMes.font")); // NOI18N
        lblMes.setForeground(resourceMap.getColor("lblMes.foreground")); // NOI18N
        lblMes.setText(resourceMap.getString("lblMes.text")); // NOI18N
        lblMes.setName("lblMes"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ycAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(ycAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloPnlDcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarImpresion;
    private javax.swing.JComboBox cbxTipoLiquidacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMes1;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JLabel lblVerDetalle;
    private com.toedter.calendar.JMonthChooser mchMes;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda;
    private javax.swing.JPanel pnlParametrosBusqueda1;
    private javax.swing.JTable tblLiquidaciones;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    private com.toedter.calendar.JYearChooser ycAnio;
    // End of variables declaration//GEN-END:variables
	
    
    
    
    public void buscar() {
    	this.actualizarModelo();
    	this.listaLiquidacionHaberes=this.adminFactory.getAdministracionLiquidacionHaberes().findLiquidacion(this.mes, this.anio, this.tipoLiquidacion);
    	if(this.listaLiquidacionHaberes==null){
    		this.listaLiquidacionHaberes= new ArrayList<LiquidacionHaberes>();
    	}				
    	this.modeloLiquidacionHaberes= new TblLiquidacionHaberesModel(this.listaLiquidacionHaberes);
    	this.tblLiquidaciones.setModel(this.modeloLiquidacionHaberes);
    	this.lblEditar.setEnabled(false);
    	this.lblEliminar.setEnabled(false);
    	this.btnBuscarImpresion.setVisible(false);
    	this.btnBuscar.setVisible(true);
    	this.lblEditar.setVisible(true);
  	    this.lblEliminar.setVisible(true);
  	    this.lblAgregar.setVisible(true);
  	    this.lblVerDetalle.setVisible(false);
	}
    
	private void actualizarModelo(){
		Integer locMes=this.mchMes.getMonth()+1;
		this.mes= locMes;
		Integer locAnio= this.ycAnio.getYear();
		this.anio= locAnio;
		this.tipoLiquidacion= (TipoLiquidacion) this.cbxTipoLiquidacion.getSelectedItem();
	}

	private void inicializarVista() {
		this.cbxTipoLiquidacion.setModel(this.modeloTipoLiquidacion);
		this.lblEditar.setEnabled(false);
		this.lblEliminar.setEnabled(false);
		this.tblLiquidaciones.setModel(this.modeloLiquidacionHaberes);
		this.cbxTipoLiquidacion.setRenderer(new TipoLiquidacionCellRenderer());
	}

	private void inicializarEventos() {
		this.btnBuscar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buscar();				
			}
		});

		this.btnBuscarImpresion.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buscarImpresion();				
			}
		});
		
		
		this.lblAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblAgregar.isEnabled()) {
					agregar();
				}
			}
		});
		
		this.lblEditar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEditar.isEnabled()) {
					editar();
				}
			}
		});
		
		this.lblVerDetalle.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblVerDetalle.isEnabled()) {
					verDetalle();
				}
			}
		});
		
		this.lblEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEliminar.isEnabled()) {
					eliminar();
				}
			}
		});
		
		this.tblLiquidaciones.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowConcepto()){
			    	lblEditar.setEnabled(true);
			    	lblEliminar.setEnabled(true);
			    	lblVerDetalle.setEnabled(true);
				}
			}
		});
	}
	
	private boolean isSelectedRowConcepto(){
		return this.tblLiquidaciones.getSelectedRow() != -1;
	}
	
	private void agregar(){
		this.adminSueldo.mostrarAMLiquidacionHaberes();
		this.adminSueldo.getPnlAMLiquidacionHaberes().setLiquidacionHaberes(new LiquidacionHaberes());
	}

	private void editar(){
		final int seleccionado= this.tblLiquidaciones.getSelectedRow();
		this.adminSueldo.mostrarAMLiquidacionHaberes();
		final CargandoLiquidacionesDialog dialogo = new CargandoLiquidacionesDialog();
		
		SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
			private LiquidacionHaberes locLiquidacion;
			
			@Override
			protected Void doInBackground() throws Exception {
				locLiquidacion = modeloLiquidacionHaberes.getLiquidacion(seleccionado);
				return null;
			}
			
			@Override
			protected void done() {
				try {
					get();
					dialogo.dispose();
					adminSueldo.getPnlAMLiquidacionHaberes().setLiquidacionHaberes(locLiquidacion);
				}
				catch(Exception e) {
					e.printStackTrace();
					JOptionPane.showMessageDialog(PnlAdminLiquidacionHaberes.this, 
							"Ha ocurrido un error al intentar obtener los datos de la liquidación.",
							"Error",
							JOptionPane.ERROR_MESSAGE);
				}
			}
		};
		worker.execute();
		dialogo.setVisible(true);
	}

	
	private void verDetalle(){
		int seleccionado= this.tblLiquidaciones.getSelectedRow();
		LiquidacionHaberes locLiquidacion= this.modeloLiquidacionHaberes.getLiquidacion(seleccionado);
		this.adminSueldo.mostrarAMLiquidacionHaberes();
		this.adminSueldo.getPnlAMLiquidacionHaberes().setLiquidacionHaberes(locLiquidacion);
		this.adminSueldo.getPnlAMLiquidacionHaberes().habilitarSoloImpresionRecibos();
	}

	private void eliminar(){
		try{
			int seleccionado= this.tblLiquidaciones.getSelectedRow();
			LiquidacionHaberes locLiquidacionHaberes= this.modeloLiquidacionHaberes.getLiquidacion(seleccionado);
			String pMensaje= "¿Realmente desea eliminar la liquidación "+locLiquidacionHaberes.getTipo()+" ("+locLiquidacionHaberes.getMes()+"-"+locLiquidacionHaberes.getAnio()+")?";
			String pTitulo= "Eliminar Plantilla";
			int locConfirm= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
			if(locConfirm==JOptionPane.YES_OPTION){
				this.adminFactory.getAdministracionLiquidacionHaberes().eliminar(locLiquidacionHaberes);
				this.buscar();
				this.inicializarVista();
			}
		}
		catch (LogicaException e){
			String pMensaje=e.getMessage();
			String pTitulo=e.getTitulo();
			JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.ERROR_MESSAGE);
		}	
	}
	
	
	public PnlAdminLiquidacionHaberes getVista() {
	    return this;
	}
	    

	
	private void inicializarModelo() {
		List<TipoLiquidacion> listaTipoLiquidacion= new ArrayList<TipoLiquidacion>();
		listaTipoLiquidacion.add(0, null);
		for(TipoLiquidacion cadaTipo: TipoLiquidacion.values()){
			listaTipoLiquidacion.add(cadaTipo);
		}
		this.modeloTipoLiquidacion= new DefaultComboBoxModel(listaTipoLiquidacion.toArray());
	}




	public void buscarImpresion() {
	    this.actualizarModelo();
	    this.listaLiquidacionHaberes=this.adminFactory.getAdministracionLiquidacionHaberes().findLiquidacion(this.mes, this.anio, this.tipoLiquidacion);
	    if(this.listaLiquidacionHaberes==null){
	    	this.listaLiquidacionHaberes= new ArrayList<LiquidacionHaberes>();
	    }				
	    this.modeloLiquidacionHaberes= new TblLiquidacionHaberesModel(this.listaLiquidacionHaberes);
	    this.tblLiquidaciones.setModel(this.modeloLiquidacionHaberes);
	    this.lblEditar.setVisible(false);
	    this.lblEliminar.setVisible(false);
	    this.lblAgregar.setVisible(false);
	    this.lblVerDetalle.setVisible(true);
	    this.lblVerDetalle.setEnabled(false);
	    this.btnBuscarImpresion.setVisible(true);
	    this.btnBuscar.setVisible(false);
	}

    
    
}
