/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlAdminConcepto.java
 *
 * Created on 23/12/2011, 19:02:37
 */
package ar.gov.cjpmv.prestamos.gui.sueldos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.ConceptoHaberes;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.ConceptoPrefijado;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.sueldos.model.TblConceptoHaberesModel;
import ar.gov.cjpmv.prestamos.gui.utiles.Utiles;

/**
 *
 * @author daiana
 */
public class PnlAdminConcepto extends javax.swing.JPanel {

	private AdminSueldosView adminSueldo;
	private List<ConceptoHaberes> listaConcepto;
	private TblConceptoHaberesModel modeloConcepto;
	private AdministracionFactory adminFactory;
	private Integer codigo;
	private String descripcion;

    
    
    public PnlAdminConcepto(AdminSueldosView adminSueldoView) {
        initComponents();
      
        this.adminSueldo= adminSueldoView;
        this.listaConcepto= new ArrayList<ConceptoHaberes>();
        this.modeloConcepto= new TblConceptoHaberesModel(this.listaConcepto);
        this.adminFactory= AdministracionFactory.getInstance();
        this.inicializarVista();
        this.inicializarEventos();
    }

   


	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlParametrosBusqueda1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConcepto = new javax.swing.JTable();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        pnlParametrosBusqueda = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        xtsTitulo = new org.jdesktop.swingx.JXTitledSeparator();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblTituloPnlDcha = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlAdminConcepto.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        pnlParametrosBusqueda1.setName("pnlParametrosBusqueda1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblConcepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Tipo"
            }
        ));
        tblConcepto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblConcepto.setName("tblConcepto"); // NOI18N
        jScrollPane1.setViewportView(tblConcepto);

        lblEjerciciosContables.setFont(resourceMap.getFont("lblEjerciciosContables.font")); // NOI18N
        lblEjerciciosContables.setForeground(resourceMap.getColor("lblEjerciciosContables.foreground")); // NOI18N
        lblEjerciciosContables.setText(resourceMap.getString("lblEjerciciosContables.text")); // NOI18N
        lblEjerciciosContables.setName("lblEjerciciosContables"); // NOI18N

        pnlBotonera.setName("pnlBotonera"); // NOI18N
        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblAgregar.setFont(resourceMap.getFont("lblAgregar.font")); // NOI18N
        lblAgregar.setForeground(resourceMap.getColor("lblAgregar.foreground")); // NOI18N
        lblAgregar.setIcon(resourceMap.getIcon("lblAgregar.icon")); // NOI18N
        lblAgregar.setText(resourceMap.getString("lblAgregar.text")); // NOI18N
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setName("lblAgregar"); // NOI18N
        pnlBotonera.add(lblAgregar);

        lblEditar.setFont(resourceMap.getFont("lblEditar.font")); // NOI18N
        lblEditar.setForeground(resourceMap.getColor("lblEditar.foreground")); // NOI18N
        lblEditar.setIcon(resourceMap.getIcon("lblEditar.icon")); // NOI18N
        lblEditar.setText(resourceMap.getString("lblEditar.text")); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.setName("lblEditar"); // NOI18N
        pnlBotonera.add(lblEditar);

        lblEliminar.setFont(resourceMap.getFont("lblEliminar.font")); // NOI18N
        lblEliminar.setForeground(resourceMap.getColor("lblEliminar.foreground")); // NOI18N
        lblEliminar.setIcon(resourceMap.getIcon("lblEliminar.icon")); // NOI18N
        lblEliminar.setText(resourceMap.getString("lblEliminar.text")); // NOI18N
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setName("lblEliminar"); // NOI18N
        pnlBotonera.add(lblEliminar);

        javax.swing.GroupLayout pnlParametrosBusqueda1Layout = new javax.swing.GroupLayout(pnlParametrosBusqueda1);
        pnlParametrosBusqueda1.setLayout(pnlParametrosBusqueda1Layout);
        pnlParametrosBusqueda1Layout.setHorizontalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusqueda1Layout.setVerticalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addGroup(pnlParametrosBusqueda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEjerciciosContables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlParametrosBusqueda.setName("pnlParametrosBusqueda"); // NOI18N

        lblCodigo.setFont(resourceMap.getFont("lblCodigo.font")); // NOI18N
        lblCodigo.setForeground(resourceMap.getColor("lblCodigo.foreground")); // NOI18N
        lblCodigo.setText(resourceMap.getString("lblCodigo.text")); // NOI18N
        lblCodigo.setName("lblCodigo"); // NOI18N

        txtCodigo.setName("txtCodigo"); // NOI18N

        btnBuscar.setIcon(resourceMap.getIcon("btnBuscar.icon")); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setName("btnBuscar"); // NOI18N

        xtsTitulo.setForeground(resourceMap.getColor("xtsTitulo.foreground")); // NOI18N
        xtsTitulo.setFont(resourceMap.getFont("xtsTitulo.font")); // NOI18N
        xtsTitulo.setName("xtsTitulo"); // NOI18N
        xtsTitulo.setTitle(resourceMap.getString("xtsTitulo.title")); // NOI18N

        lblDescripcion.setFont(resourceMap.getFont("lblDescripcion.font")); // NOI18N
        lblDescripcion.setForeground(resourceMap.getColor("lblDescripcion.foreground")); // NOI18N
        lblDescripcion.setText(resourceMap.getString("lblDescripcion.text")); // NOI18N
        lblDescripcion.setName("lblDescripcion"); // NOI18N

        txtDescripcion.setName("txtDescripcion"); // NOI18N

        javax.swing.GroupLayout pnlParametrosBusquedaLayout = new javax.swing.GroupLayout(pnlParametrosBusqueda);
        pnlParametrosBusqueda.setLayout(pnlParametrosBusquedaLayout);
        pnlParametrosBusquedaLayout.setHorizontalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xtsTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusquedaLayout.setVerticalGroup(
            pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xtsTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosBusquedaLayout.createSequentialGroup()
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlParametrosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscar))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(pnlParametrosBusqueda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlParametrosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        lblTituloPnlDcha.setFont(resourceMap.getFont("lblTituloPnlDcha.font")); // NOI18N
        lblTituloPnlDcha.setForeground(resourceMap.getColor("lblTituloPnlDcha.foreground")); // NOI18N
        lblTituloPnlDcha.setIcon(resourceMap.getIcon("lblTituloPnlDcha.icon")); // NOI18N
        lblTituloPnlDcha.setText(resourceMap.getString("lblTituloPnlDcha.text")); // NOI18N
        lblTituloPnlDcha.setName("lblTituloPnlDcha"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloPnlDcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPnlDcha)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda;
    private javax.swing.JPanel pnlParametrosBusqueda1;
    private javax.swing.JTable tblConcepto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private org.jdesktop.swingx.JXTitledSeparator xtsTitulo;
    // End of variables declaration//GEN-END:variables
    
    
    private void inicializarEventos() {
		this.btnBuscar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buscar();
			}
		});
		
		this.lblAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblAgregar.isEnabled()) {
					agregar();
				}
			}
		});
		
		this.lblEditar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEditar.isEnabled()) {
					editar();
				}
			}
		});
		
		this.lblEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEliminar.isEnabled()) {
					eliminar();
				}
			}

		});
		
		this.tblConcepto.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowConcepto()){
					int seleccionado= tblConcepto.getSelectedRow();
			    	ConceptoHaberes locConcepto= modeloConcepto.getConcepto(seleccionado);
			    	if(!(locConcepto instanceof ConceptoPrefijado)){
			    		lblEditar.setEnabled(true);
						lblEliminar.setEnabled(true);
			    	}
			    	else{
			    		lblEditar.setEnabled(false);
						lblEliminar.setEnabled(false);
			    	}
				}
			}
		});
		
	}


	private void inicializarVista() {
		activarLabel(lblAgregar , true);
		activarLabel(lblEliminar , false);
		activarLabel(lblEditar , false);
		this.tblConcepto.setModel(this.modeloConcepto);
		
	}

	
	public void buscar() {
		activarLabel(lblAgregar , true);
		activarLabel(lblEliminar , false);
		activarLabel(lblEditar , false);
		try{
			this.codigo= null;
			String cadenaCodigo= Utiles.nuloSiVacio(this.txtCodigo.getText().trim());
			if(cadenaCodigo!=null){
				try{
					this.codigo= Integer.parseInt(cadenaCodigo);
				}
				catch(NumberFormatException e){
					int codigoError= 17;
					String campo="código";
					throw new LogicaException(codigoError, campo);
				}
			}
			this.descripcion= Utiles.nuloSiVacio(this.txtDescripcion.getText().trim());
			this.listaConcepto= this.adminFactory
					.getAdministracionConceptoHaberes()
					.findConceptosHaberes(this.codigo, this.descripcion);
		
	
			if(this.listaConcepto==null) {
				this.listaConcepto= new ArrayList<ConceptoHaberes>();
			}
			this.modeloConcepto= new TblConceptoHaberesModel(this.listaConcepto);
			this.tblConcepto.setModel(this.modeloConcepto);
		
		}
		catch(LogicaException e){
			JOptionPane.showMessageDialog(this, e.getMessage(), e.getTitulo(), JOptionPane.ERROR_MESSAGE);
		}
	}
	
	
	private void activarLabel(JLabel pLabel, boolean pValor) {
		pLabel.setEnabled(pValor);
	}
	
	private boolean isSelectedRowConcepto(){
		return this.tblConcepto.getSelectedRow() != -1;
	}
	
    private void editar() {
    	try {
    		
	    	int seleccionado= this.tblConcepto.getSelectedRow();
	    	ConceptoHaberes locConcepto= this.modeloConcepto.getConcepto(seleccionado);
	    	if(!(locConcepto instanceof ConceptoPrefijado)){
	    		this.adminSueldo.mostrarAMConcepto();
	    		this.adminSueldo.getPnlAMConcepto().setConcepto(locConcepto);
	    	}
	    	else{
	    		int codigo= 36;
	    		String campo="No tiene permiso para editar un concepto prefijado.";
	    		throw new LogicaException(codigo, campo);
	    	}
    	}
    	catch(LogicaException e) {
    		JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    	}
	}
    
	private void agregar() {
		this.adminSueldo.mostrarAMConcepto();
		this.adminSueldo.getPnlAMConcepto().nuevoConcepto();
	}
	
	private void eliminar() {
		try{
			int seleccionado= this.tblConcepto.getSelectedRow();
			ConceptoHaberes locConceptoHaberes= this.modeloConcepto.getConcepto(seleccionado);
			if(!(locConceptoHaberes instanceof ConceptoPrefijado)){
				Integer codigoConcepto= locConceptoHaberes.getCodigo();
				String pMensaje= "¿Realmente desea eliminar el concepto de haberes "+codigoConcepto.toString()+" "+locConceptoHaberes.getDescripcion()+"?";
				String pTitulo= "Eliminar Concepto de Haberes";
				int locConfirm= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
				if(locConfirm==JOptionPane.YES_OPTION){
					this.adminFactory.getAdministracionConceptoHaberes().eliminar(locConceptoHaberes);
					this.buscar();
					this.inicializarVista();

			
				}
			}
			else{
				int codigo= 36;
	    		String campo="No tiene permiso para eliminar un concepto prefijado.";
	    		throw new LogicaException(codigo, campo);
			}
		}
		catch (LogicaException e){
			String pMensaje=e.getMessage();
			String pTitulo=e.getTitulo();
			JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.ERROR_MESSAGE);
		}	
	}
	
	
    public PnlAdminConcepto getVista() {
    	return this;
    }
    
}
