/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPlantillaView.java
 *
 * Created on 23/12/2011, 22:59:43
 */

package ar.gov.cjpmv.prestamos.gui.sueldos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ar.gov.cjpmv.prestamos.core.business.exceptions.LogicaException;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.ConceptoHaberes;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.ConceptoPrefijado;
import ar.gov.cjpmv.prestamos.core.persistence.sueldos.Plantilla;
import ar.gov.cjpmv.prestamos.gui.AdministracionFactory;
import ar.gov.cjpmv.prestamos.gui.sueldos.model.TblConceptoHaberesModel;
import ar.gov.cjpmv.prestamos.gui.sueldos.model.TblPlantillaModel;
import ar.gov.cjpmv.prestamos.gui.utiles.Utiles;

/**
 *
 * @author daiana
 */
public class PnlAdminPlantilla extends javax.swing.JPanel {

	private AdminSueldosView adminSueldo;
	private List<Plantilla> listaPlantilla;
	private AdministracionFactory adminFactory;
	private TblPlantillaModel plantillaModelo;
	
    
    
    public PnlAdminPlantilla(AdminSueldosView adminSueldoView) {
        initComponents();
        this.adminSueldo= adminSueldoView;
        this.listaPlantilla= new ArrayList<Plantilla>();
        this.plantillaModelo= new TblPlantillaModel(this.listaPlantilla);
        this.adminFactory= AdministracionFactory.getInstance();
        this.inicializarVista();
        this.inicializarEventos();
    }



	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlParametrosBusqueda1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlantilla = new javax.swing.JTable();
        lblEjerciciosContables = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblTituloPnlDcha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 238, 244));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblPlantilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Tipo"
            }
        ));
        tblPlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tblPlantilla);

        lblEjerciciosContables.setFont(new java.awt.Font("Tahoma 11", 1, 11));
        lblEjerciciosContables.setForeground(new java.awt.Color(102, 102, 102));
        lblEjerciciosContables.setText("Plantillas");

        pnlBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblAgregar.setFont(new java.awt.Font("Tahoma 11", 1, 11));
        lblAgregar.setForeground(new java.awt.Color(102, 102, 102));
        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/gov/cjpmv/prestamos/gui/comunes/resources/BtnAgregar.png"))); // NOI18N
        lblAgregar.setText("Agregar");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonera.add(lblAgregar);

        lblEditar.setFont(new java.awt.Font("Tahoma 11", 1, 11));
        lblEditar.setForeground(new java.awt.Color(102, 102, 102));
        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/gov/cjpmv/prestamos/gui/comunes/resources/BtnModificar.png"))); // NOI18N
        lblEditar.setText("Editar");
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonera.add(lblEditar);

        lblEliminar.setFont(new java.awt.Font("Tahoma 11", 1, 11));
        lblEliminar.setForeground(new java.awt.Color(102, 102, 102));
        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/gov/cjpmv/prestamos/gui/comunes/resources/BtnEliminar.png"))); // NOI18N
        lblEliminar.setText("Eliminar");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonera.add(lblEliminar);

        org.jdesktop.layout.GroupLayout pnlParametrosBusqueda1Layout = new org.jdesktop.layout.GroupLayout(pnlParametrosBusqueda1);
        pnlParametrosBusqueda1.setLayout(pnlParametrosBusqueda1Layout);
        pnlParametrosBusqueda1Layout.setHorizontalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlParametrosBusqueda1Layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlParametrosBusqueda1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .add(pnlParametrosBusqueda1Layout.createSequentialGroup()
                        .add(lblEjerciciosContables, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(pnlBotonera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 285, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlParametrosBusqueda1Layout.setVerticalGroup(
            pnlParametrosBusqueda1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlParametrosBusqueda1Layout.createSequentialGroup()
                .add(pnlParametrosBusqueda1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblEjerciciosContables, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlBotonera, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .add(9, 9, 9)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlParametrosBusqueda1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlParametrosBusqueda1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTituloPnlDcha.setFont(new java.awt.Font("Verdana 11 11 11 11", 1, 11));
        lblTituloPnlDcha.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloPnlDcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/gov/cjpmv/prestamos/gui/comunes/resources/LblFlecha.png"))); // NOI18N
        lblTituloPnlDcha.setText("Administración General: Plantilla");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 548, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblTituloPnlDcha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblTituloPnlDcha)
                .add(11, 11, 11)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEjerciciosContables;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblTituloPnlDcha;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlParametrosBusqueda1;
    private javax.swing.JTable tblPlantilla;
    // End of variables declaration//GEN-END:variables
    
    

    private void inicializarEventos() {
		this.lblAgregar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblAgregar.isEnabled()) {
					agregar();
				}
			}
		});
		
		this.lblEditar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEditar.isEnabled()) {
					editar();
				}
			}
		});
		
		this.lblEliminar.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (lblEliminar.isEnabled()) {
					eliminar();
				}
			}

		});
		
		this.tblPlantilla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent arg0){
				if(isSelectedRowConcepto()){
			    	activarLabel(lblEliminar, true);
					activarLabel(lblEditar, true);
				}
			}
		});
		
	}

    private void agregar() {
    	this.adminSueldo.mostrarAMPlantilla();
    	this.adminSueldo.getPnlAMPlantilla().setPlantilla(new Plantilla());
		
	}
    
    private void editar() {
    	int seleccionado= this.tblPlantilla.getSelectedRow();
    	Plantilla locPlantilla= this.plantillaModelo.getPlantilla(seleccionado);
    	this.adminSueldo.mostrarAMPlantilla();
    	this.adminSueldo.getPnlAMPlantilla().setPlantilla(locPlantilla);
		
	}
    
    private void eliminar() {
    	try{
    		int seleccionado= this.tblPlantilla.getSelectedRow();
    		Plantilla locPlantilla= this.plantillaModelo.getPlantilla(seleccionado);
    		String pMensaje= "¿Realmente desea eliminar la plantilla "+locPlantilla.getTipoLiquidacion().getCadena()+"?";
			String pTitulo= "Eliminar Plantilla";
			int locConfirm= JOptionPane.showConfirmDialog(this, pMensaje, pTitulo, JOptionPane.YES_NO_OPTION);
			if(locConfirm==JOptionPane.YES_OPTION){
				this.adminFactory.getAdministracionPlantilla().eliminar(locPlantilla);
				this.buscar();
				this.inicializarVista();
			}
    	}
		catch (LogicaException e){
			String pMensaje=e.getMessage();
			String pTitulo=e.getTitulo();
			JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.ERROR_MESSAGE);
		}	
	}
	
	
    public PnlAdminPlantilla getVista() {
    	return this;
    }
    
    
	private void inicializarVista() {
		this.lblEliminar.setVisible(false);
		activarLabel(lblAgregar , true);
		activarLabel(lblEliminar , false);
		activarLabel(lblEditar , false);
		this.tblPlantilla.setModel(this.plantillaModelo);
	}

	private void activarLabel(JLabel pLabel, boolean pValor) {
		pLabel.setEnabled(pValor);
	}

	private boolean isSelectedRowConcepto(){
		return this.tblPlantilla.getSelectedRow() != -1;
	}
	
	public void buscar() {
		activarLabel(lblAgregar , true);
		activarLabel(lblEliminar , false);
		activarLabel(lblEditar , false);
		this.listaPlantilla= this.adminFactory.getAdministracionPlantilla().getPlantillas();
		if(this.listaPlantilla==null) {
			this.listaPlantilla= new ArrayList<Plantilla>();
		}
		this.plantillaModelo= new TblPlantillaModel(this.listaPlantilla);
		this.tblPlantilla.setModel(this.plantillaModelo);
	}

	
	
}
