/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlPlantilla.java
 *
 * Created on 23/12/2011, 23:29:34
 */
package ar.gov.cjpmv.prestamos.gui.sueldos;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author daiana
 */
public class PnlPlantilla extends javax.swing.JPanel {

    /** Creates new form PnlPlantilla */
    public PnlPlantilla() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTipoLiquidacion = new javax.swing.JComboBox();
        lblDescripcion1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlantilla = new javax.swing.JTable();
        lblDescripcion2 = new javax.swing.JLabel();
        lblQuitar = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        cbxTipoLiquidacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activos - Normal", "Activos - SAC", "Jubilados - Normal", "Jubilados - SAC", "Pensionados - Normal", "Pensionados - SAC" }));
        cbxTipoLiquidacion.setName("cbxTipoLiquidacion"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.gov.cjpmv.prestamos.gui.Principal.class).getContext().getResourceMap(PnlPlantilla.class);
        lblDescripcion1.setFont(resourceMap.getFont("lblDescripcion1.font")); // NOI18N
        lblDescripcion1.setForeground(resourceMap.getColor("lblDescripcion1.foreground")); // NOI18N
        lblDescripcion1.setText(resourceMap.getString("lblDescripcion1.text")); // NOI18N
        lblDescripcion1.setName("lblDescripcion1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblPlantilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlantilla.setName("tblPlantilla"); // NOI18N
        jScrollPane1.setViewportView(tblPlantilla);

        lblDescripcion2.setFont(resourceMap.getFont("lblDescripcion2.font")); // NOI18N
        lblDescripcion2.setForeground(resourceMap.getColor("lblDescripcion2.foreground")); // NOI18N
        lblDescripcion2.setText(resourceMap.getString("lblDescripcion2.text")); // NOI18N
        lblDescripcion2.setName("lblDescripcion2"); // NOI18N

        lblQuitar.setFont(resourceMap.getFont("lblQuitar.font")); // NOI18N
        lblQuitar.setForeground(resourceMap.getColor("lblQuitar.foreground")); // NOI18N
        lblQuitar.setIcon(resourceMap.getIcon("lblQuitar.icon")); // NOI18N
        lblQuitar.setText(resourceMap.getString("lblQuitar.text")); // NOI18N
        lblQuitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuitar.setName("lblQuitar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cbxTipoLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(lblQuitar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblDescripcion1.getAccessibleContext().setAccessibleName(resourceMap.getString("lblDescripcion1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxTipoLiquidacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblQuitar;
    private javax.swing.JTable tblPlantilla;
    // End of variables declaration//GEN-END:variables
    
    
    public JComboBox getCbxTipoLiquidacion(){
    	return this.cbxTipoLiquidacion;
    }
    
    public JLabel getLblQuitar(){
    	return this.lblQuitar;
    }
    
    public JTable getTblPlantilla(){
    	return this.tblPlantilla;
    }
    
    
}
